app/mon/eCALMon/src/Widgets/Models/ProcessTreeItem.cpp, samples/cpp/services/math_server/src/math_server.cpp
Hello Rex,
if we add these two #includes, eCAL compiles out of the box on Arch Linux. If these changes do not bother your target OS, I'd like to ask for a merge.
Best regards,
Tobias
=> Make eCAL compile on current Arch Linux.

.appveyor.yml
To build documentation for window platform switch on CMake option BUILD_DOCS.
=> Fix .appveyor.yml file

README.md, ecal/core/include/ecal/cimpl/ecal_core_cimpl.h, ecal/core/include/ecal/cimpl/ecal_subscriber_cimpl.h, ecal/core/include/ecal/ecal_subscriber.h, ecal/core/src/ecalc.cpp, samples/c/minimal/minimal_rec/src/minimal_rec.c
2 new functions implemented 
```
int eCAL_Sub_Receive_ToBuffer(ECAL_HANDLE handle_, void* buf_, int buf_len_, long long* time_, int rcv_timeout_);
```
and 
```
int eCAL_Sub_Receive_Alloc(ECAL_HANDLE handle_, void** buf_, long long* time_, int rcv_timeout_); 
```
to replace the common eCAL_Sub_Receive (which is now deprecated). This should fix #51
=> eCAL_Sub_Receive new signatures (#51)

README.md
Why: Link pointing to HDF5 Group
=> What: update URL for ROS2 eCAL Middleware

.github/workflows/build-ubuntu-18.yml, .github/workflows/build-ubuntu-20.yml
Downgraded GitHub Actions GCC/G++ Verisons on Ubuntu 18.04. Github Actions uses a PPA, which introduces libgcc-s1 as dependency. That package is not available by default on Ubuntu 18 (The package is called libgcc1)
The Solution is to
1. Download the official libgcc1
2. `ppa-purge` the ppa
3. Install the downloaded libgcc1 with dpkg (ppa-purge will brick the system, this will un-brick it again 😉)
Code:
``` bash
sudo apt-get -y update
echo "Creating directory for libgcc1"
mkdir libgcc1_deb
cd libgcc1_deb
pwd
echo "Downloading bionic-security libgcc1"
apt-get download -t bionic-security libgcc1
echo "Purging GH Actions toolchain PPA"
sudo apt-get -y install ppa-purge
sudo ppa-purge -y ubuntu-toolchain-r/test
echo "installing libgcc1_deb"
sudo dpkg -i *
echo "Installing g++"
sudo apt-get -y …
```
=> Fix GitHub Actions Ubuntu18.04 libgcc1 / libgcc-s1 dependency issue

.github/workflows/build-ubuntu-18.yml, .github/workflows/build-ubuntu-20.yml, .github/workflows/build-ubuntu-iceoryx.yml, app/mon/mon_gui/src/plugin/plugin_manager.cpp, app/rec/rec_client_core/src/addons/addon_manager.cpp, cpack/cpack_variables.cmake, ecal/core/src/ecal_config.cpp, ecal/core/src/ecal_def.h, ecal/core/src/ecal_defs.h.in
mon plugins, rec addons and ecal.ini are now loaded by using the paths used by CMake. The CPACK_PACKAGING_INSTALL_PREFIX is set to the CMAKE_INSTALL_PREFIX to achieve that.
Fixes #129
=> Multiarch support by using CMake Paths

.github/workflows/build-windows.yml, CMakeLists.txt, doc/rst/development/building_ecal_from_source.rst, thirdparty/cmake_functions/qt/qt_msvc_path.cmake
The old QT_ROOT_DIRECTORY is not used anymore. The autodetection aims for upwards-compatibility, which will work as long as Microsoft doesn't change their 2-year-Visual-Studio-schedule and uses 10 MSVC_VERSION numbers per Visual Studio.
Fixes #170
=> Qt is now auto-detected on Windows

app/play/play_gui/src/widgets/settings_widget/settings_widget.cpp
Fixed a bug that caused the playback limits to get stuck when loading a measurement
=> Fixed player limits getting stuck

CMakeLists.txt, app/mon/mon_gui/src/ecalmon.cpp, app/mon/mon_gui/src/widgets/log_widget/log_widget.cpp, app/mon/mon_gui/src/widgets/models/group_tree_model.cpp, app/mon/mon_gui/src/widgets/models/plugin_table_model.cpp, app/mon/mon_gui/src/widgets/visualisation_widget/visualisation_widget.cpp, app/mon/mon_plugins/monitor_tree_view/CMakeLists.txt, app/play/play_core/src/ecal_play.cpp, app/sys/sys_cli/src/command_executor.h, app/sys/sys_cli/src/commands/command.h, app/sys/sys_cli/src/commands/helpers.h, app/sys/sys_cli/src/commands/list.cpp, app/sys/sys_cli/src/ecalsys_cli.cpp, app/sys/sys_cli/src/ecalsys_service.h, app/sys/sys_client_cli/src/ecal_sys_client_cli.cpp, app/sys/sys_gui/src/widgets/treemodels/group_tree_item.cpp, app/util/launcher/src/main_window.cpp, app/util/launcher/src/main_window.h, contrib/mma/CMakeLists.txt, contrib/mma/include/mma.h, contrib/mma/include/mma_impl.h, contrib/mma/include/windows/mma_windows.h, contrib/mma/src/mma_application.cpp, ecal/core/src/service/ecal_tcpclient.cpp, ecal/pb/CMakeLists.txt, lib/CustomQt/include/CustomQt/QSizeHintFrame.h, samples/cpp/services/ecalplayer_gui_client/CMakeLists.txt, samples/cpp/services/ecalplayer_gui_client/src/ecalplayer_gui_client.cpp, samples/cpp/services/rec_client_service_gui/CMakeLists.txt, thirdparty/cmake_functions/protoc_functions/protoc_generate_cpp.cmake
eCAL is now compile-warning-free up to gcc 10.2 / MSVC 2019 / Qt 5.15.
Also fixed a compile issue on Ubuntu 16.04 (gcc 5).
=> Fixed MSVC and gcc warnings

.github/workflows/build-macos.yml
The new Protobuf Version (3.15.4) prevents compiling of samples. See #199
=> Removed samples and test-builds for macOS

CMakeLists.txt, cmake/Modules/Findasio.cmake, cmake/Modules/Findsimpleini.cmake, cmake/Modules/Findtclap.cmake, contrib/ecalhdf5/CMakeLists.txt, testing/contrib/cross/.dockerignore, testing/contrib/cross/.gitignore, testing/contrib/cross/Makefile, testing/contrib/cross/README.md, testing/contrib/cross/host/Dockerfile, testing/contrib/cross/target/ubuntu18.Dockerfile, testing/contrib/cross/toolchain-arm64.cmake
Adds a set of files under `testing/contrib/cross` which allows one to quickly setup a cross-compilation environment example and test the building of eCAL using this environment. 
There are two Docker containers constructed: "target" and "host"
The "target" is a simple arm64 container (built using QEMU) used to emulate having an ARM64 system root with some pre-built binaries, for example libssl and hdf5. The exact libraries present can be changed in order to test different build scenarios/flags. 
The "host" is a basic C++ Debian environment with GCC8 aarch64 compiler and an updated Protobuf compiler installed.
The build script provided in the README executes a sequence of steps:
1. dump the "target" container's filesystem so it can be referenced by the cross toolchain
2. spin up the "host" …
=> Cross-compilation (arm64) example and build fixture, some CMake fixes

CMakeLists.txt
from outside when running CMake, in case it's a build from a source only folder (no git repo)
=> Introduce a cache variable to set a build version

CMakeLists.txt
... as it can lead to strange install behavior. Consumers should set it to their needs from outside
=> Remove ancient switch for install prefix default

app/rec/rec_addon_core/src/time_limited_queue.h, samples/cpp/multiple/multiple_snd/src/multiple_snd.cpp
As discussed in #285, here's the pull request.
It only adds two explicit includes that are no longer implicitly available with GCC 11.
=> Add some explicit includes to support building with GCC 11

cmake/eCALConfig.cmake.in
CMake currently does not resolve the path to QT's RCC compiler properly in RelWithDebInfo and in MinSizeRel mode.
In these cases currently it tries to search the compiler with a suffix "Release" however this compiler is not specific to the Build_Type.
In the issue mentioned below it is requested that the compiler should fall back to no suffix in this case.
However as cmake does not support this fallback, they proposed a workaround to provide an empty string.
This works quite fine on my side. However I currently have to manually override this file every time I am updating the conan dependencies
=> Fixed RelWithDebInfo and MinSizeRel mode for QT

app/rec/rec_gui/src/qecalrec.cpp
The blacklist and whitelist dialog and the corresponding buttons are now properly updated when loading a config or creating a new one.
Fixes #300
=> Rec GUI: fixed blacklist/whitelist dialog

doc/rst/conf.py, requirements.txt
Sphinx 4 seems to have severe issues rendering code-blocks nicely. This kinda disqualifies it unfortunately. So let's try this again with Sphinx 3.5.4 and hope everything just looks as it used to look.
The issues with Sphinx 4 are:
- The API becomes unreadable, Sphinx chooses a light color scheme on a light background
- The default color scheme for code blocks is a dark scheme on dark background. This can be changes though, via pygments_style.
- The Line numbers in code-blocks get selected too, when selecting the text with the mouse. So copy and paste has the line-numbers at the beginning of each line. Everybody hates that.
=> Downgraded Sphinx again

doc/rst/development/ecal_cmake_options.rst
sync with documentation cmake options in [1]
[1]
https://continental.github.io/ecal/development/ecal_cmake_options.html
Signed-off-by: Phong Tran <tranmanphong@gmail.com>
=> CMakeLists.txt: Change default option BUILD_SAMPLES to OFF

lib/Udpcap/src/udpcap_socket_private.cpp
The memory leak occured when handling fragmented IP traffic while having NPCAP turned on on Windows.
=> Udpcap: Fixed Memory leak

lib/Udpcap/CMakeLists.txt, lib/Udpcap/src/ip_reassembly.cpp, lib/Udpcap/src/ip_reassembly.h, lib/Udpcap/src/udpcap_socket_private.cpp, lib/Udpcap/src/udpcap_socket_private.h
Earlier versions of Udpcap had an issue with IP Reassembly. The issue actually was inside the used Pcap++ library, which would store fragments basically forever. The IPv4 ID however is only a 16 bit value, which overflows quite easily. So once this value overflows, the Pcap++ library will mix up old and new fragments and create faulty IP packets.
The issue was solved by wrapping the Pcap++ IPReassembly class with a custom one. The outer class keeps track of the last-use-timestamp for all packets that haven't been assembled, yet. When a packet is tool old it will be removed from the Pcap++ IPReassembly and not used any more.
=> Core/Udpcap: Fixed IP reassembly

CMakeLists.txt
Re-added the terrible hack that adds the hdf5 targets to the eCALCoreTargets. Unfortunatelly this seems to be necessary at the moment to not break compatibility with 5.9 or lower.
=> CMake: Added HDF5 targets to eCALCoreTargets again

doc/rst/getting_started/hello_world.rst, doc/rst/getting_started/hello_world_proto.rst, doc/rst/getting_started/src/hello_world/hello_world_rec/CMakeLists.txt, doc/rst/getting_started/src/hello_world/hello_world_snd/CMakeLists.txt, doc/rst/getting_started/src/hello_world_protobuf/protobuf_rec/CMakeLists.txt, doc/rst/getting_started/src/hello_world_protobuf/protobuf_snd/CMakeLists.txt
Removed the old PROTOBUF_USE_DLL with set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON), so CMake will properly use the installed protobuf config instead of the generic find script.
=> Doc: Improved Hello World CMakeLists.txt

app/mon/mon_cli/src/ecal_mon.cpp
The compile issue was caused by an unscoped (non-class) enum in ecal mon cli, that caused duplicate definitions.
=> Fixed compile issue of eCAL 5.8 on Ubuntu 21.10

ecal/core/include/ecal/msg/protobuf/dynamic_subscriber.h
Recently support for handling default (zero-byte) protobuf messages was fixed in v5.9.1. Logic was placed in `subscriber.h` to handle this new case. However, the logic to handle it in `dynamic_subscriber.h` was also missing. This PR adds that logic.
The dynamic subscriber callback doesn't get called when default (empty) proto messages are published.
Issue Number: https://github.com/continental/ecal/issues/397
The dynamic subscriber callback does get called with a default message when a default (empty) proto message is published.
I issued this PR against the `support/v5.9` branch, and I'm not sure if that's the …
=> Dynamic Subscriber - check for default (empty) proto

.github/workflows/build-macos.yml
=> disable documentation build on macos

.github/workflows/build-windows.yml
Windows GitHub action does not work because of checksum error while installing doxygen via chocolatey
```
Download of doxygen-1.9.3-setup.exe (41.22 MB) completed.
Error - hashes do not match. Actual value was '83F7241DFB44C5BB271072792379BCB539284247'.
ERROR: Checksum for 'C:\Users\runneradmin\AppData\Local\Temp\chocolatey\doxygen.install\1.9.3\doxygen-1.9.3-setup.exe' did not meet '24fd29b4476ad1197a41438efcd67b926db923cd' for checksum type 'sha1'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of doxygen.install was NOT …
```
=> doxygen downgrade to 1.9.2 because of chocolatey install checksum error

ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_descgate.h, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_pubgate.h, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/pubsub/ecal_subgate.h
Multiple subscriber callback are called synchronously. Access is locked by standard (exclusive) mutex. This may lead to performance issues.
Issue Number: #468 
Subscriber callbacks are called asynchronously by using a shared lock. A single subscriber callback can not be called parallel (as before).
The same adaption (shared locking) is done for the description gate and may be done in the future for the client and service gates (after merging #372)
=> Fix: shared_lock for publisher, subscriber and description gate

contrib/ecalhdf5/src/eh5_meas_dir.cpp
Writing the exact same content into an eCAL HDF5 recording leads to none bit exact files because of an extra time stamp added by the HDF5 library.
Issue Number: #471
Files are bit exact.
=> Fix: eCAL HDF5 Files - enable creation of bit-exact files

.github/workflows/build-macos.yml
It uses macos-latest anyways, so it confuses everybody to write a specific version in the title
=> [Actions]: Renamed macOS Build

cmake/helper_functions/ecal_add_functions.cmake
Pre-3.19 cmake did not accept multiple values in a $<CONFIG:xxxx> expression.
=> [Build]: Split CONFIG expressino to support legacy cmake <3.19

ecal/core/include/ecal/msg/protobuf/client.h, ecal/core/include/ecal/msg/protobuf/server.h, samples/cpp/services/ping_client/src/ping_client.cpp, samples/cpp/services/ping_server/src/ping_server.cpp
… name)
Protobuf service instance name can not be set independently from the service name given by the protobuf service description.
Issue Number: #493
Protobuf service instance name can be set independently.
=> Fix: setting service name independently from protobuf service name

app/mon/mon_gui/src/ecalmon.cpp, app/mon/mon_gui/src/ecalmon.h, app/mon/mon_gui/src/main_window.ui, app/play/play_gui/src/ecal_play_gui.cpp, app/play/play_gui/src/ecal_play_gui.h, app/play/play_gui/src/main_window.ui, app/rec/rec_gui/src/ecalrec_gui.cpp, app/rec/rec_gui/src/ecalrec_gui.h, app/rec/rec_gui/src/main_window.ui, app/sys/sys_gui/src/ecalsys_gui.cpp, app/sys/sys_gui/src/ecalsys_gui.h, app/sys/sys_gui/src/main_window.ui, lib/QEcalParser/src/ecal_parser_editor/ecal_parser_editor_widget.cpp
Added a dark mode that one can enable via `View/Theme` in all of our main GUI Applications.
=> Added dark mode to GUI Applications

ecal/core/src/ecal_register.cpp
There are several sleep calls in the registration logic for different entities. Because the registration is now handled by a global registration thread (with global time sync/sleep), this logic is no more needed.
Removed.
=> registration sleep logic cleanup (removal)

app/sys/sys_core/src/config/config_manager.cpp
eCAL Sys now sorts tasks of groups by ID  before saving
=> eCAL Sys now sorts tasks of groups by ID  before saving

ecal/core/src/ecal_descgate.cpp
Set-up of bug:
* Clone project fully and load project in Qt Creator.
* Enable Parameters: `-DQT_CREATOR_SKIP_CONAN_SETUP=ON` and `-DECAL_THIRDPARTY_BUILD_PROTOBUF:BOOL=ON`.
Expected behaviour: Project compiles with no build errors.
Actual behaviour: 
```
ecal/ecal/core/src/ecal_descgate.cpp: In member function ‘void eCAL::CDescGate::ApplyDescription(const string&, const string&, const string&)’:
ecal/ecal/core/src/ecal_descgate.cpp:45:10: error: ‘unique_lock’ is not a member of ‘std’
45 |     std::unique_lock<std::shared_timed_mutex> lock(m_topic_name_desc_sync);
|          ^~~~~~~~~~~
ecal/ecal/core/src/ecal_descgate.cpp:28:1: note: ‘std::unique_lock’ is defined in header …
```
=> Fix: Add mutex header to define missing objects

app/mon/mon_gui/src/widgets/ecalmon_tree_widget/ecalmon_tree_widget.ui, app/mon/mon_gui/src/widgets/log_widget/log_widget.ui
It can now be unreadably small. I did it to support #542, as it always bothers me when I cannot at least temporarily resize docked widgets to a very small state in order to move them around.
=> The monitor can now be very very small.

app/mon/mon_gui/src/widgets/log_widget/log_widget.cpp, app/mon/mon_gui/src/widgets/visualisation_widget/visualisation_widget.cpp, app/play/play_gui/src/widgets/scenario_widget/edit_button_delegate.cpp, app/play/play_gui/src/widgets/scenario_widget/scenario_widget.cpp, app/play/play_gui/src/widgets/scenario_widget/scenario_widget.h, app/rec/rec_gui/src/widgets/recordermanager_widget/host_filter_delegate.cpp, app/rec/rec_gui/src/widgets/recordermanager_widget/recordermanager_widget.cpp, app/rec/rec_gui/src/widgets/recordermanager_widget/recordermanager_widget.h, app/rec/rec_gui/src/widgets/recording_history_widget/recording_history_widget.cpp, app/rec/rec_gui/src/widgets/recording_history_widget/recording_history_widget.h
Fixed the following issues:
- Mon: Play/Pause Button Icons now work properly
- Play: Fixed mouse-hover in labels-widget (i.e. the edit-buttons)
- Rec: Fixed mouse-hover in recorder and history widget (host selection and button hover)
Fixes #542
=> Darkmode: Fixed Windows issues

requirements.txt
This PR fixes a doc-compile-issue. Jinja2 removed some deprectated API with 3.1. Unfortunatelly the sphinx theme is still not properly Sphinx 4 ready, yet, so upgrading isn't the proper way in this case.
=> Pinned Jinja2 to < 3.1

.github/workflows/build-macos.yml, doc/rst/conf.py, requirements.txt
The python apidoc caused sphinx-build to crash on macOS.
Fixes #584
=> Doc: Disabled Python apidoc on macOS

doc/rst/getting_started/cloud.rst, ecal/core/cfg/ecal.ini, ecal/core/src/ecal_def.h
- Set `network_mode = false` by default in `ecal.ini`
- Documented that since eCAL 5.10 you will have to also set the network mode to `true` again for it to work properly
=> Config: Set network_mode=false by default

CMakeLists.txt
Before CMake would fail with not finding the MSVC Qt5 Discovery file when accidentally not having Qt5 installed
=> Made Qt5-msvc-code MSVC-only

ecal/core/include/ecal/ecal_process.h, ecal/core/src/ecal_process.cpp, ecal/core/src/ecal_process.h, ecal/core/src/ecal_reggate.cpp, ecal/core/src/ecalc.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_writer.cpp
In order to exchange data payload via shared memory the host id has to match on the respective nodes. Unfortunately this check will lead to problems once containerized eCAL nodes (e.g. in docker) would like to communicate on shared memory, but does not have the same host id, although they are on the same host.
The host id check will be removed, so the nodes can already communicate via shared memory in case of a matching hostname. Furthermore the eCAL::Process::GetHostID() API function has been tagged as deprecated and can be removed completely in a future version of eCAL. In order to avoid a "deprected warning" by internal functions …
=> Remove hostid check

ecal/core/src/io/udp_receiver_asio.cpp, ecal/core/src/io/udp_receiver_asio.h, ecal/core/src/io/udp_receiver_npcap.cpp, ecal/core/src/io/udp_receiver_npcap.h
Error states are not handled correctly in the udp low level receiver implementation. See this [discussion](https://github.com/continental/ecal/pull/595#discussion_r847012314).
Error states are checked and functions return correctly (thanks @rhd)
=> udp receiver error handling fixed

thirdparty/cmake_functions/qt/qt_msvc_path.cmake
It is questionable whether the Qt Company will ever publish Qt5 binaries for Visual Studio 2022 given the downwards compatibility of VS and the existence of Qt6. But we are prepared now.
=> CMake: The Qt5 autodetection script for Windows now supports VS 2022 builds.

ecal/core/include/ecal/ecal.h
Added missing ecal/ecal_config.h to ecal/ecal.h
You have to include ecal/ecal_config.h manually in your code instead of it being provided by ecal/ecal.h
You can access it view ecal/ecal.h.
=> Added config header to ecal.h file

lang/python/core/ecal/proto/helper.py
Replaced new protobuf `append()` code with the old `add()`code again, that is compatible with old protobuf versions and does the same thing.
Fixes #631
=> Python: fixed compatibility with older protobuf versions

CMakeLists.txt
It should probably go away entirely, but it is at least better than before
=> Moved C++14 Code to the top of the CMakeLists.txt

lang/python/core/src/ecal_wrap.cxx, lang/python/ecalhdf5/src/ecalhdf5_wrap.cxx
Python API is not working for Python 3.10. Using variants like s# and y# seems to need to include PY_SSIZE_T_CLEAN before Python.h
Fixes #635
Described macro added before including Python.h
=> Python: PY_SSIZE_T_CLEAN add before including Python.h

ecal/core/src/service/ecal_tcpclient.cpp
Well, at least the Core and non-gui apps still compile. The Qt Apps for Ubuntu 16 are going to die.
=> Fixed compile issue on Ubuntu 16.04

app/mon/mon_plugins/signals_plotting/src/chart_widget.cpp, app/mon/mon_plugins/signals_plotting/src/plugin_widget.ui
1. The Graph can now make use of the area above it (previously blocked by the buttons)
2. The widget can be resized to a way smaller state (Good for moving it around). It will therefore not block resizing the GUI any more, e.g. if it is hidden behind another widget.
=> Mon: Improved signal plotting resizability

.github/workflows/clang-tidy-review.yml
The output will be similar to this:
https://github.com/FlorianReimold/ecal/pull/11
But it will use the `.clang-tidy` file from the project root
=> Created clang-tidy-review workflow

.clang-tidy
The amount of `clang-diagnostics` is just too much at the moment to be helpful. I disabled those until we fixed them.
=> Set .clang-tidy file to only use clang-analyzer warnings

ecal/core/include/ecal/cimpl/ecal_client_cimpl.h, ecal/core/include/ecal/cimpl/ecal_proto_dyn_json_subscriber_cimpl.h, ecal/core/include/ecal/cimpl/ecal_publisher_cimpl.h, ecal/core/include/ecal/cimpl/ecal_server_cimpl.h, ecal/core/include/ecal/cimpl/ecal_subscriber_cimpl.h, ecal/core/include/ecal/ecal_os.h, ecal/core/src/ecalc.cpp
Revert function renaming introduce by 17f576b
Issue Number: #671 
Bring back C-Api  function that were renamed in 5.10, but mark as deprecated
=> Reintroduce functions that were removed with 5.10 (accidentially)

ecal/core/include/ecal/cimpl/ecal_client_cimpl.h, ecal/core/include/ecal/cimpl/ecal_proto_dyn_json_subscriber_cimpl.h, ecal/core/include/ecal/cimpl/ecal_publisher_cimpl.h, ecal/core/include/ecal/cimpl/ecal_server_cimpl.h, ecal/core/include/ecal/cimpl/ecal_subscriber_cimpl.h, ecal/core/src/ecalc.cpp
Restore 5.9 C AP'I
C API functions were removed with 5.10. This reintroduces those functions to ensure API compatibility again.
=> Reintroduce C  API functions that were removed with 5.10 (accidentially)

.github/workflows/clang-tidy-review.yml
It used pull_request_target before, which would always then check out master. You can check out an untrusted branch, but that is unsafe.
=> GH Action: changed clang-tidy-review to on pull_request

.github/workflows/build-ubuntu-20.yml, .github/workflows/clang-tidy-review.yml
Now we won't always have the "Base commit: 0000000000000000000000000000000000000000" error in the actions any more.
=> Actions: Restricted runs of clang-tidy actions to PR

lib/ecal_utils/src/filesystem.cpp
The build fails with GCC 12 on Arch Linux because strerror() is not found in filesystem.cpp.
The build passes with GCC 12 on Arch Linux because cstring is included explicitly.
This problem is also present in fineftp-server, so this pull request alone won't fix the whole problem. I also created pull request for fineftp-server in their repository and will probably ask for a version bump once that is processed.
=> Explicitly include <cstring> for strerror() to support GCC12.

ecal/core/include/ecal/msg/subscriber.h, testing/ecal/core_test/CMakeLists.txt, testing/ecal/core_test/src/callback_destruction_test.cpp
simplified logic in message subscriber to avoid data races in destruction phase (proven with applied test from Kerstin)
Message subscriber crash while destruction based on data race when message callback is under heavy use.
Issue Number: #701
No more crashing by simplified callback deactivation logic based on one class member only instead checking additional "active" boolean.
=> Bugfix/Datarace in CMsgSubscriber Destruction

ecal/core/src/io/ecal_memfile_sync.cpp
The map is not locked during destroying.
=> Lock m_event_handle_map_sync in Destroy()

ecal/core/src/ecal_log_impl.cpp, ecal/core/src/ecal_log_impl.h
Data race while concurrent logging in shutdown process.
No more data race.
=> minimal fix in global log instance

lang/python/ecalhdf5/ecal/measurement/measurement.py
Allow the possibility to read a measurement in binary mode (and access info like descriptor, schema type, ...)
No access to binary channel data from high level python interface
Two measurement modes for accessing data -> OBJECT (default) and BINARY
The user may decide how they want to access the data.
The current API is extended to accept a new value for measurement access mode.
Per default the access mode is `OBJECT`, which is the same behavior as before the change.
=> Allow binary reading of the measurements in Python API.

.github/workflows/build-windows.yml
With this PR, if a code-signing certificate is available, then the Windows installer will be signed just before the upload step.
The Windows installer is not signed.
Issue Number: [Win Setup: Cryptographically sign binaries #735](https://github.com/eclipse-ecal/ecal/issues/735)
A code-signing certificate is introduced via four GitHub SECRETs:
- cert_body: ${{ secrets.CERT_BODY }}
- cert_pswd: ${{ secrets.CERT_PSWD }}
- cert_algo: ${{ secrets.CERT_ALGO }}
- cert_hash: ${{ secrets.CERT_HASH }}
For further information please visit the [code-sign-action](https://github.com/OrhanKupusoglu/code-sign-action) repository.
This fork added two important features: …
=> Add steps to sign the Windows installer

contrib/ecalhdf5/include/ecal/measurement/imeasurement.h, contrib/ecalhdf5/include/ecal/measurement/omeasurement.h
Fix multiply defined symbols linker error that occurs when IMeasurement or OMeasurement is used in two different translation units as the present method definition in the two header files violates the One Definition Rule.
As method implementations for IMeasurement and OMeasurement are contained in the header file, multiply defined symbols errors will be thrown by the linker if the classes are used in two different translation units.
Using the inline keyword, this error is fixed.
Alternative solutions would be implementing the method in the header definition directly or …
=> FIX: Multiply Defined Symbols

.github/workflows/clang-tidy-review.yml
This comment doesn't provide any helpful information and would cause the review action to fail from forks, even when no issues were found.
=> Actions: Removed clang-tidy-review LGTM comment

ecal/core/include/ecal/ecal_process.h, ecal/core/include/ecal/ecal_timed_cb.h, ecal/core/src/ecal_process.cpp, ecal/core/src/ecal_time.cpp, ecal/core/src/ecal_timegate.cpp, ecal/core/src/io/snd_raw_buffer.cpp, ecal/core/src/service/ecal_tcpclient.cpp
For windows, std::this_thread::sleep_for does not use a steady clock and is affected by system clock changes.
- Added a new templated function which can be used similarly to the classic sleep_for, which takes a std::chrono::duration argument
- Using Sleep method from synchapi.h header, thread sleep works as supposed and is not affected by system clock changes
=> Steady clock thread sleep implementation for windows

ecal/pb/CMakeLists.txt
Compatibility target eCAL::pb may depend on other targets based on CMake configuration switches.
Issue Number: #611
=> eCAL::pb link targets depending on global CMake configuration

ecal/core/CMakeLists.txt, ecal/core/src/ecal_global_accessors.cpp, ecal/core/src/ecal_global_accessors.h, ecal/core/src/ecal_globals.cpp, ecal/core/src/ecal_globals.h, ecal/core/src/ecal_process.cpp, ecal/core/src/ecal_registration_provider.cpp, ecal/core/src/ecal_registration_provider.h, ecal/core/src/ecal_registration_receiver.cpp, ecal/core/src/ecal_registration_receiver.h, ecal/core/src/ecal_util.cpp, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_pubgate.h, ecal/core/src/pubsub/ecal_publisher.cpp, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_server_impl.cpp
Some eCAL core class names are misleading, methods are unused. Especially the "gate" classes needs to be named clearly and documented.
More consistency in class naming and internal documentation.
=> renaming global eCAL instances of the registration layer

.clang-tidy
We have some magic numbers in the code and those are usually fine. The warning is not very helpful.
=> clang-tidy: disabled cppcoreguidelines-avoid-magic-numbers

ecal/core/src/io/linux/ecal_memfile_os.cpp, lib/ecal_utils/src/filesystem.cpp
This fix is Linux-only. It saves 1 open file descriptor per published topic.
This relates to #723 but is not enough to solve #592
=> Properly closing file descriptors on linux after mmap

ecal/core/src/io/linux/ecal_memfile_os.cpp
This reverts commit 858dfc008d108d3e331ff4afd24558ad9063e56a.
=> Revert "Properly closing file descriptors on linux after mmap (#765)"

.clang-tidy
Reinterpret casts may be ugly, but they are the proper tool for what they do.
=> clang-tidy: turned off reinterpret_cast warnings

app/play/play_gui/src/main_window.ui, contrib/ecalhdf5/src/eh5_meas_dir.cpp, contrib/ecalhdf5/src/eh5_meas_dir.h, contrib/ecalhdf5/src/eh5_meas_file_writer_v5.cpp, contrib/ecalhdf5/src/eh5_meas_file_writer_v5.h
eCAL HDF5 fails to split the HDF5 files.
Fixes #802
eCAL HDF5 is again splitting the HDF5 files.
=> eCAL HDF5: fixed Split-Size option

thirdparty/build-curl.cmake
Updated most submodules to a "resonable" new Version.
- This mostly is the latest released version available.
- Protobuf is not updated and remains on 3.11
- CURL was updated to the version that is default on Ubuntu 22.04 (libcurl curl-7_69_1)
=> Updated Submodules

app/play/play_gui/CMakeLists.txt, app/rec/rec_gui/CMakeLists.txt, app/sys/sys_gui/CMakeLists.txt
Looks like Ubuntu 22.04 has a bug (?) that prevents loading icons from the hicolor theme. The Humanity theme works though. The default Yaru theme inherits from both, so I moved the icons to the Humanity theme and now they show up fine.
Fixes #825
=> Switched mime icons from hicolor to Humanity theme

CMakeLists.txt, samples/CMakeLists.txt
This fixes a bug that would prevent FTXUI / Mon TUI to compile, as those targets need C++ 17.
Fixes #830
=> CMakeLists: Removed code that would fix the CXX Standard to 14

app/play/play_cli/src/ecal_play_cli.cpp, app/play/play_gui/src/main.cpp
eCAL Play GUI and eCAL Play CLI now both raise the open-fd-soft-limit up to the hard-limit.
Fixes #592
=> eCAL Play @ Linux: Increase FD Limit

testing/ecal/clientserver_test/CMakeLists.txt, testing/ecal/core_test/CMakeLists.txt, testing/ecal/pubsub_inproc_test/CMakeLists.txt, testing/ecal/pubsub_test/CMakeLists.txt
Currently all tests are build twice.
=> Remove double tests (which before went through old C - C++ Wrapper).

CMakeLists.txt, ecal/core/CMakeLists.txt, ecal/core/cfg/ecal.ini, ecal/core/include/ecal/ecal_config.h, ecal/core/src/ecal_config.cpp, ecal/core/src/ecal_def.h, ecal/core/src/ecal_def_ini.h, ecal/core/src/ecal_process.cpp, ecal/core/src/io/linux/ecal_socket_option_linux.h, ecal/core/src/io/udp_receiver_asio.cpp
Added `ecal.ini` option to join the Multicast groups on all Interfaces. The setting is Linux only. By default it is turned off.
New version of #776
Fixes #695
=> Core@Linux: Add option to join MC group on all interfaces

app/mon/mon_gui/src/widgets/system_information_widget/system_information_widget.cpp
Now also gnome-text-editor can open the file as root for editing.
Fixes #861
=> eCAL Mon GUI: Support gnome-text-editor when clicking ecal.ini

app/app_pb/CMakeLists.txt, contrib/ecaltime/ecaltime_pb/CMakeLists.txt, ecal/core_pb/CMakeLists.txt
On Linux, the targets are hardcoded compiled as shared objects. On Windows they are hardcoded as static libs. Even though this may not be optimal, it fixes #687.
=> Made eCAL::app_pb, ::core_pb and ::time_pb shared libraries on Linux

.github/workflows/build-windows.yml
Currently, the Windows GH Action only builds the Python 3.11 wheel.
Fixes #885
Build 5 different wheels for Python 3.11/3.10/3.9/3.8/3.7.
=> Build Python wheels for older versions in Windows

thirdparty/build-curl.cmake, thirdparty/build-ftxui.cmake
Installing the static libs of FTXUI and curl should not be a responsibility of eCAL.
=> CMake: Excluded FTXUI and libcurl libs from installation

ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_server_impl.cpp, ecal/core/src/service/ecal_service_server_impl.h, testing/ecal/clientserver_test/CMakeLists.txt, testing/ecal/clientserver_test/src/clientserver_test.cpp
This PR fixes a bug that caused long running RPC calls to block a mutex for the entire time of the RPC call. As this mutex is also needed by the monitoring loop, long running RPC calls caused the eCAL nodes to disappear from the system.
The commit is a Qick-and-dirty hotfix. The code now contains many TODOs, as during review a lot of other questions arose. Please also check #905 for more details regarding those questions. It should however solve the actual problem.
Fixes #903
=> Core Services: Fixed bug that caused the monitoring loop to block in case of long running RPC calls

thirdparty/build-udpcap.cmake
Replaced the CMAKE_BUILD_SHARED_LIBS (that does nothing) with the correct BUILD_SHARED_LIBS variable.
Fixes #912
=> Udp build script: Fixed variable

ecal/core/src/io/ecal_memfile_sync.cpp
Exiting a subscription node will affect the publishing node when shm shared memory acknowledge feature is activated.
Fixes: #925
Acknowledge feature is working properly again by invalidating the acknowledge event after the first timeout (not a local copy of that event).
=> Fix crash based on wrong acknowledgment event handling.

app/rec/rec_addon_dummy/CMakeLists.txt
Fixes #933
Cannot build eCAL on FreeBSD
- `ecal_rec_dummy` which directly uses threads now has a CMake find package call and properly links threads.
=> Fix: `rec_addon_dummy` finds and links threads.

ecal/core/src/service/ecal_service_server_impl.cpp
Fixes #937, a bug that was introduced with commit 419d7f33edca6cf4b02c50b8e879981f4043f873
=> Core Services Bugfix: Service response header now contains the methodname again

ecal/core/src/service/ecal_service_server_impl.cpp
Fixes #937, a bug that was introduced with commit 419d7f33edca6cf4b02c50b8e879981f4043f873
=> [5.10] Core Services Bugfix: Service response header now contains the method name again

ecal/core/src/service/ecal_service_server_impl.cpp
Fixes #937, a bug that was introduced with commit 419d7f33edca6cf4b02c50b8e879981f4043f873
=> [5.11] Core Services Bugfix: Service response header now contains the method name again

contrib/mma/src/linux/mma_linux.cpp
It was in KB before and now is in Bytes, just as the Documentation says and how it already was on Windows.
Fixes #947
=> MMA: Corrected reading of ram usage for processes

app/rec/rec_gui/src/qecalrec.cpp, app/rec/rec_server_core/src/rec_server_impl.cpp
=> eCAL Rec: ClearConfig (GUI: File/New Config) now properly clears the one-file-per-channel-option

CMakeLists.txt, doc/rst/configuration/options.rst, ecal/core/CMakeLists.txt, ecal/core/cfg/ecal.ini, ecal/core/include/ecal/ecal_config.h, ecal/core/src/ecal_config.cpp, ecal/core/src/ecal_def.h, ecal/core/src/ecal_def_ini.h, ecal/core/src/ecal_log_impl.cpp, ecal/core/src/ecal_process.cpp, ecal/core/src/ecal_registration_provider.cpp, ecal/core/src/ecal_registration_receiver.cpp, ecal/core/src/io/udp_configurations.cpp, ecal/core/src/io/udp_configurations.h, ecal/core/src/mon/ecal_monitoring_threads.cpp, ecal/core/src/readwrite/ecal_reader_udp_mc.cpp, ecal/core/src/readwrite/ecal_writer_udp_mc.cpp, ecal/core/src/topic2mcast.h, testing/ecal/topic2mcast_test/CMakeLists.txt, testing/ecal/topic2mcast_test/src/topic2mcast_test.cpp
Unintuitive masking for multicast addresses
Issue Number: #873
This PR introduces a new multicast configuration version mode, e.g. V2. The previous mode is called V1.
V1 stays the standard mode for now, to be compatible with older eCAL Versions. 
V2 is introduced, and allows better configuration.
Please review:
The behavior to treat collisions:
Per default, `multicast_group` is the MC address to send registration information on.
If a topic is to be sent on the same MC address as registration information, it is send on +1. If this causes "overflow" (e.g. multicast group `139.0.0.255` and mask of `255.255.255.0`, the topic will be sent on `139.0.0.0`.
It is to be discussed if this is a favorable behavior. …
=> Core: Added proper topic_name -> UDP MC group computation.

app/app_pb/src/ecal/app/pb/rec/server_config.proto, app/rec/rec_server_core/src/proto_helpers.cpp
For this, the server_config.proto description had to be extended with a field for the upload_config.
Fixes #953
=> eCAL Rec: When calling GetConfig via RPC, the Upload settings are now properly included

app/rec/rec_server_cli/src/commands/get_config.cpp
=> eCAL Rec CLI: getconfig command now also displays the one-file-per-topic setting

.github/workflows/build-ubuntu-18.yml, .github/workflows/build-ubuntu-20.yml, .github/workflows/build-ubuntu-22.yml, CMakeLists.txt, app/app_pb/src/ecal/app/pb/rec/server_service.proto, app/rec/rec_client_core/include/rec_client_core/rec_error.h, app/rec/rec_client_core/src/job_config.cpp, app/rec/rec_gui/src/qecalrec.cpp, app/rec/rec_gui/src/qecalrec.h, app/rec/rec_gui/src/service/rec_server_service.cpp, app/rec/rec_gui/src/service/rec_server_service.h, app/rec/rec_server_cli/src/commands/set_config.cpp, app/rec/rec_server_cli/src/commands/set_config.h, app/rec/rec_server_cli/src/ecal_rec_server_cli.cpp, app/rec/rec_server_cli/src/rec_server_service.cpp, app/rec/rec_server_cli/src/rec_server_service.h, app/rec/rec_server_core/include/rec_server_core/rec_server.h, app/rec/rec_server_core/include/rec_server_core/rec_server_config.h, app/rec/rec_server_core/src/config/config.cpp, app/rec/rec_server_core/src/rec_server.cpp, app/rec/rec_server_core/src/rec_server_impl.cpp, app/rec/rec_server_core/src/rec_server_impl.h, app/rec/rec_tests/rec_rpc_tests/CMakeLists.txt, app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.cpp, app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.h, app/rec/rec_tests/rec_rpc_tests/src/rec_cli_test.cpp
- Added SetConfig RPC Call to Rec GUI and Rec CLI
- Enabled --set-config from command line and setconfig from interactive mode of Rec CLI in Remote control mode
- Added Tests for Rec CLI Remote control mode (command-line version) testing the control of both eCAL Rec CLI and GUI 
Fixes #848
=> eCAL Rec: Added RPC Service "SetConfig"

doc/extensions/generate_download_tables.py, doc/extensions/resource/download_archive.rst.em, doc/extensions/resource/download_archive_page.rst.em
The page now sorts the releases in tables and displays their release date and the support status.
=> Documentation: Improved Download Archive / All Releases section

ecal/core/include/ecal/cimpl/ecal_callback_cimpl.h, ecal/core/include/ecal/ecal_callback.h, ecal/core/src/ecal_clang.cpp, ecal/core/src/ecalc.cpp, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer.h, samples/cpp/person/person_rec_events/src/person_rec_events.cpp, samples/cpp/person/person_snd_events/src/person_snd_events.cpp
Connection refresh event to inform publisher / subscriber permanently about established connections and their attributes is not existing.
Fixes: #919
New events pub_event_update_connection and sub_event_update_connection introduced.
Event callback information structs SPubEventCallbackData and SSubEventCallbackData extended to provide additional topic. Attributes samples person_snd_events and person_rec_events adapted to show usage.
ABI compatibility break
=> new events pub/sub_event_update_connection

app/mon/mon_gui/CMakeLists.txt
eCAL or rather the monitor gui does not build when ECAL_NPCAP_SUPPORT flag is enabled due to a wrong target name of udpcap.
eCAL Monitor gui builds properly against the correct udpcap target.
=> Fixed wrong udpcap target in monitor gui

ecal/core/src/ecal_process.cpp
On MacOs the process name does not have the correct length.
@JerryHyun
=> Bugfix: Process name on MacOs should have the length of the read path.

lang/csharp/Continental/eCAL/Core/ecal_clr.cpp, lang/csharp/Continental/eCAL/Core/ecal_clr.h
C# strings are not pure byte containers as they are in C++ and thus not very suitable for the API in many places.
This commit provides some overloads / additional functions to use `byte[]` instead of `string`.
=> C#: Overload current API functions to take/return byte[] instead of string

lang/csharp/Continental/eCAL/Core/ecal_clr.cpp, lang/csharp/Continental/eCAL/Core/ecal_clr.h, lang/csharp/Continental/eCAL/Protobuf/CMakeLists.txt, lang/csharp/Continental/eCAL/Protobuf/ProtoHelper.cs, lang/csharp/Continental/eCAL/Protobuf/ProtoPublisher.cs
Properly create Protobuf descriptors when using newer Protobuf Versions which have that feature available.
=> C#: Properly create protobuf descriptors

ecal/core/include/ecal/msg/publisher.h
=> CMsgPublisher::SendSynchronized method added

ecal/core/cfg/ecal.ini, ecal/core/include/ecal/ecal_config.h, ecal/core/src/ecal_config.cpp, ecal/core/src/ecal_def.h, ecal/core/src/ecal_def_ini.h, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, samples/cpp/performance/performance_rec_cb/src/performance_rec_cb.cpp, samples/cpp/performance/performance_snd/src/performance_snd.cpp
Messages may arrive out of order under certain conditions. This is not handled currently.
Issue Number: #986
Based on a new, experimental configuration flag `drop_out_of_order_messages` the eCAL core can handle out of order messages in 2 different ways:
1. ignore order and forward the message to the matching subscriber (issue will logged as warning)
2. ignore the message, interrupt the forwarding
The default behavior is 1.
=> additional configurable logic to handle out of order messages

ecal/core/src/ecal_def.h, ecal/core/src/io/ecal_memfile_pool.cpp, ecal/core/src/io/ecal_memfile_pool.h, samples/cpp/datarate/datarate_snd/src/datarate_snd.cpp
* For every observed memory file a separate thread is checking for updates (`CMemFileObserver::Observer`). When a memory file is outdated the observing thread ends without deallocating the `CMemFileObserver` internal receive buffer buffer variable `m_ecal_buffer` (renamed to `receive_buffer`).
* All `CMemFileObserver` are organized in a central map inside `CMemFileThreadPool`. Outdated/stopped observer entities are not removed from the global `CMemFileThreadPool::m_observer_pool` map.
Issue Number: #1021
* The memory file content receive buffer is now defined inside the scope of the `CMemFileObserver::Observe` function and will be freed when observation …
=> memfile observer pool and receive buffer cleanup

ecal/core/src/readwrite/ecal_writer_tcp.cpp, ecal/core_pb/src/ecal/core/pb/ecal.proto
This solves an issue with Capnproto. Capnproto requires the serialized data to be 8-bytes-aligned in memory. By already sending the payload 8-byte-aligned, this solves that issue.
Fixes #1017
=> Core (TCP Layer): Added bytes-alignment field in TCP Header to 8-byte-align the TCP user payload.

ecal/core/include/ecal/ecal_publisher.h, ecal/core/include/ecal/msg/publisher.h, ecal/core/src/pubsub/ecal_publisher.cpp
Implement only one send function, to make the rest of the send logic trivial.
=> We implement one and only one SEND method for the publishers.

CMakeLists.txt, app/meas_cutter/src/measurement_exporter.cpp, app/meas_cutter/src/measurement_exporter.h, app/meas_cutter/src/measurement_importer.cpp, app/meas_cutter/src/measurement_importer.h, app/meas_cutter/src/utils.h, app/play/play_core/src/ecal_play.cpp, app/play/play_core/src/measurement_container.cpp, app/play/play_core/src/measurement_container.h, app/play/play_core/src/play_thread.cpp, app/play/play_core/src/play_thread.h, app/rec/rec_client_core/src/job/hdf5_writer_thread.cpp, app/rec/rec_client_core/src/job/hdf5_writer_thread.h, contrib/ecalhdf5/CMakeLists.txt, contrib/ecalhdf5/include/ecal/measurement/imeasurement.h, contrib/ecalhdf5/include/ecal/measurement/omeasurement.h, contrib/ecalhdf5/include/ecalhdf5/eh5_meas.h, contrib/ecalhdf5/include/ecalhdf5/eh5_types.h, contrib/measurement/base/CMakeLists.txt, contrib/measurement/base/include/ecal/measurement/base/measurement.h, contrib/measurement/base/include/ecal/measurement/base/types.h, lang/python/ecalhdf5/src/ecalhdf5_wrap.cxx
This introduces a common base class `eCAL::measurement::base::Measurement` that allows to write measurements in a polymorphic way, thus allowing to exchange the actual writer implementation.
All occurences (except in test cases) now use the base class for pointers, and instantiating then `eh5::eCALMeas`.
Behavior should be 100% identical.
Part of #1076 .
The implementation is **fully** compatible and does not break API for anyone wishing to use `eh5::eCALMeas` directly. 
Please review with regard to:
- Class naming
- CMake target naming
- Folder / include path structure
=> Measurement: Prepare mcap support by introducing measurement base class.

ecal/core/CMakeLists.txt
Files are now not artifically scattered into different folders anymore (e.g. in Visual Studio). Rather, the filesystem is used, where (private) header files are usually located next to the corresponding cpp file. So now, the `src` dir contains everything private and the `include` dir contains everything public, just as in the folder structure.
=> Core CMake: Restructured source_groups of files for IDEs

contrib/ecaltime/linuxptp/src/ecal_time_linuxptp.h, ecal/core/src/topic2mcast.h
eCAL does not build with GCC 13. See GCC documentation [here](https://gcc.gnu.org/gcc-13/porting_to.html).
eCAL builds with GCC 13. Please note that termcolor also needs an adaption, but I filed a pull requst [there directly](https://github.com/ikalnytskyi/termcolor/pull/72).
Tested on Arch Linux with GCC 13.1. This change is minimal - it is basically adding #include for cstdint to two files (three if you count termcolor).
=> GCC13 compatibility: Explicitly include cstdint

ecal/core/src/custom_tclap/advanced_tclap_output.cpp, ecal/core/src/ecal_clang.cpp, ecal/core/src/ecal_config.cpp, ecal/core/src/ecal_config_reader.cpp, ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_globals.cpp, ecal/core/src/ecal_log_impl.cpp, ecal/core/src/ecal_process.cpp, ecal/core/src/ecal_time.cpp, ecal/core/src/ecal_timer.cpp, ecal/core/src/ecal_util.cpp, ecal/core/src/ecalc.cpp, ecal/core/src/io/ecal_memfile_db.cpp, ecal/core/src/io/ecal_memfile_pool.cpp, ecal/core/src/io/rcv_sample.cpp, ecal/core/src/io/snd_raw_buffer.cpp, ecal/core/src/io/snd_sample.cpp, ecal/core/src/io/udp_configurations.cpp, ecal/core/src/io/udp_init.cpp, ecal/core/src/io/udp_receiver_asio.cpp, ecal/core/src/io/udp_sender.cpp, ecal/core/src/io/win32/ecal_named_mutex_impl.cpp, ecal/core/src/mon/ecal_monitoring_threads.cpp, ecal/core/src/pubsub/ecal_proto_dyn_json_sub.cpp, ecal/core/src/service/ecal_tcpclient.cpp, ecal/core/src/sys_usage.cpp
Clang-Tidy
Clang-tidy warnings.
Fixed only clang-tidy warning: local variable could be declared as const for all core files
=> clang-tidy/can-be-declared-const-2

app/meas_cutter/src/measurement_converter.cpp, app/meas_cutter/src/measurement_exporter.cpp, app/meas_cutter/src/measurement_exporter.h
Current output folder structure of meas cutter is
Recording_Folder
+ MEASUREMENT_CONVERTER
+ doc
+ ...
+ *.ecalmeas
+ *.hdf5
+ config.yaml
which is not similar to eCAL's recording folder structure
Recording_Folder
+ doc
+ PC1
+ *.hdf5
+ PC2
+ *.hdf5
+ *.ecalmeas
Issue Number: #1109 
The new output folder structure of meas cutter is aligned to eCAL rec
Recording_Folder
+ doc
+ MEASUREMENT_CONVERTER
+ *.hdf5
+ *.ecalmeas
=> Fixed output folder structure of meas cutter

.github/workflows/build-macos.yml
The current MacOs Build is failing:
```
==> Fetching dependencies for protobuf: abseil
==> Fetching abseil
==> Downloading https://ghcr.io/v2/homebrew/core/abseil/manifests/20230125.3-1
==> Downloading https://ghcr.io/v2/homebrew/core/abseil/blobs/sha256:42d1faa5ff28d113705a651d57edcdc29580c8b7c941a9db5f3f06c97306966f
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:42d1faa5ff28d113705a651d57edcdc29580c8b7c941a9db5f3f06c97306966f?se=2023-06-23T13%3A55%3A00Z&sig=s%2Floazqe4YswGGN0T%2Bw9pbzKgRIMudtAp4N55VcIyMA%3D&sp=r&spr=https&sr=b&sv=2019-12-12
==> Fetching protobuf
==> Downloading https://ghcr.io/v2/homebrew/core/protobuf/manifests/23.3
==> Downloading https://ghcr.io/v2/homebrew/core/protobuf/blobs/sha256:d529c07b5c32da9f6ce554b254deb080efb3d52afde57ec …
```
=> Install older macos protobuf (3.21)

ecal/core/include/ecal/ecal_publisher.h, ecal/core/include/ecal/ecal_subscriber.h, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_pubgate.h, ecal/core/src/pubsub/ecal_publisher.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/pubsub/ecal_subgate.h, ecal/core/src/pubsub/ecal_subscriber.cpp, testing/ecal/pubsub_test/src/pubsub_test.cpp
- Transform Subscriber / Subgate datareader to shared_ptr instead of raw pointer.
- Transform CPublisher / CPubGate CDataWriter to shared_ptr instead of raw pointer.
- Successfully allow to call Destroy() function in callbacks. (Lock map only to retreive datareaders).
fixes #1073
fixes #707
=> [bugfix] eCAL::core: Avoid possible deadlocks inside callbacks

ecal/core/src/mon/ecal_monitoring_impl.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/readwrite/ecal_reader.cpp
This commit compiles with gcc 5.4 dating back to 2016, which should be C++14 capable. but not more.
Fixes #1138
=> Core: Fixed compatibility with old gcc versions

app/mon/mon_gui/src/widgets/models/log_model.cpp, app/mon/mon_gui/src/widgets/models/log_model.h
Now, the default text color is used (black in light mode and white in dark mode). Before, it was always black, which rendered the string unreadable in dark-mode.
Fixes #1135
=> Mon: Fixed text color of "Debug x" string in Log panel

ecal/core/include/ecal/msg/protobuf/dynamic_subscriber.h, testing/ecal/pubsub_proto_test/CMakeLists.txt, testing/ecal/pubsub_proto_test/src/proto_dyn_subscriber_test.cpp
(API to be changed for 5.13, to make it more intuitive)
Undeprecate the API. To be backported for 5.10 / 5.11
=> Core: Restore Receive functionality for Dynamic Subscribers

ecal/core/include/ecal/ecal_payload_writer.h, samples/CMakeLists.txt, samples/cpp/pubsub/binary/binary_rec/CMakeLists.txt, samples/cpp/pubsub/binary/binary_rec/src/binary_rec.cpp, samples/cpp/pubsub/binary/binary_zero_copy_rec/CMakeLists.txt, samples/cpp/pubsub/binary/binary_zero_copy_rec/src/binary_zero_copy_rec.cpp, samples/cpp/pubsub/binary/binary_zero_copy_snd/CMakeLists.txt, samples/cpp/pubsub/binary/binary_zero_copy_snd/src/binary_zero_copy_snd.cpp
We missed samples to demonstrate low level zero copy API and the CPayloadWriter class was not documented (Doxygen).
Issue Number: #1145
Two new binary send / rec zero copy samples added, CPayloadWriter class documented.
**Cherry-Pick to**
- 5.12
=> Core / ZeroCopy: Added Doxygen API documentation and 2 new c++ samples demonstrating usage of low level zero copy API

ecal/core/src/io/udp_sender.cpp, ecal/core/src/io/udp_sender.h
Untested, internal [`CUDPSender::SendAsync`](https://github.com/eclipse-ecal/ecal/blob/50699d8326f3ad48e06b847b20b6002284bda92a/ecal/core/src/io/udp_sender.h#L50) API.
API removed.
**Cherry-pick to:**
- _none_
=> core: remove unused and untested udp sendasync method

testing/ecal/pubsub_test/CMakeLists.txt
Minimal fix in testing/ecal/pubsub_test/CMakeLists.txt (forgotten source file extension :-/)
**Cherry-pick to:**
- 5.12
=> source file extension in testing/ecal/pubsub_test/CMakeLists.txt missed

ecal/core/include/ecal/ecal_payload_writer.h, ecal/core/include/ecal/ecal_publisher.h, ecal/core/include/ecal/msg/capnproto/publisher.h, ecal/core/include/ecal/msg/protobuf/publisher.h, ecal/core/src/ecal_buffer_payload_writer.h, ecal/core/src/io/ecal_memfile.cpp, ecal/core/src/readwrite/ecal_writer.cpp, samples/cpp/benchmarks/latency_snd/src/binary_payload_writer.h, samples/cpp/benchmarks/performance_snd/src/binary_payload_writer.h, samples/cpp/benchmarks/pubsub_throughput/src/binary_payload_writer.h, samples/cpp/pubsub/binary/binary_zero_copy_snd/src/binary_zero_copy_snd.cpp, testing/ecal/pubsub_test/src/pubsub_multibuffer.cpp
core: CPayloadWriter methods renamed Write -> WriteFull, Update -> WriteModified
doc: documentation of CPublisher::ShmEnableZeroCopy updated
**Cherry-pick to:**
- 5.12
**New API:**
```cpp
/**
* @brief Base payload writer class to allow zero copy memory operations.
*
* This class serves as the base class for payload writers, allowing zero-copy memory
* operations. The `WriteFull` and `WriteModified` calls may operate on the target
* memory file directly in zero-copy mode.
* 
* A partial writing / modification of the memory file is only possible when zero-copy mode 
* is activated. If zero-copy is not enabled, the `WriteModified` method is ignored and the 
* `WriteFull` method is always …
```
=> core: CPayloadWriter methods Write & Update renamed

.github/pull_request_template.md
**Description**
The old issue template was very long. It was hard to fill out correctly and thus often contained wrong information. Thousands of checkboxes distracted from what is actually important.
The most important thing for a PR should always be: What does it change.
I also added a section for related issues and cherry-pick. The latter is meant for giving myself a better overview over what still needs to be cherry-picked to which branch and what is master-only. Usually the developer knows that when submitting the PR.
**Related issues**
- _none_
**Cherry-pick to**:
- _none_
=> GitHub: Radically shortened the PR template

app/mon/mon_tui/CMakeLists.txt, app/mon/mon_tui/src/tui/style_sheet.hpp, thirdparty/build-ftxui.cmake
Allows to build `mon_tui` with latest ftxui.
Fixes https://github.com/eclipse-ecal/ecal/issues/1186
- 5.11 (old stable) - ??? (we have to decide)
- 5.12 (current stable) - ??? (we have to decide)
=> #1186 Make compatible with ftxui 5.0.0

ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer.h
Introduces two new structs (SLocalSubscriptionInfo and SExternSubscriptionInfo) and uses them for applying / unapplying registrations. They are also stored in the ExpiredMap when topic are no longer visible on monitoring layer.
Fixes #1196
- 5.12
=> Fixes bug regarding unregistration introduced with #1086.

doc/requirements.txt
The latest version of sphinxcontrib-youtube is not compatible with our Sphinx version (4.5) anymore. I downgraded sphinxcontrib-youtube to 1.2 or lower.
- 5.11 (probably needs to be re-implemented)
=> Sphinx Doc: downgrade sphinxcontrib-youtube

app/rec/rec_gui/src/widgets/recordermanager_widget/recorder_model.cpp
=> Rec GUI: Fixed a tooltip typo

ecal/core/src/io/ecal_memfile_pool.cpp, testing/ecal/pubsub_test/src/pubsub_test.cpp
2333d20 introduced a bug when sending zero length messages over SHM - the callback would contain stale non-zero length messages from the previous call.
This commit fixes the introduced bug, and adds a testcase for this scenario.
Fixes #1200  
- 5.11 (old stable) -> probably cannot be cherry picked, but requires a different commit
=> eCAL Core: Callback after zero length send contains stale message

.github/workflows/build-windows.yml
The default GH Action runners dropped Python 3.6, so we are dropping it as well.
=> GH Actions: Remove Python 3.6 wheel build on Windows

ecal/core/src/io/ecal_memfile_pool.cpp, ecal/core/src/io/ecal_memfile_pool.h
Prior to this commit, SHM data was dropped, if the subscriber wasn't able to access it in 5ms. Now, the subscriber re-tries, until it got access to it, or new data is available.
- Found by debugging #1194, but this fix did not fix the issue.
=> Core: Fixed a bug that may have caused drops in the SHM Layer

ecal/core/src/service/ecal_service_client_impl.cpp
Unintended semicolon in if statement removed.
- _none_
=> unintended semicolon in if statement

ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer_base.h, ecal/core/src/readwrite/ecal_writer_shm.cpp, ecal/core/src/readwrite/ecal_writer_shm.h, samples/cpp/pubsub/protobuf/person_rec_events/src/person_rec_events.cpp, samples/cpp/pubsub/protobuf/person_snd_events/src/person_snd_events.cpp
- `RemLocConnection` call for SHM removed from ecal_writer.cpp
- this call is unnecessary (events are closed on `CSyncMemFile Destruction/Disconnect`)
- this call disconnects to a process even there are still additional subscriber for the same topics in this process
- calls `AddLocConnection`/`AddExtConnection`, `RemLocConnection`/`RemExtConnection `for all layers (including tcp) even function are unimplemented
- changed signature for all `AddXXXConnection`/`RemXXXConnection `functions to provide now unambiguous information host name, process id, topic id and not only process id
- _none_
=> cleanup add/rem datawriter connection logic

ecal/service/test/src/ecal_tcp_service_test.cpp, testing/contrib/ecalproto/dynproto_test/src/dynproto_test.cpp, testing/contrib/ecalproto/ecal_proto_test/src/test_filters.cpp, testing/ecal/clientserver_test/src/clientserver_getservices.cpp, testing/ecal/clientserver_test/src/clientserver_test.cpp, testing/ecal/io_memfile_test/src/memfile_naming_test.cpp, testing/ecal/io_memfile_test/src/memfile_test.cpp, testing/ecal/pubsub_inproc_test/src/pubsub_inproc_test.cpp, testing/ecal/pubsub_proto_test/src/proto_dyn_subscriber_test.cpp, testing/ecal/pubsub_test/src/pubsub_acknowledge.cpp, testing/ecal/pubsub_test/src/pubsub_gettopics.cpp, testing/ecal/pubsub_test/src/pubsub_multibuffer.cpp, testing/ecal/pubsub_test/src/pubsub_receive_test.cpp, testing/ecal/pubsub_test/src/pubsub_test.cpp, testing/ecal/util_test/src/util_test.cpp
Inconsistent unit test naming cleaned up.
- _none_
=> tried to cleanup the naming of the ecal unit tests a bit

app/play/play_cli/src/ecal_play_cli.cpp, app/rec/rec_server_cli/src/commands/status.cpp, app/rec/rec_server_cli/src/commands/table_printer.cpp, app/sys/sys_cli/src/commands/list.cpp
Currently (2023-10-26) termcolor does not include the cstdint header file, but it is needed for Ubuntu 23.10 / gcc 13.2: https://github.com/ikalnytskyi/termcolor/pull/72
- None
=> GCC 13: Added workaround for termcolor bug (missing include)

contrib/mma/src/linux/mma_linux.cpp
The branch reading line 12 of /proc/cpuinfo is valid only for `__x86_64__`.
So, bugfix is to restrict this branch for `__x86_64__` only.
Or, simpler and more generic, use `get_ncores()`.
- Fixes #1233
=> Fix segfault in GetCpuCores

doc/rst/license/thirdparty_licenses.rst
We apparently forgot to replace those links when moving to Eclipse 
- none
- 5.11
- 5.12
=> Doc: replaced continental links with eclipse-ecal

app/meas_cutter/CMakeLists.txt
Ensure compatibility with yaml-cpp version 0.8.0.
=> CMake: Compatibility with new yaml-cpp release 0.8.0.

contrib/measurement/base/include/ecal/measurement/imeasurement.h
In some parts of the imeasurement class, timestamps of sender and receiver side have been accidentelly swapped. 
=> Fixed wrong order of sender and receiver timestamp in make_frame() method

ecal/core/src/ecal_log_impl.cpp, ecal/core/src/ecal_process.cpp, ecal/core/src/ecal_registration_provider.cpp, ecal/core/src/ecal_registration_receiver.cpp, ecal/core/src/io/ecal_receiver.h, ecal/core/src/io/snd_sample.cpp, ecal/core/src/io/udp_configurations.cpp, ecal/core/src/io/udp_configurations.h, ecal/core/src/io/udp_receiver_asio.cpp, ecal/core/src/io/udp_receiver_asio.h, ecal/core/src/io/udp_receiver_npcap.cpp, ecal/core/src/io/udp_receiver_npcap.h, ecal/core/src/io/udp_sender.cpp, ecal/core/src/io/udp_sender.h, ecal/core/src/mon/ecal_monitoring_threads.cpp, ecal/core/src/readwrite/ecal_reader_udp_mc.cpp, ecal/core/src/readwrite/ecal_writer_udp_mc.cpp, ecal/core/src/readwrite/ecal_writer_udp_mc.h
In preparation for a new udp communication layer implementation there are some cleanups made in udp_confiuration and the sender and receiver udp attribute structures. Test under Windows and Ubuntu with local and network mode and for Windows with and without npcap.
Is not fixing any issue, should behave as before.
- _none_
=> cleanup udp configuration and sender/receiver attributes

ecal/core/src/io/udp/snd_raw_buffer.cpp
Random UDP package id now uses timestamp to start with a unique number for every process.
=> initialize random udp package id using nanosecond timestamp

lang/python/core/ecal/core/core.py, lang/python/core/ecal/core/service.py, lang/python/core/src/ecal_wrap.cxx
Fixed the python bindings for removing a response callback from a service client:
`ecal.core.service.py` :
- Client had `rem_response_callback` taking a method name parameter (which was unused) and calling non-existant `ecal.core.core.client_rem_response_callback`.
`ecal.core.core.py`:
- `client_rem_response_callback` doesn't exist because it was typoed in as `client_rem_method_callback`.
`ecal_wrap.cxx`:
- Implementation of `client_rem_response_callback` does exist
- Unfortunately, the `_ecal_methods` mapping binds the python API function `client_rem_response_callback` to the C++ function `client_add_response_callback`!
- None
=> Python: Fix client remove response callback

lang/python/core/ecal/core/core.py, lang/python/core/ecal/core/service.py
Fix python wrapper function name
`client_set_host_name` to `client_set_hostname`
the method defined here:
https://github.com/eclipse-ecal/ecal/blob/28ef1a150bf7e27d0748c124d42a7381f72c4862/lang/python/core/src/ecal_wrap.cxx#L1633C22-L1633C22
-
=> fix wrapper function miss matching

doc/requirements.txt
At the moment it seems to be the case that the recently released version 4.0.0 (end of nov) of python package empy is not compatible with our sphinx documentation build. As short-term fix the package version can be pinned to the previous version 3.3.4 so that the documentation build on the master branch works again.
=> Doc: Fixed compatibility issue with empy

ecal/core/src/io/udp_receiver.cpp, ecal/core/src/io/udp_receiver.h
Sporadic crashing of UDP layer shutdown (triggered by eCAL::Finalize ) by resetting the socket while still handling receives. Socket needs to be protected by mutex.
=> ensure correct udp socket concurrent handling by mutex

doc/requirements.txt
sphinxcontrib-applehelp 1.0.8 needs Sphinx 5 or up, but our old sphinx-book-theme 0.3.3 requires Sphinx 4
Fixes #1301
=> Doc: Downgraded applehelp in requirements.txt

doc/requirements.txt
* The most recent release of various sphinx related packages need Sphinx 5 or up, but our old sphinx-book-theme 0.3.3 requires Sphinx 4 For a proper solution see #1303
=> Doc: Downgraded sphinx related packages in requirements.txt (#1302)

app/meas_cutter/src/measurement_exporter.cpp, app/meas_cutter/src/measurement_exporter.h, app/meas_cutter/src/measurement_importer.cpp, app/meas_cutter/src/measurement_importer.h, app/meas_cutter/src/utils.h, app/play/play_core/src/ecal_play.cpp, app/play/play_core/src/measurement_container.cpp, app/play/play_core/src/measurement_container.h, app/play/play_core/src/play_thread.cpp, app/play/play_core/src/play_thread.h, app/rec/rec_client_core/src/job/hdf5_writer_thread.cpp, app/rec/rec_client_core/src/job/hdf5_writer_thread.h, contrib/ecalhdf5/include/ecalhdf5/eh5_meas.h, contrib/ecalhdf5/include/ecalhdf5/eh5_types.h, contrib/measurement/base/include/ecal/measurement/base/reader.h, contrib/measurement/base/include/ecal/measurement/base/types.h, contrib/measurement/base/include/ecal/measurement/base/writer.h, contrib/measurement/base/include/ecal/measurement/imeasurement.h, contrib/measurement/base/include/ecal/measurement/omeasurement.h, contrib/measurement/hdf5/include/ecal/measurement/hdf5/reader.h, contrib/measurement/hdf5/include/ecal/measurement/hdf5/writer.h, contrib/measurement/hdf5/src/reader.cpp, contrib/measurement/hdf5/src/writer.cpp, lang/python/ecalhdf5/src/ecalhdf5_wrap.cxx
Introduce experimental namespace for measurement to mark new API as not yet stable.
=> API: Introduce experimental namespace to mark new api as not yet stable.

ecal/core/src/pubsub/ecal_publisher.cpp, ecal/core/src/pubsub/ecal_subscriber.cpp
as the previous manual implementation was just plainly wrong.
Cherry-pick to:
- none
=> [Core] Default move constructor/assignment for CPublisher/CSubscriber

ecal/core/include/ecal/ecal_timer.h, ecal/core/include/ecal/msg/protobuf/dynamic_json_subscriber.h, ecal/core/include/ecal/msg/protobuf/dynamic_subscriber.h, ecal/core/src/config/ecal_config_reader.cpp, ecal/core/src/config/ecal_config_reader.h, ecal/core/src/ecal_descgate.h, ecal/core/src/monitoring/ecal_monitoring_def.cpp, ecal/core/src/monitoring/ecal_monitoring_def.h, ecal/core/src/monitoring/ecal_monitoring_impl.h, ecal/core/src/pubsub/ecal_proto_dyn_json_sub.cpp, ecal/core/src/time/ecal_timer.cpp
and replace with `make_shared` or `make_unique`.
There is really need for explicit use of `new` so replace with creation of shared/unique pointers.
- None (changes public API slightly and will therefore be ABI compatible)
=> [Core] Remove unnecessary `new` operators ... 

CMakeLists.txt, app/meas_cutter/CMakeLists.txt
- Fixes yaml-cpp compatability with CMake < 3.18
- See #1322 for details
- Corrects the minimum required version to 3.15
- Required for `list(APPEND)`
closes #1322
- none
=> fix: yaml-cpp compatability with CMake < 3.18

app/mon/mon_plugins/signals_plotting/src/signal_tree_model.cpp
"Number" and "Rule" were mixed up, before
- Fixes #130
=> Mon GUI: Fixed Column labels in signal plotting widget

ecal/core/include/ecal/msg/capnproto/subscriber.h, ecal/core/include/ecal/msg/flatbuffers/subscriber.h, ecal/core/include/ecal/msg/messagepack/subscriber.h, ecal/core/include/ecal/msg/protobuf/subscriber.h, ecal/core/include/ecal/msg/string/subscriber.h, ecal/core/include/ecal/msg/subscriber.h, testing/ecal/core_test/src/core_test.cpp
- Properly implement destructor (in inherited classes)! -> Destroy may not be called in base CMsgSubscriber class as this can lead to stack unwinding (most likely causes an exception in destructor, or leads to already deleted functions of derived class being called when they are already deleted)
- Correct order of RemReceiveCallback and resetting internal pointer
- protect function pointer with mutex.
- Make testcase "harder" to more easily trigger race conditions.
=> [Core] Fix Race Conditions in CMsgSubscriber

ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_writer.cpp
Sometimes callbacks which are stored in the event callback map do not exist anymore.
Nobody knows why. And we should rather fix the root.
However, this prevents eCAL from crashing.
=> [Core] Check validity of event callbacks before actually calling them.

ecal/core/src/io/udp/ecal_udp_sample_sender.cpp, ecal/core/src/io/udp/ecal_udp_sample_sender.h
This PR protects the `m_payload` member variable and thus makes the `Send()` function reentrant, as it may be called simultaneously from different threads.
Fixes #1332
- 5.12 (current stable) - Cherry picking might require making manual changes as files have been renamed betwween 5.12 and master.
=> [Core] Fix race condition in CSampleSender::Send() #1332

.github/workflows/build-macos.yml, contrib/ecalhdf5/CMakeLists.txt
This "hack" was added to enable cross compile builds.
However it's a bad hack, and it's not working for Macos runners, which somehow (some of them) are considered to be cross-compiling?
Alternatively, we could call find_package, and if it fails resort to finding it manually?
=> [CMake] CROSS_COMPILING builds should be able to locate hdf5.

ecal/core/src/ecal_registration_receiver.h
Added #include <mutex> to registration_provider.h. This is required for Ubuntu 18.04
=> Core: Fixed missing include

ecal/core/src/readwrite/ecal_reader.cpp
=> [Core] Check validity of message drop event callback before actually calling it

lang/python/ecalhdf5/ecal/measurement/writer.py
Description
Add high level API for writing measurements in Python
This was a first draft used in some Python tooling, and I thought it would be useful to bring it to the repo.
However, not yet 100% happy with the API, wouldn't want to make it stable. However the functionality may be valuable.
=> 1st draft for Python Measurement Writer.

ecal/service/ecal_service/src/client_session_impl_v0.cpp, ecal/service/ecal_service/src/client_session_impl_v1.cpp, testing/ecal/clientserver_test/src/atomic_signalable.h, testing/ecal/clientserver_test/src/clientserver_test.cpp
Before, the Service Client would only try the very first route to the Service Server. Now, it will go through all routes until it finds one that works.
- _none_
=> Services: Improved behavior when the first route to the server doesn't work

ecal/core/src/io/udp_receiver.cpp, ecal/core/src/io/udp_receiver.h
This reverts commit 771280e603494e57d6f817374d087b0a38a049e2.
The commit attempted to fix a racecondition. The result however are deadlocks and / or timeouts somewhere, which leads to ctest tests taking 40 minutes (instead of 5). Also, we were not able to reproduce the racecondition anymore, so this commit has be reverted.
- Fixes #1350
=> 5.12: Revert "ensure correct udp socket concurrent handling by mutex (#1289)"

ecal/core/src/readwrite/ecal_reader.cpp
check validity of message drop event callback before actually calling it. (#1346)
=> Cherry pick for 5.12

ecal/service/ecal_service/include/ecal/service/client_manager.h, ecal/service/ecal_service/include/ecal/service/client_session.h, ecal/service/ecal_service/include/ecal/service/server.h, ecal/service/ecal_service/include/ecal/service/server_manager.h, ecal/service/ecal_service/src/client_manager.cpp, ecal/service/ecal_service/src/client_session.cpp, ecal/service/ecal_service/src/client_session_impl_base.h, ecal/service/ecal_service/src/client_session_impl_v0.cpp, ecal/service/ecal_service/src/client_session_impl_v0.h, ecal/service/ecal_service/src/client_session_impl_v1.cpp, ecal/service/ecal_service/src/client_session_impl_v1.h, ecal/service/ecal_service/src/log_helpers.h, ecal/service/ecal_service/src/protocol_v0.cpp, ecal/service/ecal_service/src/protocol_v0.h, ecal/service/ecal_service/src/protocol_v1.cpp, ecal/service/ecal_service/src/server.cpp, ecal/service/ecal_service/src/server_impl.cpp, ecal/service/ecal_service/src/server_impl.h, ecal/service/ecal_service/src/server_manager.cpp, ecal/service/ecal_service/src/server_session_impl_base.h, ecal/service/ecal_service/src/server_session_impl_v0.cpp, ecal/service/ecal_service/src/server_session_impl_v0.h, ecal/service/ecal_service/src/server_session_impl_v1.cpp, ecal/service/ecal_service/src/server_session_impl_v1.h, ecal/service/test/src/ecal_tcp_service_test.cpp
Service header clean up, see  see https://github.com/eclipse-ecal/ecal-core/pull/15.
Based on changes by @FlorianReimold):
_I tried to apply the IWYU pragma. I mainly focused on std headers, as those don't come with umbrella headers._
- None
=> [new-core-alignment] service includes cleaned up

.github/workflows/documentation.yml
Documentation workflow now uses the modern `HAS_QT` option
- master-v5 (master for eCAL 5 feature backporting)
_Cherry pick to all support branches, even though they don't use Qt6, as the support branches still trigger the Qt6-enabled master for building the documentation_
=> [GH Actions] Documentation workflow now uses the modern HAS_QT option

.github/workflows/documentation.yml, CMakeLists.txt, thirdparty/cmakefunctions/cmake_functions/qt/qt_msvc_path.cmake
- Fixed handling of legacy HAS_QT5 option
- qt_msvc_path now sets the legacy Qt5 / Qt6 variables (with version) as well.
- master-v5 (master for eCAL 5 feature backporting)
=> [CMake] Fixed Qt Discovery

contrib/mma/include/linux/mma_linux.h, contrib/mma/include/linux/pipe_refresher.h, contrib/mma/include/logger.h, contrib/mma/src/linux/mma_linux.cpp, contrib/mma/src/linux/pipe_refresher.cpp, contrib/mma/src/logger.cpp, contrib/mma/src/mma.cpp, contrib/mma/src/mma_application.cpp, contrib/mma/src/query_manager.cpp, contrib/mma/src/zombie_instance_killer.cpp
Cleaned includes of ecal_mma.
- master-v5 (master for eCAL 5 feature backporting)
=> [mma] cleaned includes

CMakeLists.txt, build_win/Readme.md, build_win/win_set_vars.bat, cmake/qt_msvc_path.cmake, thirdparty/cmakefunctions/cmake_functions/cmake_functions.cmake
Now, Qt is discovered before QWT is included. Also, the script works with Qt6 now by setting the CMAKE_PREFIX_PATH
- Fixes #1374
=> [cmake] Fixed qt autodetection script

app/play/play_core/src/measurement_container.cpp
Currently if there are 0 items in a measurement, the player will crash.
Fixes #1378
- master-v5 (master for eCAL 5 feature backporting)
=> [play] fix crash when playing empty measurements.

cpack/innosetup.cmake
[CMake / Cpack] replaced deprecated exec_program with execute_process
=> [CMake / Cpack] replaces deprecated exec_program with execute_process

ecal/core/CMakeLists.txt
Added missing C++14 requirement in CMakeLists.txt
Important for very old gcc versions (tested with gcc5 on Ubuntu 16.04)
=> [Core / Process Stub] Added missing C++14 requirement in CMakeLists.txt

ecal/core/src/io/udp/sendreceive/udp_receiver_npcap.cpp
There has been an API break, but the code is still compatible with Udpcap 1 by using preprocessor checks. However, you will get a deprecation warning.
=> [Core/Submodule] Updated Udpcap to 2.0 (fixes lost-datagram-issues)

ecal/core/src/serialization/ecal_serialize_sample_registration.cpp, testing/ecal/serialization_test/src/registration_generate.cpp
Process state information was not serialized with nanopb and unfortunately not tested as well.
- _none_
=> [core] protobuf process state now serialized too

lang/python/core/CMakeLists.txt, lang/python/ecalhdf5/CMakeLists.txt
Fixes the Python C extensions having an explicit link dependency on libpython. In environments without libpython this causes problems. The easiest way to encounter this is through pyenv.
Eg: Building the wheel using a Python install that has libpython and trying to install and run it in a Python without it (static build).
The first hint of the problem is running `ldd` on the shared object when using a pyenv installation (for example):
``` 
ldd out/wheel/build/python/ecal/_ecal_core_py.so
linux-vdso.so.1 (0x00007ffefb729000)
libpython3.12.so.1.0 => not found
...
```
This will actually run fine if it is run in a Python interpreter that has a shared libpython as the wheels inherit the symbols from Python (see the PEP 513 link below). However; trying to run this eCAL wheel in a statically …
=> [python] Don't link C extensions to libpython

ecal/core/src/ecal.cpp
SetUnitName should not be able to set the eCAL global unit name to an empty string and nullptr argument should be handled as well.
=> set unit name empty string and nullptr handling fixed

ecal/tests/CMakeLists.txt, ecal/tests/c/core_test/CMakeLists.txt, ecal/tests/c/core_test/src/core_test.cpp, ecal/tests/cpp/core_test/src/core_test.cpp, ecal/tests/cpp/pubsub_test/src/pubsub_test.cpp
eCAL C API is currently not tested. Therefore a core C API test is added and the existing C++ API test is aligned with that.
- _none_
=> [core] core c test added / core cpp test cleaned up

ecal/service/ecal_service/src/client_session_impl_v0.cpp
Fix unused `endpoint` variable.
- _none_
=> [warnings] silence unused parameter warning 2

lib/EcalParser/src/functions/os.cpp
=> Ecal Parser: Added QNX and default OS

app/mon/mon_tui/src/model/data/topic.hpp, app/mon/mon_tui/src/model/monitor.hpp, app/mon/mon_tui/src/tui/view/message_visualization/factory.hpp, app/mon/mon_tui/src/tui/view/topic_details.hpp, app/mon/mon_tui/src/tui/viewmodel/topics.hpp
Mon Tui now displays and handles topic type and encoding separately, thus removing the need to combine them back together.
- _none_
=> [mon tui] Now displays encoding and type separately.

ecal/core/CMakeLists.txt, ecal/core/include/ecal/cimpl/ecal_core_cimpl.h, ecal/core/include/ecal/cimpl/ecal_log_cimpl.h, ecal/core/include/ecal/cimpl/ecal_monitoring_cimpl.h, ecal/core/include/ecal/ecal_log.h, ecal/core/include/ecal/ecal_monitoring.h, ecal/core/include/ecal/types/logging.h, ecal/core/include/ecal/types/monitoring.h, ecal/core/src/cimpl/ecal_log_cimpl.cpp, ecal/core/src/cimpl/ecal_monitoring_cimpl.cpp, ecal/core/src/logging/ecal_log.cpp, ecal/core/src/logging/ecal_log_impl.cpp, ecal/core/src/logging/ecal_log_impl.h, ecal/core/src/monitoring/ecal_monitoring_impl.cpp, ecal/core/src/serialization/ecal_serialize_logging.cpp, ecal/core/src/serialization/ecal_serialize_logging.h, ecal/tests/cpp/serialization_test/CMakeLists.txt, ecal/tests/cpp/serialization_test/src/logging_compare.cpp, ecal/tests/cpp/serialization_test/src/logging_generate.cpp, ecal/tests/cpp/serialization_test/src/logging_serialization_test.cpp
New public API function int GetLogging(Logging::SLogging& log_) to get log messages as struct without the need to serialize and deserialize it via protobuf.
- _none_
=> [core] new public api getlogging as struct

ecal/core/CMakeLists.txt, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer.h, ecal/core/src/util/frequency_calculator.h, ecal/tests/cpp/util_test/src/util_test.cpp
The frequency calculation for reader / writer frequencies was moved from reader.cpp / writer.cpp into it's own class.
The calculator properly handles frequencies below 1Hz and is able to reset if no data is coming in.
The calculator is not thread safe. Therefore mutexes are needed for synchronization.
The non-resettable calculator can probably be made threadsafe by moving the two members with are accessed concurrently into a struct with a size of < 8 bytes and proper memory alignment. Both functions could atomically load/store the values and a lock-free thread safety can be achieved.
The resettable calculator sees a bit harder. The unique_ptr needs to be handled and atomic unique_pointers are not available. That pointer may be created in `addTick` and destroyed in `getFrequency`, and I …
=> [core] create FrequencyCalculator class for sender / receiver frequency calculation.

cpack/innosetup/ecal_setup.iss.in
As the ECAL_DATA environment variable is suppose to be used only in cases when the user wants to load an ecal.ini configuration file from a custom location, there is no need that inno setup add this variable by default.
Related to #361
=> [deployment] Removed setting of ECAL_DATA environment variable in inno setup

.github/workflows/cherry-pick-label-check.yml
The action fails if there is no cherry-pick-to- label applied to a PR. The goal is to remind us of always applying a label explicitly.
=> [GH Actions] Create cherry-pick-label-check.yml

doc/rst/versions/5.13/deprecation.rst
Syntax fixes for `versions/5.13/deprecation.rst`.
=> [doc] v5.13 deprecation.rst fixed

ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_descgate.h
Incorrectly used shared_locks, when internally, data was modified.
Also deprecate the map on all function calls.
Based on PR #1459
=> [core] Bugfix: descgate incorrectly locked with shared locks (master)

app/rec/rec_tests/rec_rpc_tests/src/rec_cli_test.cpp, ecal/tests/c/core_test/src/core_test.cpp, ecal/tests/cpp/core_test/src/core_test.cpp, ecal/tests/cpp/util_test/src/util_test.cpp, tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp, tests/contrib/ecalproto/dynproto_test/src/dynproto_test.cpp, tests/contrib/ecalproto/ecal_proto_test/src/test_filters.cpp
* SetUnitName test by comparison via eCAL::Process::GetUnitName, eCAL_Process_GetUnitName. 
* (Out commented) PubSub tests removed from cpp core_test. These tests were moved to pubsub_test before.
* Renamed some test suites (app, contrib, hdf5) to get more consistent test grouping
=> [core, test] set-get-unit-name

app/play/play_gui/src/main.cpp, contrib/mma/src/mma_application.cpp, ecal/core/include/ecal/cimpl/ecal_init_cimpl.h, ecal/core/include/ecal/ecal_init.h, ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_descgate.h, ecal/core/src/ecal_globals.cpp, ecal/core/src/monitoring/ecal_monitoring_impl.cpp, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_publisher.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer.h, ecal/core/src/registration/ecal_registration_provider.cpp, ecal/core/src/registration/ecal_registration_provider.h, ecal/core/src/registration/ecal_registration_receiver.cpp, ecal/core/src/registration/ecal_registration_receiver.h, ecal/core/src/service/ecal_clientgate.cpp, ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_client_impl.h, ecal/core/src/service/ecal_service_server.cpp, ecal/core/src/service/ecal_service_server_impl.cpp, ecal/core/src/service/ecal_service_server_impl.h, ecal/tests/CMakeLists.txt, ecal/tests/cpp/clientserver_test/src/clientserver_getservices.cpp, ecal/tests/cpp/pubsub_test/src/pubsub_gettopics.cpp, ecal/tests/cpp/util_test/src/util_test.cpp
DescGate logic refactored:
- SHM and UDP registrations collected in common SampleList
- ApplyDescription/Type whole quality logic moved to desc_gate.cpp unit
- eCAL Initialize flag ProcessReg removed (should be set always)
Needs to be written.
=> [core] description gate refactoring

.gitmodules, cmake/submodule_dependencies.cmake, thirdparty/ecaludp/build-ecaludp.cmake
Added ecaludp as submodule.
Adapted submodule_dependencies.cmake.
Removed the line `add_library(ecaludp::ecaludp ALIAS ecaludp)` from build-ecaludp.cmake integration from ecal-core as per feedback from @rex-schilasky.
=> Added ecaludp as submodule.

thirdparty/qwt/CMakeLists.txt
The CMakeLists.txt reused QWT_LIBRARY_TYPE to get the target property type later and thus changed the user-defined value. Technically it was still correct, but now the variable is not reused anymore which is much nicer.
=> [QWT cmake] Fixed variable reuse of QWT_LIBRARY_TYPE

ecal/tests/CMakeLists.txt, ecal/tests/cpp/util_test/src/util_test.cpp
Minimal fix: ParallelGetTopics (core/util_test) gtest was excluded due to ECAL_CORE_PUBLISHER condition (that should not used in test cpp modules, because all ECAL_CORE_XY variables are not forwarded as compiler defines.)
=> [core/test] util_test (ParallelGetTopics) was excluded due to incorrect CMake setting

ecal/core/src/config/ecal_config_reader.cpp, ecal/core/src/config/ecal_config_reader.h, ecal/core/src/ecal_def.h, ecal/core/src/ecal_def_ini.h
ecal_def.h and ecal_def_ini.h converted from defines to use constexpr.
In addition, ecal_config_reader.h/.cpp got a unsigned int and size_t read function.
=> Convert defines to constexpr

ecal/core/src/registration/ecal_registration_provider.cpp
ecal_registration_provider.cpp: m_sample_list_sync should also protect m_sample_list_buffer.
=> [core] Fix possible race condition

app/mon/mon_gui/src/widgets/models/service_tree_item.cpp
Very simple fix. Adds the service name to the `ServiceTreeItem` identifier so that different services running on the same host/process with the same methods don't get accidentally de-duped in `ecal_mon_gui`.
This PR fixes the following bug:
This Python program creates two different eCAL services with the same PID, host, and method name.
```
import ecal.core.core as ecal_core
import ecal.core.service as ecal_service
import sys, time
def callback():
pass
ecal_core.initialize(sys.argv, "BugDemo")
server1 = ecal_service.Server("MyService1")
server1.add_method_callback("GetConfig", "string", "string", callback)
server2 = ecal_service.Server("MyService2")
server2.add_method_callback("GetConfig", "string", "string", callback)
try:
while True:
time.sleep(1)
except KeyboardInterrupt:
pass
finally: …
```
=> [Mon] Fix service collisions on ecal_mon_gui (5.13)

ecal/core/src/io/udp/sendreceive/udp_receiver_npcap.cpp
Fixed the deprecation warning. The old warning didn't work with Visual Studio 2017
=> [Core] Fixed Udpcap warning

.github/workflows/build-macos.yml
The github runners were updated to macos-13, which is not able to build ecal.
=> downgrade macos version.

.github/workflows/build-windows.yml
The self-signed certificate is not needed anymore, as we use the official Eclipse certificate.
- Fixes #1546
=> [GH Actions] Removed Code-sign action with self-signed certificate

app/mon/mon_gui/src/widgets/models/topic_tree_item.cpp, app/mon/mon_tui/src/model/monitor.hpp
Current (master) monitoring gui/tui apps visualize all transport layer as active independently from their confirmed state. Issue is not existing in 5.12/5.13 series.
=> [app] ecalmon layer detection logic

ecal/core/include/ecal/ecal_util.h
Added missing include for Compiling on Ubuntu 23.10 with gcc 13.2.0
=> [Core] Added missing include

ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer.h, ecal/core/src/readwrite/ecal_writer_base.h, ecal/core/src/readwrite/shm/ecal_writer_shm.cpp, ecal/core/src/readwrite/shm/ecal_writer_shm.h, ecal/core/src/readwrite/tcp/ecal_writer_tcp.cpp, ecal/core/src/readwrite/tcp/ecal_writer_tcp.h, ecal/core/src/readwrite/udp/ecal_writer_udp_mc.cpp, ecal/core/src/readwrite/udp/ecal_writer_udp_mc.h
All eCAL writer Create/Destroy functions removed. Constructor and destructor should be used to construct writers for udp, shm, tcp.
Fixes #1475
=> [core] writer refactoring based on unique ptr

ecal/tests/cpp/util_test/src/util_gettopics.cpp
The include is required for Compiling on Ubuntu 20.04 with gcc 9.4.0
=> [Core Tests] Added missing include

ecal/service/ecal_service/src/server_session_impl_v0.cpp, ecal/service/ecal_service/src/server_session_impl_v0.h, ecal/service/test/src/ecal_tcp_service_test.cpp
The crash occured when a v0 client connected to a service server.
- Fixes #1578
=> [Core / Service]: Fixed crash that occured when communicating with eCAL 5.12 services

ecal/core_pb/src/ecal/core/pb/ecal.proto, ecal/core_pb/src/ecal/core/pb/layer.proto, ecal/service/ecal_service/src/client_session_impl_v0.cpp, ecal/service/ecal_service/src/client_session_impl_v1.cpp
- fixed lambda caputres (not sure why I had to do that in those places but not in others)
- Removed reserved fields from protobuf enums
=> [Core, Services, Protobuf] Fixed compatibility with Ubuntu 18.04 (gcc7 / protobuf 3.0)

lib/CustomQt/src/QMulticolumnSortFilterProxyModel.cpp
The MultiColumnSortFilterProxyModel now supports QRegexp and QRegularExpression depending on the Qt Version
- Fixes #1589
=> [Mon / Qt Apps] Fixed filter-function

.clang-tidy
The code that clang tidy suggests is available in C++20 and later only.
Also, I don't agree that the suggestions are more readable.
=> [.clangtidy] Disabled readability-use-anyofallof warning

app/rec/rec_gui/src/widgets/recording_history_widget/job_history_model.cpp, app/rec/rec_gui/src/widgets/wait_for_shutdown_dialog/wait_for_shutdown_dialog.cpp, app/rec/rec_server_cli/src/ecal_rec_server_cli.cpp
The bugs were caused from changing bit-wise | and & to boolean versions, which caused the latter functions to not be evaluated. Turning around the parameter fixes the issue too, without bit-wise operators (those are prone to warnings)
- Fixes #1590
=> [Rec] Fixed "Recording" display bug and some other bugs

ecal/core/CMakeLists.txt, ecal/core/include/ecal/ecal_publisher_config.h, ecal/core/include/ecal/ecal_subscriber.h, ecal/core/include/ecal/ecal_subscriber_config.h, ecal/core/src/ecal_globals.cpp, ecal/core/src/io/shm/ecal_memfile_db.cpp, ecal/core/src/io/shm/ecal_memfile_db.h, ecal/core/src/io/shm/ecal_memfile_pool.cpp, ecal/core/src/io/shm/ecal_memfile_pool.h, ecal/core/src/logging/ecal_log_impl.cpp, ecal/core/src/logging/ecal_log_impl.h, ecal/core/src/monitoring/ecal_monitoring_def.cpp, ecal/core/src/monitoring/ecal_monitoring_def.h, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_pubgate.h, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/core/src/pubsub/ecal_subscriber_config.cpp, ecal/core/src/registration/ecal_registration_provider.cpp, ecal/core/src/registration/ecal_registration_provider.h, ecal/core/src/registration/ecal_registration_receiver.cpp, ecal/core/src/registration/ecal_registration_receiver.h, ecal/core/src/time/ecal_timegate.cpp, ecal/core/src/time/ecal_timegate.h
CSubscriber configuration introduced.
=> [core] subscriber configuration

ecal/core/include/ecal/msg/protobuf/dynamic_json_subscriber.h, ecal/samples/cpp/pubsub/protobuf/proto_dyn_json_rec/CMakeLists.txt, ecal/samples/cpp/pubsub/protobuf/proto_dyn_json_rec/src/proto_dyn_json_rec.cpp
based on CDynamicMessageSubscriber
eCAL::protobuf::CDynamicJSON Subscriber is now based on CDynamicMessageSubscriber, which greatly simplifies code.
API break: the message callback API is now changed, which should be fine for eCAL 6.
=> [core] Move eCAL::protobuf::CDynamicJSONSubscriber

ecal/core/src/readwrite/ecal_writer.cpp
=> send frequency calculation fixed in case of unconnected publisher

lang/csharp/Continental/eCAL/Protobuf/ProtoSubscriber.cs
as this cannot reset fields which are not contained on the wire. (#1593)
Fixes #1593
=> [c#] Do not reuse Protobuf message objects in callbacks

.github/workflows/build-ubuntu.yml
Added Ubuntu 24.04 (currently in beta) to GH workflows. 
Info: https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/
=> [GH] Adding Ubuntu 24.04 to GH workflows

ecal/core/src/io/udp/sendreceive/udp_receiver.cpp
It turns out that the newly introduced locks in 5.13.x in the UDP Receiver methods create a side effect when creating new subscribers in the process. When a the Subscriber in a process is created, a Sample Receiver is created as well, which simultaneously creates a UDP receiver. Once the UDP Receiver object is gone up, the Receive() method is called repeatedly via a thread with a timeout of 1000 ms. As a result, the lock is already blocked, which means that AddMultiCastGroup/RemMultiCastGroup can only be called every 1000 ms in the worst case, which also delays the creation of each additional subscriber in the process.
The fix resolves the dependency on the lock by removing it from the AddMultiCastGroup/RemMultiCastGroup method.
**The issue only exists in the 5.13.x release. Neither the …
=> [core] Removed locks in AddMultiCastGroup()/RemMultiCastGroup() method to prevent blocking when Receive() is called in parallel.

.github/workflows/build-ubuntu-24.yml
Added ubuntu 24 build to Github Actions
- 5.12
=> Feature/ubuntu 24 runner for 5.13 5.12

ecal/core/src/util/ecal_expmap.h, ecal/samples/cpp/monitoring/monitoring_get_topics/src/monitoring_get_topics.cpp
For large maps the `update_timestamps` function is not performing well.
* Utilization of find Function: The find function is used to search for the key k in the `_key_to_value` map, rather than using at, which would throw an exception if the key is not found.
* Splicing Instead of Erasing and Inserting: Instead of erasing and re-inserting elements into the `_key_tracker` list, the new version uses the splice function to move the element to the end of the list, improving efficiency.
* Timestamp Update Improvement: The timestamp update logic has been simplified and made more explicit by directly assigning the current time to the timestamp associated with the key k.
* Simplified Clear Functionality: Just clearing the internal map and list without iterating over their elements.
=> [core] expmap performance improvement

ecal/core/src/util/ecal_expmap.h, samples/cpp/monitoring/monitoring_get_topics/src/monitoring_get_topics.cpp
* performance improvement of update_timestamp for large maps (tested with > 25 k entries)
* monitoring_get_topics sample slightly improved to allow time updates of internal (large) expmaps in case of subsequent readings
=> [core] expmap performance improvement (#1626)

ecal/core/include/ecal/ecal_subscriber.h, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/core/src/readwrite/ecal_reader.h, testing/ecal/pubsub_test/src/pubsub_receive_test.cpp
* additional check for CSubscriber::GetPublisherCount() using the connection state of the matching subscriber to ensure that GetPublisherCount is increased only if the matching publisher is able to send data
* test added to test new behavior
=> [core] add/improved IsPublished/IsSubscribed logic (5.13.x)

ecal/core/src/pubsub/ecal_subgate.cpp, testing/ecal/pubsub_test/src/pubsub_receive_test.cpp
* additional check for CSubscriber::GetPublisherCount() using the connection state of the matching subscriber to ensure that GetPublisherCount is increased only if the matching publisher is able to send data
* test added to test new behavior
=> [core] add/improved IsPublished/IsSubscribed logic (5.12.x)

ecal/core/src/util/ecal_expmap.h, ecal/tests/cpp/expmap_test/src/expmap_test.cpp
This improves testability and allows to expire based on different time base, if required.
=> [core] Expmap takes additional template parameter for clock type.

ecal/core/include/ecal/ecal_publisher.h, ecal/core/src/pubsub/ecal_publisher.cpp, ecal/samples/cpp/benchmarks/dynsize_snd/src/dynsize_snd.cpp
=> const keyword removed from send() in publisher files

ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_descgate.h, ecal/core/src/monitoring/ecal_monitoring_impl.cpp, ecal/core/src/monitoring/ecal_monitoring_impl.h, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer.h, ecal/core/src/service/ecal_clientgate.cpp, ecal/core/src/service/ecal_clientgate.h, ecal/core/src/util/ecal_expmap.h, ecal/tests/cpp/expmap_test/src/expmap_test.cpp
Internally refactoring of CExpMap (for better understandability).
=> [core] Refactoring / Renaming / Documentation of CExpMap 

ecal/core/include/ecal/ecal_subscriber.h, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/tests/cpp/pubsub_test/src/pubsub_receive_test.cpp
* new CSubscriber method "IsPublished" added
* additional check for IsPublished using the connection state of the matching subscriber to ensure that IsPublished is flagged true only if publisher is able to send data
* test added to test new behavior
=> [core] add/improved IsPublished/IsSubscribed logic (master)

ecal/samples/cpp/services/latency_client/src/latency_client.cpp, ecal/samples/cpp/services/math_client/src/math_client.cpp, ecal/samples/cpp/services/ping_client/src/ping_client.cpp, ecal/samples/cpp/services/ping_client_dyn/src/ping_client_dyn.cpp
These samples did not react on ecal_stop (shutdown). eCAL::Ok() needs to be checked properly.
=> [sample] shutdown condition fixed

ecal/core/src/util/frequency_calculator.h, ecal/tests/cpp/util_test/src/util_test.cpp
The internal frequency calculation method is changed in a way that it only resets in cases when no data has been incoming over a longer period of time.
Fixes #1649
=> [core] Fix bug in frequency calculator that will reset the frequency to 0.0 even though data is still incoming.

cpack/innosetup/ecal_setup.iss.in
The windows gh action temporary folders for install and configuration files seems to be changed from
1. configuration -> _configuration
2. configinstall -> _configinstall
=> [core] innosetup-configuration-path-fix

.github/workflows/build-macos.yml
Kill XProtect to avoid malware scan of dmg image.
See https://github.com/actions/runner-images/issues/7522
=> [gh-actions] kill-xprotect-scan-macos

ecal/core/include/ecal/config/publisher.h, ecal/core/include/ecal/config/subscriber.h, ecal/core/include/ecal/config/transport_layer.h, ecal/core/include/ecal/ecal_config.h, ecal/core/src/config/ecal_config.cpp, ecal/core/src/config/ecal_config_initializer.cpp, ecal/tests/cpp/config_test/src/config_test.cpp
Cleanup of unused member in transportlayer configuration as well as removing API call functions that relate to that.
Changed executor reader/writer amount configuration to publisher and subscriber.
=> [config] cleanup

ecal/core/CMakeLists.txt, ecal/core/src/config/ecal_cmd_parser.cpp, ecal/core/src/config/ecal_config_reader.cpp, ecal/tests/cpp/config_test/CMakeLists.txt
sync-with-ecal-core-2024-07-17
=> sync-with-ecal-core-2024-07-17

ecal/core/CMakeLists.txt, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_transport_layer.h, ecal/core/src/readwrite/ecal_writer.cpp
Transport layer version is increased from 1 to 2 for eCAL6. This allows to recognize registrations of old transport layer configurations not containing the new dynamic enabling feature. In this case the transport layer is interpreted as enabled and the communication eCAL5 <> eCAL6 is kept compatible.
=> [core] new-pub-sub-matching-compatibility-5

samples/CMakeLists.txt, samples/cpp/benchmarks/massive_pub_sub/CMakeLists.txt, samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
Sample to compare pub/sub creation performance over different eCAL versions.
=> [sample] benchmark-sample-massive_pub_sub-added

ecal/core/src/registration/shm/ecal_registration_sender_shm.cpp, ecal/core/src/registration/shm/ecal_registration_sender_shm.h, ecal/core/src/registration/udp/ecal_registration_sender_udp.cpp, ecal/core/src/registration/udp/ecal_registration_sender_udp.h
Class member variable (sample list buffer) moved into local function scope to avoid dataraces when calling SendSampleList() out of different threads.
=> [core] registration-sender-datarace-fix

ecal/core/cfg/ecal.yaml, ecal/core/src/config/default_config.h, ecal/core/src/ecal_globals.cpp, ecal/core/src/monitoring/ecal_monitoring_impl.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer.h, ecal/core/src/readwrite/tcp/ecal_reader_tcp.cpp, ecal/core/src/readwrite/tcp/ecal_reader_tcp.h, ecal/core/src/registration/ecal_registration_provider.cpp, ecal/core/src/registration/ecal_registration_provider.h, ecal/core/src/registration/ecal_registration_sample_applier.cpp, ecal/core/src/registration/ecal_registration_sample_applier.h, ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_client_impl.h, ecal/core/src/service/ecal_service_server_impl.cpp, ecal/core/src/service/ecal_service_server_impl.h, ecal/core/src/util/ecal_thread.h, ecal/tests/cpp/util_test/src/util_getclients.cpp, ecal/tests/cpp/util_test/src/util_getservices.cpp, ecal/tests/cpp/util_test/src/util_gettopics.cpp
* registration provider single threaded send logic
* Register(false) calls removed finally
=> [core] registration-provider-refactoring

ecal/core/include/ecal/msg/protobuf/publisher.h, ecal/tests/cpp/pubsub_proto_test/src/proto_subscriber_test.cpp
The Send function incorrectly always returns 0 for protobuf pusblishers.
This PR fixes this behavior.
=> [core] Protobuf Publisher Send should return the actual send size.

ecal/core/src/io/shm/ecal_memfile_pool.cpp, ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp
zero length payload was not transferred over shm in zero copy mode
=> [core] zero-copy-zero-payload-shm-transfer

ecal/core/src/readwrite/ecal_writer.cpp
=> [core] missing-include-ecal-writer

ecal/core/include/ecal/ecal_registration.h, ecal/core/include/ecal/ecal_types.h, ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_descgate.h, ecal/core/src/registration/ecal_registration.cpp, ecal/core/src/serialization/ecal_struct_sample_registration.h, ecal/tests/CMakeLists.txt, ecal/tests/cpp/descgate_test/CMakeLists.txt, ecal/tests/cpp/descgate_test/src/descgate_getentities.cpp, ecal/tests/cpp/registration_test_public/CMakeLists.txt, ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp, ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp, ecal/tests/cpp/registration_test_public/src/registration_gettopics.cpp
Descgate API changed to use separate GetEntityIDs() + GetEntityInfo(id) functions instead of single GetEntities() variants.
=> [core] feature/id-based-descgate

ecal/core/include/ecal/ecal_types.h, ecal/core/src/ecal_descgate.cpp, ecal/core/src/serialization/ecal_struct_sample_registration.h
=> [core] eCAL sample completely internal, only SEntityId public.

.github/workflows/build-macos.yml
Let brew overwrite the existing python symlinks
=> [GH] Hotfix macos build

ecal/tests/cpp/registration_test_public/src/registration_gettopics.cpp
Rewrite the test in such a way that the execution time is always the same, and the test will only fail but not hang indefinately.
=> [core] Rewrite GetTopicsParallel test to be more robust.

ecal/samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
Sample massive-pub-sub adapted to:
- use shm monitoring mode
- demonstrate usage and performance of the new eCAL::Registration::GetPublisher|SubscriberID's API
=> [sample] sample massive_pub_sub adapted

lang/python/core/src/ecal_wrap.cxx
Add some missing monitoring info to the eCAL monitoring python dictionary (for d-fine prototyping).
=> [python] add-monitoring-info

ecal/core/include/ecal/config/monitoring.h, ecal/core/include/ecal/config/registration.h, ecal/core/include/ecal/ecal_config.h, ecal/core/src/builder/monitoring_attribute_builder.cpp, ecal/core/src/builder/registration_attribute_builder.cpp, ecal/core/src/config/configuration_to_yaml.cpp, ecal/core/src/config/default_configuration.cpp, ecal/core/src/config/ecal_config.cpp, ecal/core/src/registration/attributes/registration_attributes.h, ecal/core/src/registration/ecal_registration_receiver.cpp, ecal/tests/cpp/config_test/src/config_test.cpp
Remove the monitoring timeout from Config (+API function) because it is no longer used within eCAL.
Additionally, the default registration timeout is set to 10 seconds as a compromise between a stable connection and up to date display in eCAL Monitor.
=> [core] remove monitoring timeout

ecal/core/include/ecal/config/registration.h, ecal/core/src/builder/registration_attribute_builder.cpp
The registration.host_group_name now will be set by default to an empty string. Instead, the ProcessName gets added in the registration attribute builder, if the string is empty. The logic behind the host_group_name needs to get checked later on.
=> [config] Move host_group_name logic

ecal/tests/cpp/config_test/src/config_test.cpp, ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp, ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp
=> [core] 2 tests renamed

samples/CMakeLists.txt, samples/python/monitoring/monitoring_json/CMakeLists.txt, samples/python/monitoring/monitoring_json/monitoring_json.py, samples/python/monitoring/monitoring_json/monitoring_json.pyproj
Python sample added that converts the monitoring dictionary into a JSON representation. Unfortunately we can not implement this in the c++ runtime core, because NanoPb is not supporting this feature (convert protocol buffer to JSON).
=> [python] python-monitoring-json-sample-added

doc/rst/configuration/options.rst, doc/rst/configuration/runtime_configuration.rst, doc/rst/configuration/src/hello_config/main.cpp, ecal/core/include/ecal/config/publisher.h, ecal/core/include/ecal/config/transport_layer.h, ecal/core/src/config/configuration_to_yaml.cpp, ecal/core/src/config/configuration_to_yaml.h, ecal/core/src/config/default_configuration.cpp, ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
The memfile settings where split between transport_layer and publisher config. Now all is available only in the publisher config to enable individual configuration for each publisher.
=> [config] Move complete memfile config to publisher

ecal/msg/protobuf/src/ecal_proto_decoder.cpp, ecal/samples/cpp/pubsub/protobuf/proto_dyn_rec/src/proto_dyn_rec.cpp
Removed size check on cpp message types in protobuf reflection.
Impact: Empty message fields are visible, e.g. in eCAL monitor protobuf reflection plugin
=> [protobuf] Improved protobuf reflection for empty submessages

ecal/msg/protobuf/src/ecal_proto_decoder.cpp, ecal/samples/cpp/pubsub/protobuf/proto_dyn_rec/src/proto_dyn_rec.cpp
To avoid infinite recursive for recursive proto definitions readded the msg_size check and additionally a field name find check. The later enables the msg to show at least one default submsg, even if every field is just a default value.
=> [protobuf] Readded msg_size and field name check to ProcProtoMsg recursion

ecal/core/include/ecal/ecal_callback.h, ecal/core/include/ecal/ecal_publisher.h, ecal/core/include/ecal/ecal_subscriber.h, ecal/core/include/ecal/ecal_types.h, ecal/core/src/io/shm/ecal_memfile_pool.cpp, ecal/core/src/io/shm/ecal_memfile_pool.h, ecal/core/src/pubsub/ecal_publisher.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/pubsub/ecal_subgate.h, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, ecal/core/src/readwrite/ecal_writer.h, ecal/core/src/readwrite/shm/ecal_reader_shm.cpp, ecal/core/src/readwrite/shm/ecal_reader_shm.h, ecal/core/src/readwrite/tcp/ecal_reader_tcp.cpp, ecal/core/src/readwrite/tcp/ecal_writer_tcp.cpp, ecal/core/src/readwrite/udp/ecal_writer_udp.cpp, ecal/core/src/serialization/ecal_serialize_sample_payload.cpp, ecal/core/src/serialization/ecal_struct_sample_payload.h, ecal/samples/cpp/benchmarks/many_connections_rec/src/many_connections_rec.cpp, ecal/tests/cpp/pubsub_test/CMakeLists.txt, ecal/tests/cpp/pubsub_test/src/pubsub_callback_topicid.cpp, ecal/tests/cpp/serialization_test/src/payload_compare.cpp, ecal/tests/cpp/serialization_test/src/payload_generate.cpp
- Add new Callback Type which includes STopicId (ecal_callback.h)
- Remove topic_name and topic_id from memfile_pool
- Subgate applies Payload::Topic
TODO: take care of PID for TCP and UDP layer.
We don't yet have the information in callbacks about *who* sent a message, we only receive the topic name. This PR fixes this in a way that callbacks receive an `STopicID` containing both topic name and additional information (unique sender id).
=> [core] Make STopicId available in subscriber callbacks

ecal/core/include/ecal/ecal_callback.h, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, ecal/core/src/serialization/ecal_struct_sample_registration.h, ecal/samples/cpp/benchmarks/many_connections_rec/src/many_connections_rec.cpp, ecal/tests/cpp/pubsub_test/src/pubsub_callback_topicid.cpp
We now have the possibility to provide the DatatypeInformation in Callbacks, which makes it much easier for dynamic subscribers to deserialize data, without needing to look it up elsewhere.
@rex-schilasky 
I now have a few questions:
- We only provide this information for the callbacks. What about the `Receive` method?
- What about callback and receive signatures for protobuf subscribers and dynamic subscribiers?
=> [core] provide SDataTypeInformation in callbacks

ecal/core/src/ecal_descgate.cpp, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/util/ecal_expmap.h
These are some minor performance improvements for eCAL core, to avoid unnessecary copies or indexing into potentially large maps.
=> [core] minor performance improvements

lang/python/core/src/ecal_wrap.cxx
Use correct values for ecal_wrap.cxx connections_loc/ext and message_drops.
Also set ecal_wrap.cxx connections_loc/ext and message_drops to int, otherwise mon_monitoring() function will cause the algo to crash.
=> [python] Bugfix mon_monitoring() crash

ecal/core/CMakeLists.txt, ecal/core/include/ecal/ecal_types.h, ecal/core/src/pubsub/ecal_pubgate.cpp, ecal/core/src/pubsub/ecal_subgate.cpp, ecal/core/src/readwrite/ecal_reader.cpp, ecal/core/src/readwrite/ecal_reader.h, ecal/core/src/readwrite/ecal_writer.cpp, ecal/core/src/readwrite/ecal_writer.h, ecal/core/src/registration/ecal_registration_provider.cpp, ecal/core/src/registration/ecal_registration_provider.h, ecal/core/src/registration/shm/ecal_registration_receiver_shm.cpp, ecal/core/src/registration/shm/ecal_registration_receiver_shm.h, ecal/core/src/registration/udp/ecal_registration_sender_udp.cpp, ecal/core/src/serialization/ecal_serialize_common.cpp, ecal/core/src/serialization/ecal_serialize_common.h, ecal/core/src/serialization/ecal_serialize_sample_registration.cpp, ecal/core/src/serialization/ecal_struct_sample_common.h, ecal/core/src/serialization/ecal_struct_sample_registration.h, ecal/core/src/serialization/ecal_struct_service.h, ecal/core/src/service/ecal_clientgate.cpp, ecal/core/src/service/ecal_servicegate.cpp, ecal/core/src/util/expanding_vector.h, ecal/tests/cpp/serialization_test/src/registration_compare.cpp, ecal/tests/cpp/serialization_test/src/registration_generate.cpp, ecal/tests/cpp/serialization_test/src/registration_serialization_test.cpp, ecal/tests/cpp/util_test/CMakeLists.txt, ecal/tests/cpp/util_test/src/expanding_vector_test.cpp
In bigger, idle eCAL System there is quite a large "Grundlast" in the system, due to how Registrations are processed.
This PR tries to solve that, by providing a `Util::CExpandingVector` which only deallocates members upon destruction, and avoiding any unnessesary instatiations of `eCAL::Sample` instances.
=> [core] Reduce allocation / deallocations necessary for Registration.

lang/python/ecalhdf5/ecal/measurement/measurement.py
When Binary Reading mode was introduced to the Python API, this broke the regular iteration over a measurement.
This PR fixes this.
Fixes #1748
=> [python] Fix iterating over measurement which was broken by fe84826

cpack/innosetup/ecal_setup.iss.in
Innosetup takes files from internal cpack install locations, to pack them all together.
Adapt the Innosetup script to reflect different paths for different cpack versions.
=> [innosetup] Adapt innosetup script to different cpack conventions.

lang/python/core/src/ecal_wrap.cxx, lang/python/ecalhdf5/src/ecalhdf5_wrap.cxx
When writing Python extensions from C++, objects created with `Py_BuildValue`, `Py_....` need their references decremented unless they are returned directly from the functions.
This PR fixes some occurences where the ref counters where not decreased, which leads to memory leaks.
Fixes #1753
=> Fix memory leaks in Python wrapper by adding missing Py_DECREF.

lang/python/core/src/ecal_wrap.cxx
If you used a service client and server in the same process (like described in this issue: https://github.com/eclipse-ecal/ecal/issues/1755), the application locks. With this fix, it does not lock anymore and function as expected.
=> [python] Call_method in service now allows threads.

ecal/core/src/registration/ecal_process_registration.cpp, ecal/core/src/serialization/ecal_serialize_sample_registration.cpp, ecal/tests/cpp/serialization_test/src/registration_generate.cpp
Correctly keeps processes in CExpiringMap of unregistration provider.
Now their id is the `process_id` instead of `""`, which lead to process entries overwriting themselves in tthe map kept by the unregistration provider.
Fixes #1763
=> [core] fix bug that processes will not be "unregistered" correctly.

ecal/core/src/service/ecal_clientgate.cpp, ecal/core/src/service/ecal_clientgate.h, ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_client_impl.h, ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp
Service client connection state (IsConnected) now handled correctly. Connection state is true if a matching server (at least one) is connected on lower client/service API level. We might change this API even more to return the states of all matching server.
#1779 
<!-- Leave empty, if you don't know. For master-only changes use "none"
=> service client connection state handling

ecal/core/src/config/ecal_config.cpp, ecal/core/src/config/ecal_config_initializer.cpp, ecal/core/src/registration/ecal_registration.cpp
We should use the `ECAL_API` macro in header files only.
=> [core] Remove ECAL_API occurrences in cpp files.

ecal/service/ecal_service/src/client_session_impl_v0.cpp, ecal/service/ecal_service/src/client_session_impl_v1.cpp
eCAL service client is offering event callback functionality. Like this
```c++
const eCAL::service::ClientSession::EventCallbackT event_callback = []
(eCAL::service::ClientEventType /*event*/, const std::string& /*message*/) -> void
{
};
client_session = client_manager->create_client(protocol_version, endpoint_list, event_callback);
```
If the event callback logic is not relevant for your use case I would expect to just pass a nullptr like this
```c++
client_session = client_manager->create_client(protocol_version, endpoint_list, nullptr);
```
but this leads to a crash.
None
- _none_
=> check event callback before execution

ecal/core/src/pubsub/config/builder/reader_attribute_builder.cpp
[This commit](https://github.com/eclipse-ecal/ecal/commit/10366571caa6ab7d81d9aa0618254739dca7ab05#diff-2cdf63d88eed3c28f62b4d0f6e7b8769a5117c887e6ed8eef99aa39636b3c9a0) introduced some problems which show in the monitor like this:
The uname of a process is not set properly, it was missed in the attribute builder.
This PR fixes this.
=> [core][bugfix] attributes.unit_name not initialized.

.github/workflows/build-macos.yml
The packing usually fails and we don't use the artifacts anyways
=> [GH Actions] Removed macOS packing step

app/play/play_core/include/ecal_play.h, app/play/play_core/src/ecal_play.cpp, app/play/play_core/src/measurement_container.cpp, app/play/play_core/src/measurement_container.h, app/play/play_core/src/play_thread.cpp, app/play/play_core/src/play_thread.h, app/play/play_gui/src/q_ecal_play.cpp, app/play/play_gui/src/q_ecal_play.h, app/play/play_gui/src/widgets/channel_widget/channel_widget.cpp, app/play/play_gui/src/widgets/models/channel_tree_item.cpp, app/play/play_gui/src/widgets/models/channel_tree_item.h, app/play/play_gui/src/widgets/models/channel_tree_model.cpp, app/play/play_gui/src/widgets/models/channel_tree_model.h
=> [play] Separate Encoding and Type in Player application.

ecal/core/include/ecal/ecal_monitoring.h, ecal/core/src/monitoring/ecal_monitoring_def.cpp, lang/python/core/src/ecal_wrap.cxx
=> [core] Changed return types of monitoring api to booleans

ecal/core/src/cimpl/ecal_monitoring_cimpl.cpp, lang/python/core/src/ecal_clang.cpp, lang/python/core/src/ecal_clang.h, lang/python/core/src/ecal_wrap.cxx
=> [core] Adapted c-api of monitoring in the way to remain c-return value compliant

ecal/core/include/ecal/ecal_client.h, ecal/core/include/ecal/ecal_registration.h, ecal/core/include/ecal/ecal_server.h, ecal/core/include/ecal/ecal_types.h, ecal/core/src/service/ecal_service_client.cpp, ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_client_impl.h, ecal/core/src/service/ecal_service_server.cpp, ecal/core/src/service/ecal_service_server_impl.cpp, ecal/core/src/service/ecal_service_server_impl.h
Implements `GetServiceId` for `CServiceClient` and `CServiceServer`.
=> [core] get service id implementation

contrib/ecalhdf5/src/hdf5_helper.cpp, contrib/ecalhdf5/src/hdf5_helper.h, contrib/measurement/base/include/ecal/measurement/base/types.h, tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
Changes the underlying type of the topic ID (there is no reason for IDs to be of a signed type).
Also add missing license headers.
=> Use uint64_t for topic id in hdf5

app/mon/mon_gui/src/ecalmon.cpp, app/mon/mon_gui/src/widgets/models/log_model.cpp, ecal/core/src/logging/ecal_log.cpp, ecal/core/src/logging/ecal_log_receiver.cpp, ecal/core/src/logging/ecal_log_receiver.h
Enable logging receiving in mon_gui.
Check size of rows before adding them in log_model.cpp . Without that size check, in debug the monitor crashed through an assert.
=> [mon_gui] Logging enable, crash fix

ecal/core/include/ecal/ecal_service_info.h, ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_descgate.h, ecal/core/src/service/ecal_service_client.cpp, ecal/core/src/service/ecal_service_client_v5_impl.cpp, ecal/core/src/service/ecal_service_server_impl.cpp, ecal/core/src/service/ecal_service_server_v5_impl.cpp, ecal/samples/cpp/services/latency_server/src/latency_server.cpp, ecal/samples/cpp/services/minimal_server/src/minimal_server.cpp, ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
Simplified
```cpp
using MethodInfoCallbackT = std::function<int(const SMethodInfo& method_info_, const std::string& request_, std::string& response_)>;
```
using new structure:
```cpp
struct SMethodInfo
{
std::string              method_name; //!< The name of the method.
SDataTypeInformation     req_type;    //!< The type of the method request.
SDataTypeInformation     resp_type;   //!< The type of the method response.
};
```
Removed code duplicates for `SDataTypeInformation` conversion in `CDescGate`.
=> [core] service client use datainfo (post fixes)

.github/workflows/build-windows.yml
GH Actions removed Python 3.7, so we remove the build for it.
=> [GH Action] Removed Python 3.7 build on windows [5.12]

.github/workflows/build-windows.yml
GH Actions removed Python 3.7, so we remove the build for it.
=> [GH Action] Removed Python 3.7 build on windows [5.13]

.github/workflows/documentation.yml, doc/rst/conf.py
[doc] Added support for multiversion documentation [5.12]
- [GH Action] Documentation is now published as artifact for easy preview
- [GH Action] Documentation is now deployed in a subdirectory
- [conf.py] Added version switcher to switch between different doc versions
=> [doc] Added support for multiversion documentation [5.12]

.github/workflows/documentation.yml, doc/rst/conf.py
[doc] Added support for multiversion documentation
- [GH Action] Documentation is now published as artifact for easy preview
- [GH Action] Documentation is now deployed in a subdirectory
- [conf.py] Added version switcher to switch between different doc versions
=> [doc] Added support for multiversion documentation [5.13]

.github/workflows/documentation.yml, doc/rst/conf.py
[doc] Added support for multiversion documentation
- [GH Action] Documentation is now published as artifact for easy preview
- [GH Action] Documentation is now deployed in a subdirectory
- [conf.py] Added version switcher to switch between different doc versions
=> [doc] Added support for multiversion documentation [master]

ecal/core/src/config/ecal_path_processing.cpp
3 warnings fixed for unreferenced parameters
=> [core] 3 minor warnings fixed

cmake/helper_functions/ecal_add_functions.cmake, cmake/helper_functions/ecal_install_functions.cmake, ecal/core/CMakeLists.txt, lang/c/core/CMakeLists.txt
Removes the old redundant `ecal_add_ecal_*` and `ecal_install_ecal_*` CMake functions
- Closes #549
=> [cmake] Remove old helper functions

ecal/core/include/ecal/ecal_callback.h, ecal/core/src/pubsub/ecal_publisher_impl.cpp, ecal/core/src/pubsub/ecal_publisher_impl.h, ecal/core/src/pubsub/ecal_subscriber_impl.cpp, ecal/core/src/pubsub/ecal_subscriber_impl.h, lang/c/core/src/ecal_publisher_cimpl.cpp, lang/c/core/src/ecal_subscriber_cimpl.cpp, lang/c/tests/core_test/src/core_test.cpp, lang/python/core/src/ecal_clang.cpp, serialization/protobuf/samples/pubsub/person_events_rec/src/person_events_rec.cpp, serialization/protobuf/samples/pubsub/person_events_snd/src/person_events_snd.cpp
- Removed `corrupted` and `update_connection` events from `eSubscriberEvent` and `ePublisherEvent` enums.
- Removed `clock` field from `SPubEventCallbackData` and `SSubEventCallbackData` structs.
- Added `FireDroppedEvent` function to `CSubscriberImpl`.
=> [core] event handling cleanup

ecal/core/include/ecal/ecal_registration.h, ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_descgate.h, ecal/core/src/registration/ecal_registration.cpp, ecal/samples/cpp/monitoring/monitoring_get_services/src/monitoring_get_services.cpp, ecal/tests/cpp/descgate_test/src/descgate_getentities.cpp, ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp, serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
GetServiceIDs -> GetServerIDs
GetServiceInfo -> GetServerInfo
We need to make the naming a bit more consistent: we haver Servers and Clients, for which we can retrieve information.
=> [core] Rename Methods regarding Server/Client:

lang/c/CMakeLists.txt
Make sure C tests are executed in github actions.
=> [cmake] add missing enable_testing call.

ecal/core/include/ecal/ecal_core.h, ecal/core/src/ecal.cpp, ecal/core/src/ecal_global_accessors.cpp, ecal/tests/cpp/core_test/CMakeLists.txt, ecal/tests/cpp/core_test/src/core_test.cpp, lang/c/core/include/ecal/cimpl/ecal_core_cimpl.h, lang/c/core/src/ecal_core_cimpl.cpp, lang/c/tests/core_test/CMakeLists.txt, lang/c/tests/core_test/src/core_test.cpp, lang/python/core/ecal/core/core.py, lang/python/core/src/ecal_clang.cpp, lang/python/core/src/ecal_clang.h, lang/python/core/src/ecal_wrap.cxx
Removed SetUnitName from API in C++, C and Python.
Changed UnitName generation in globals to use EcalUtils function.
=> [Process] Unit name handling

ecal/core/src/registration/shm/relocatable_circular_queue.h
- File: relocatable_circular_queue.h
- Type: Deprecated feature (-Wdeprecated-declarations)
- Details: Use of std::iterator is deprecated
=> [core] linux warning fix (RelocatableCircularQueue)

ecal/core/CMakeLists.txt, ecal/core/src/logging/ecal_log_provider.cpp, ecal/core/src/logging/ecal_log_receiver.cpp, ecal/core/src/pubsub/ecal_subscriber_impl.cpp, ecal/core/src/pubsub/ecal_subscriber_impl.h, ecal/core/src/service/ecal_service_server_impl.cpp, ecal/core/src/service/ecal_service_server_impl.h
- File: ecal_log_provider.cpp
- Type: Member initialization order (-Wreorder)
- Details: `m_attributes` is initialized after `m_created`.
- File: ecal_log_provider.cpp
- Type: Unused function (-Wunused-function)
- Details: The function `isDirectory` is defined but not used.
- File: ecal_log_receiver.cpp
- Type: Member initialization order (-Wreorder)
- Details: `m_attributes` is initialized after `m_created`.
- File: ecal_subscriber_impl.cpp
- Type: Member initialization order (-Wreorder)
- Details: `m_attributes` is initialized after `m_receive_time`.
- File: ecal_service_server_impl.cpp
- Type: Member initialization order (-Wreorder)
- Details: `m_created` is initialized after `m_service_name`.
=> [core] linux warning fixes

app/rec/rec_server_cli/src/commands/command.cpp, app/rec/rec_server_core/src/recorder/remote_recorder.cpp, app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.cpp, app/sys/sys_cli/src/commands/command.cpp, app/sys/sys_core/src/connection/remote_connection.cpp, ecal/core/include/ecal/service/types.h, ecal/core/include/ecal/v5/ecal_callback.h, ecal/core/src/v5/service/ecal_service_client_impl.cpp, ecal/samples/cpp/orchestration/orchestrator/src/orchestrator.cpp, ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp, ecal/tests/cpp/clientserver_v5_test/src/clientserver_test.cpp, lang/c/core/src/ecal_client_cimpl.cpp, lang/csharp/Continental.eCAL.Core/ecal_clr.cpp, lang/python/core/src/ecal_wrap.cxx, samples/cpp/services/ecalplayer_client/src/ecalplayer_client.cpp, samples/cpp/services/ecalplayer_gui_client/src/ecalplayer_gui_client.cpp, samples/cpp/services/ecalplayer_gui_client/src/ecalplayer_gui_client.h, samples/cpp/services/ecalsys_client/src/ecalsys_client.cpp, samples/cpp/services/rec_client_service_cli/src/ecalrecorder_client.cpp, samples/cpp/services/rec_client_service_gui/src/EcalrecGuiClient.cpp, samples/cpp/services/rec_client_service_gui/src/EcalrecGuiClient.h, samples/cpp/services/rec_server_service_gui/src/rec_server_service_gui.cpp, samples/cpp/services/rec_server_service_gui/src/rec_server_service_gui.h, serialization/protobuf/protobuf/include/ecal/msg/protobuf/client.h, serialization/protobuf/samples/services/math_client/src/math_client.cpp, serialization/protobuf/samples/services/ping_client/src/ping_client.cpp, serialization/protobuf/tests/clientserver_proto_test/src/clientserver_test_proto.cpp
Move deprecated type used for v5 Services to v5/ecal_callback.h
Fix minimal_client sample as it used incorrect values.
=> [core] move SServiceResponse (old API) to v5/ecal_callback.h

.github/workflows/build-windows.yml
We have not updated doxygen in a while and now have install problems.
=> Update doxygen to latest version.

ecal/core/include/ecal/registration.h, ecal/core/include/ecal/service/client.h, ecal/core/include/ecal/service/server.h, ecal/core/include/ecal/service/types.h, ecal/core/include/ecal/v5/ecal_client.h, ecal/core/src/ecal_descgate.cpp, ecal/core/src/ecal_descgate.h, ecal/core/src/registration/ecal_registration.cpp, ecal/core/src/serialization/ecal_struct_sample_common.h, ecal/core/src/serialization/ecal_struct_service.h, ecal/core/src/service/ecal_service_client.cpp, ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_client_impl.h, ecal/core/src/service/ecal_service_server.cpp, ecal/core/src/service/ecal_service_server_impl.cpp, ecal/core/src/service/ecal_service_server_impl.h, ecal/core/src/v5/service/ecal_service_client.cpp, ecal/core/src/v5/service/ecal_service_client_impl.cpp, ecal/core/src/v5/service/ecal_service_client_impl.h, ecal/core/src/v5/service/ecal_service_server_impl.cpp, ecal/core/src/v5/service/ecal_service_server_impl.h, ecal/samples/cpp/monitoring/monitoring_get_services/src/monitoring_get_services.cpp, ecal/samples/cpp/services/latency_server/src/latency_server.cpp, ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp, ecal/samples/cpp/services/minimal_server/src/minimal_server.cpp, ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp, ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp, ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp, serialization/protobuf/protobuf/include/ecal/msg/protobuf/client.h, serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
We want to further harmonize the Server API.
`SServiceId` is used as a Type to qualify either a Client or a Server. This is returned from the Registration functions, to see which server / clients are available.
About each server / client, the user can then retrieve information about the available service methods, including their meta information. (`ServiceMethodInfoSetT`)
=> Harmonize Server API

ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
Due to newly created event handles when resubscribing an existing topic, it is no longer possible to receive data via shared memory of the same process and topic on unix operating systems. This commit fixes the problem temporarily until an even more elegant solution is implemented.
=> [core] Fixed topic resubscription via shared memory

CMakeLists.txt
Adds a CMake option for including the C language bindings.
I know this might be contentious, as I've seen sentiment that you have too many CMake options already (personally, I think its ok and I hope you never look at VTK :laughing).
It feels like the C bindings are considered important, which is why I kept it default-on and marked as advanced to indicate it probably shouldn't be touched.  
The motivation is that, for example, I don't need it for my Go bindings so would like to be to exclude it from the container build (actually I see there's a `core_v5` target now which is a much larger unused resource for me...).
If the marked-as-advanced option is still too much, I ask at least for an undocumented regular variable.
-
=> [cmake] Optional C bindings

ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp
Will eventually track down and resolve an issue with subscribers connecting but not receiving data.
Current status: Test case refined, problem understood (see issue for details).
- Fixes #1914
=> [test: shm] Add testcase for fast reconnection

ecal/core/include/ecal/service/server.h, ecal/core/include/ecal/service/types.h, ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_server.cpp, ecal/core/src/service/ecal_service_server_impl.cpp, ecal/core/src/service/ecal_service_server_impl.h, ecal/core/src/v5/service/ecal_service_client_impl.cpp, ecal/core/src/v5/service/ecal_service_server_impl.cpp, ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp, ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp, ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp
A little bit of type renaming, and some comments added.
=> [core] service renaming and comments.

ecal/core/include/ecal/config/configuration.h
That string was probably added by accident
=> [core] removed "abc" as default ecal yaml file path.

ecal/core/include/ecal/registration.h, ecal/core/src/registration/ecal_registration.cpp, ecal/samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp, ecal/samples/cpp/monitoring/monitoring_get_services/src/monitoring_get_services.cpp, ecal/samples/cpp/monitoring/monitoring_get_topics/src/monitoring_get_topics.cpp, ecal/tests/cpp/registration_test_public/src/registration_getclients.cpp, ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp, ecal/tests/cpp/registration_test_public/src/registration_getservices.cpp, ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp, ecal/tests/cpp/registration_test_public/src/registration_gettopics.cpp, lang/python/core/src/ecal_clang.cpp, serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
Please see if you like the naming.
To be more in line with the functions for service / client, the function was split into two separate functions.
=> [core] split `GetTopicNames` into `GetPublishedTopicNames` and `GetSubscribedTopicNames`.

app/mon/mon_tui/src/model/monitor.hpp, ecal/core/include/ecal/types/monitoring.h, ecal/core/src/monitoring/ecal_monitoring_impl.cpp, ecal/core/src/pubsub/ecal_publisher_impl.cpp, ecal/core/src/pubsub/ecal_publisher_impl.h, ecal/core/src/pubsub/ecal_subscriber_impl.cpp, ecal/core/src/pubsub/ecal_subscriber_impl.h, ecal/core/src/serialization/ecal_serialize_common.cpp, ecal/core/src/serialization/ecal_serialize_monitoring.cpp, ecal/core/src/serialization/ecal_serialize_sample_registration.cpp, ecal/core/src/serialization/ecal_struct_sample_registration.h, ecal/core/src/serialization/nanopb/ecal/core/pb/topic.npb.c, ecal/core/src/serialization/nanopb/ecal/core/pb/topic.npb.h, ecal/core_pb/src/ecal/core/pb/topic.proto, ecal/tests/cpp/serialization_test/src/monitoring_compare.cpp
Remove user defined attributes for topics. This includes also removing any functionality in the publisher/subscriber v5 implementation, where these interface calls still exist. They will now log a warning, that this has no impact anymore.
In v6 this already is phased out.
=> [Topic] Remove remove user defined attributes for topics

ecal/core/include/ecal/service/client.h, ecal/core/include/ecal/service/client_instance.h, ecal/core/src/service/ecal_service_client.cpp, ecal/core/src/service/ecal_service_client_impl.cpp, ecal/core/src/service/ecal_service_client_impl.h, ecal/core/src/service/ecal_service_client_instance.cpp, ecal/core/src/v5/service/ecal_service_client_impl.cpp, ecal/samples/cpp/services/latency_client/src/latency_client.cpp, ecal/samples/cpp/services/minimal_client/src/minimal_client.cpp, ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp, serialization/protobuf/samples/services/ping_client_dyn/src/ping_client_dyn.cpp
As the title says. This will simplify the client method call API function usage a remarkable.
=> [core] introduced default timeout parameter for client service method calls

doc/rst/development/building_ecal_from_source.rst, doc/rst/development/ecal_cmake_options.rst
Minor fix:
1. Whitespace alignment in cmake option documentation
2. Build documenation for python wheel updated
=> [doc] blanks and python build

contrib/mma/src/zombie_instance_killer.cpp
This PR sets back the naming in the zombie_killer implementation from the mma application. As the variable naming was the same as a parameter name, the application tried to close all running processes.
=> [mma] Hotfix: mma kills all processs

CMakePresets.json
Removes all the explicit CMake options to disable building from the submodules. With the submodule dependency provider dependencies are only pulled into the build when needed and are excluded from all anyway. They were only disabling unused dependencies.
This fixes usage of the presets on Windows where curl and hdf5 weren't being set (was relying on logic that got deleted in the transition)
- Me trying to build on Windows with the preset and it not working...
=> fix[cmake]: Remove thirdparty build options from presets

ecal/core/include/ecal/config.h
The implementation was removed in a previous PR.
Sorry, this was a clear oversight on my side, the declaration should have been removed earlier.
=> [core] remove function declaration without implementation

thirdparty/curl/build-curl.cmake, thirdparty/yaml-cpp/build-yaml-cpp.cmake
Disables many curl targets from being generated and places missed thirdparty targets (just curl and yaml-cpp) into the correct IDE folder. (`CMAKE_FOLDER sets the default value for the `FOLDER` property)
- Visual studio CMake targets list being filled with junk from curl.
=> [cmake]: Disable unwanted curl options and put missed targets in correct IDE folder

doc/rst/conf.py
Fixed doc build by removing leading "v." from the version number and parsing it as partial version.
=> [Doc] Fixed parsing of ecal_doc_version number

doc/rst/conf.py
The python package cannot handle "short" version numbers (like 5.13) properly when comparing versions.
=> [Doc] Fixed compile issue when compiling for the latest stable version

.github/workflows/build-windows.yml, lib/CustomQt/CMakeLists.txt, lib/EcalParser/CMakeLists.txt, lib/QEcalParser/CMakeLists.txt, lib/ThreadingUtils/CMakeLists.txt, lib/ecal_utils/CMakeLists.txt, thirdparty/tcp_pubsub/build-tcp_pubsub.cmake
Fixes the build such that the installed result is usable when eCAL is built with `BUILD_SHARED_LIBS=ON`.
- `tcp_pubsub` submodule is now always built statically as it is a strictly internal dependency.
- `ecal-utils` may now be static or shared depending on `BUILD_SHARED_LIBS`
- It was required to be installed as it was used by other static/shared libraries
- There was no particular reason for it to always be static so now it aligns with the other non-fixed libraries
- `EcalParser, QEcalParser, CustomQt, and ThreadingUtils` are now **always static** because they were implementation details for applications and application plugins and were not required to be installed.
Fixes #2014
=> [cmake]: Fix usage after install when built with `BUILD_SHARED_LIBS=ON`

ecal/core/include/ecal/util.h, ecal/core/src/config/ecal_path_processing.cpp, ecal/core/src/config/ecal_path_processing.h, ecal/tests/cpp/config_test/src/path_processing_test.cpp
eCALLogDirImpl returned the standard paths of the environment variables set, as also the default path where the ecal.yaml file was loaded from. Now with this change, there is a check for the case of ECAL_DATA directory and the loaded ecal.yaml file, if a subfolder named "logs" exists. If so, take this as the logging directory.
By default the "logs" directory will be created with ecal_generate_config(.exe), so its valid to write into that path.
=> [logging] eCALLogDir returns now subfolder "logs" in special cases

ecal/core/src/io/shm/ecal_memfile_sync.cpp, ecal/core/src/readwrite/shm/ecal_writer_shm.cpp
When having acknowledge enabled the publisher runs into the acknowledge timeout after a subscriber stopped. The problem was, that after the subscriber got restarted, the publisher runs again into the acknowledge timeout for each Send, even if the "new old" subscriber is working fine.
With this fix, the behaviour of acknowledgement is as expected. After reconnecting the subscriber, the publisher does not run into the timeout anymore.
=> [core] Fixed acknowledge bug for multiple processes

ecal/core/CMakeLists.txt
Explicitly require C++ 14 Standard for core compilation.
=> [cmake] Require CXX14 for core compilation.

app/play/play_core/include/ecal_play_logger.h, app/rec/rec_client_core/include/rec_client_core/ecal_rec_logger.h, app/sys/sys_client_core/include/sys_client_core/ecal_sys_client_logger.h, app/sys/sys_core/CMakeLists.txt, app/sys/sys_core/include/ecalsys/ecal_sys_logger.h
Previous implementation of GeteCALLogDir returned path with path separator at the end. Now it does not, so additional handling is needed.
=> [app] Path separator for log path.

app/rec/rec_client_core/src/job/ftp_upload_thread.cpp, app/rec/rec_client_core/src/job/ftp_upload_thread.h, app/rec/rec_client_core/src/job/record_job.cpp
Added mDNS support for FTP Uploads. As CURL does not support backup hostnames, the hostname is probed beforehand to check which variant can be resolved.
- For plain hostnames, eCAL rec will probe [`Hostname`, `Hostname.local`] in that order
- The variant that can be resolved to an IPv4 address is preferred
- `Hostname` is preferred over `Hostname.local`
- Hostnames that already contain a `.` are used as-is. No .local is added and therefore, the probing step is skipped
- If the Hostname is an IPv4/v6 address, the probing step is skipped and the address is used as-is
- Fixes #1531
=> [Rec] Added mDNS support for FTP Uploads

README.md, doc/rst/configuration/src/publisher_config/main.cpp, doc/rst/getting_started/src/hello_world/hello_world_rec/main.cpp, doc/rst/getting_started/src/hello_world/hello_world_snd/main.cpp, serialization/flatbuffers/flatbuffers/CMakeLists.txt, serialization/protobuf/protobuf/CMakeLists.txt, serialization/string/string/CMakeLists.txt
The new serialization pub/sub need also the serializer.h, which was not provided in the installation before.
In addition, samples in doc are fixed to the new implementation.
=> [core] Provide serializer.h for installation

app/mon/mon_plugins/capnproto_reflection/src/plugin_widget.cpp, app/mon/mon_plugins/protobuf_reflection/src/plugin_widget.cpp, app/mon/mon_plugins/signals_plotting/src/plugin_widget.cpp, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/core/src/pubsub/ecal_subscriber_impl.h, serialization/common/common/include/ecal/msg/subscriber.h, serialization/protobuf/tests/pubsub_proto_test/src/proto_subscriber_test.cpp
Implement `CMessageSubscriber` callbacks with lambdas instead of member functions, which greatly simplifies handling in case of moving.
`SetReceiveCallback` function now takes both data and error callback, so that these functions are available atomically.
With the previous implementation, it's easily possible to deadlock eCAL when simulatenously setting callbacks and receiving data.
This is no longer the case with the proposed implementation, as the `CMessageSubscriber` no longer contains any locks.
At the same time, it fixes the move constructor / assignment of the `CMessageSubscriber`.
=> [msg] Avoid deadlocking with CMessageSubscriber

contrib/ecalhdf5/src/hdf5_helper.cpp, contrib/ecalhdf5/src/hdf5_helper.h, tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
Currently, when the user stores empty strings for any field in DataTypeInformation in the measurement, they are read back from hdf5 as "\0". 
This is problematic, as it does not allow to properly compare the DatatypeInformation for usecases like determining if serialization will work successfully.
This PR fixes this behavior.
=> [bugfix] Allow to store empty strings for DataTypeInformation in measurement

cmake/helper_functions/ecal_helper_functions.cmake, doc/samples/cpp/configuration/hello_config/CMakeLists.txt, doc/samples/cpp/configuration/publisher_config/CMakeLists.txt, doc/samples/cpp/protobuf/hello_world_rec/CMakeLists.txt, doc/samples/cpp/protobuf/hello_world_snd/CMakeLists.txt, doc/samples/cpp/string/hello_world_rec/CMakeLists.txt, doc/samples/cpp/string/hello_world_snd/CMakeLists.txt, thirdparty/protobuf/build-protobuf.cmake, thirdparty/termcolor/build-termcolor.cmake, thirdparty/yaml-cpp/build-yaml-cpp.cmake
Allow eCAL to successfully build with CMake 4.0
closes #2041
=> [bugfix] Allow compatibility with CMake 4.0

.github/workflows/build-macos.yml, .github/workflows/build-ubuntu.yml, .github/workflows/build-windows.yml, .github/workflows/build_wheels.yml, contrib/ecaltime/linuxptp/CMakeLists.txt, ecal/tests/cpp/pubsub_test/src/pubsub_test_shm.cpp, thirdparty/yaml-cpp/compatibility-yaml-cpp.cmake
Aims to speed up CI times in two ways:
1. By doing shallow clones of the submodules and main repo
2. By building less vendored code, instead using system packages were suitable.
Effect:
This speeds up CI runs by up to roughly 2 minutes (there is a _lot_ of variance). Less than I was hoping, but is ~10% in the best case.
Detailed changes:
- The eCAL repo is now checkedout using `--filter=tree:0`. This is like a less aggressive shallow clone; the commits are fetched but their contents are fetched on-demand. This lets the tag-based versioning to continue to work but minimises the data transferred.
- More unneeded submodules are de-initialized.
- Ubuntu:
- package lists are now split into common and specific to reduce repetition.
- `spdlog` and `gmock` have been added to the installed …
=> CI: Use shallow submodules and more system packages

ecal/core/src/io/mtx/linux/ecal_named_mutex_impl.cpp, ecal/core/src/io/mtx/linux/ecal_named_mutex_impl.h, ecal/core/src/io/mtx/linux/ecal_named_mutex_robust_clocklock_impl.cpp, ecal/core/src/io/mtx/linux/ecal_named_mutex_robust_clocklock_impl.h, ecal/tests/cpp/registration_test_public/src/registration_getpublisherids.cpp, ecal/tests/cpp/registration_test_public/src/registration_getsubscriberids.cpp
Fixes two instances of ODR violations:
1. From `::named_mutex`
2. From test fixtures
- 
Closes #2111
=> [fix] Mutex and test ODR violations

.github/workflows/build-windows.yml, cpack/innosetup/ecal_setup.iss.in
=> [setup] Set eCAL Launcher to be linked on the userdesktop instead of common desktop

ecal/core/include/ecal/types/custom_data_types.h, ecal/core/src/types/ecal_custom_data_types.cpp, ecal/tests/cpp/config_test/src/config_test.cpp
Replaces use of `std::regex` to validate ipv4 address strings with asio.
Does technically remove support of expressing IPv4 addresses in hex but I suspect that didn't work anyway (as at least one usage path leads into an `asio::ip::make_address` call).
Tidies up some whitespace/headers and clang-tidy reports as well.
Closes #2124
=> fix: Use asio to validate ipv4 address strings instead of regex

.github/actions/ccache-prepare/action.yml, .github/actions/ccache-save/action.yml, .github/workflows/build-macos.yml, .github/workflows/build-ubuntu.yml, doc/CMakeLists.txt
Integrates ccache into the MacOS workflow:
- The sphinx documentation is now built with multiple threads (have not measured the impact)
- The ccache steps have been extracted into composite actions to prevent duplication
- Building documentation on MacOS was disabled as it was not used and the Ubuntu workflow already builds it to ensure validity.
- Follow on from #2108
=> [CI] Use ccache on MacOS

.github/workflows/build-windows.yml, cpack/innosetup/ecal_setup.iss.in, doc/CMakeLists.txt, lang/csharp/CMakeLists.txt, thirdparty/udpcap/build-udpcap.cmake
Updates the Windows workflow to make use of ccache. In total this brings a CI run down from ~40 minutes to ~20 minutes. The largest gain is speeding up the release build 10x from 20 minutes to **2**. The largest steps are the release testing, debug (SDK) build (because ccache does not work with /Zi), and packaging. 
This PR is also ordered into logical commits (with commit messages).
- `install-qt-action` updated to v4
- `setup-python` was enabled to allow it pick an appropriate python version for us (currently 3.10)
- The qt version was relaxed to select the most recent 6.6 patch version
- The `archives` option is set to minimize the qt install
- Caching is now enabled
- Initializing and updating of the submodules combined to one line
- (The windows build uses all submodules so the …
=> [CI] Use ccache on Windows

ecal/core/src/io/udp/ecal_udp_sample_receiver_asio.cpp, ecal/core/src/io/udp/ecal_udp_sample_receiver_asio.h, ecal/core/src/io/udp/ecal_udp_sample_receiver_npcap.cpp, ecal/core/src/io/udp/ecal_udp_sample_receiver_npcap.h
This is a manual cherry pick as replacement for #2162
Original PR was #2160
=> [CP #2160 > support/v6.0] [Submodules] Updated asio to 1.34.2 and fixed compatibility of udp samples with asio >= 1.33

.github/workflows/build-macos.yml, .github/workflows/build-ubuntu.yml, .github/workflows/build-windows.yml, .github/workflows/build_wheels.yml
The old shallow checkout prevented checking out the QWT commit, as there was a newer commit on the branch. The issue was introduced with https://github.com/eclipse-ecal/ecal/pull/2108
=> [GH Actions] Fixed checkout of submodules

app/mon/mon_gui/CMakeLists.txt, app/play/play_gui/CMakeLists.txt, app/rec/rec_gui/CMakeLists.txt
Previously while building eCAL with Qt5 the Qt5WinExtras was missing in the deployment. This is now fixed, that the correct dependencies of eCAL Recorder and eCAL Player get installed.
=> [apps] Fix Qt5WinExtras deployment

README.md
There was another link to ecal-rs that is now fixed to rustecal.
=> fixed another rust link

app/mon/mon_gui/CMakeLists.txt, app/mon/mon_gui/src/custom_types/byte_size.cpp, app/mon/mon_gui/src/custom_types/byte_size.h, app/mon/mon_gui/src/util.h, app/mon/mon_gui/src/widgets/ecalmon_tree_widget/host_widget.cpp, app/mon/mon_gui/src/widgets/ecalmon_tree_widget/topic_widget.cpp, app/mon/mon_gui/src/widgets/models/host_tree_item.cpp, app/mon/mon_gui/src/widgets/models/host_tree_model.h, app/mon/mon_gui/src/widgets/models/topic_tree_item.cpp, app/mon/mon_gui/src/widgets/models/topic_tree_model.h
In eCAL Monitor GUI, it's hard to properly understand the size of sent data when it gets bigger.
This PR will display data rates in the format of 10.0B, 1.34 KiB, 100.00 MiB or 1.49 GiB.
=> [ecal monitor] Use Delegates to properly display byte sizes for transmitted data.

lang/c/tests/pubsub_test/src/pubsub_test.cpp, lang/c/tests/services_test/src/services_test.cpp
Fixes unused argument warnings
=> [fix] Remove some warnings in C samples.

contrib/ecalhdf5/src/eh5_meas_api_v3.cpp, contrib/ecalhdf5/src/eh5_meas_dir.cpp, contrib/ecalhdf5/src/eh5_meas_dir.h, contrib/ecalhdf5/src/eh5_meas_file_v1.cpp, contrib/ecalhdf5/src/eh5_meas_file_v1.h, contrib/ecalhdf5/src/eh5_meas_file_v2.cpp, contrib/ecalhdf5/src/eh5_meas_file_v2.h, contrib/ecalhdf5/src/eh5_meas_file_v3.cpp, contrib/ecalhdf5/src/eh5_meas_file_v3.h, contrib/ecalhdf5/src/eh5_meas_file_v4.cpp, contrib/ecalhdf5/src/eh5_meas_file_v4.h, contrib/ecalhdf5/src/eh5_meas_file_v5.cpp, contrib/ecalhdf5/src/eh5_meas_file_v5.h, contrib/ecalhdf5/src/eh5_meas_file_v6.cpp, contrib/ecalhdf5/src/eh5_meas_file_v6.h, contrib/ecalhdf5/src/eh5_meas_file_writer_v5.cpp, contrib/ecalhdf5/src/eh5_meas_file_writer_v5.h, contrib/ecalhdf5/src/eh5_meas_file_writer_v6.cpp, contrib/ecalhdf5/src/eh5_meas_file_writer_v6.h, contrib/ecalhdf5/src/eh5_meas_impl.h, contrib/ecalhdf5/src/escape.cpp, contrib/ecalhdf5/src/escape.h, tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
- Adds new testcase
- Introduces strong type so that it is clear where and where not channel names have been escaped.
=> [ecalhdf5] Fix bug of double escaping channel names.

app/sys/sys_cli/src/ecalsys_service.cpp, app/sys/sys_cli/src/ecalsys_util.cpp, app/sys/sys_core/src/ecal_sys.cpp, app/sys/sys_core/src/ecal_sys_monitor.cpp, app/sys/sys_core/src/taskaction_threads/start_task_list_thread.cpp, app/sys/sys_core/src/taskaction_threads/stop_task_list_thread.cpp, app/sys/sys_core/src/taskaction_threads/update_from_cloud_task_list_thread.cpp, app/sys/sys_gui/src/ecalsys_service.cpp, app/sys/sys_gui/src/widgets/groupwidget/group_widget.cpp, app/sys/sys_gui/src/widgets/taskwidget/task_widget.cpp, app/sys/sys_gui/src/widgets/taskwidget/task_widget.ui, app/sys/sys_gui/src/widgets/treemodels/task_tree_item.cpp
The Hostname can now be programmed with the Ecal Parser syntax known from the Executable path, arguments, etc.
Limitation: TARGET functions are never evaluated, as the Hostname determines the target and cannot be evaluated *on* it for obvious reasons. Thus, something like `$TARGET{ENV my_env}` would never be evaluated.
Fixes #1940
=> [Sys] Added Ecal Parser Evaluation to target Hostname field

lang/python/core/src/ecal_wrap.cxx
Missing `Py_DECREF` caused memory to increase when writing Python servers. See  #2270
=> [python] fix memory leaks by adding missing Py_DECREF.

app/mon/mon_tui/src/tui/ftxui_version_compatibility.hpp, app/mon/mon_tui/src/tui/view/command_line.hpp, app/mon/mon_tui/src/tui/view/component/data_table.hpp, app/mon/mon_tui/src/tui/view/component/decorator.hpp, app/mon/mon_tui/src/tui/view/component/focus_manager.hpp, app/mon/mon_tui/src/tui/view/component/scroller.hpp, app/mon/mon_tui/src/tui/view/component/tree.hpp, app/mon/mon_tui/src/tui/view/help.hpp, app/mon/mon_tui/src/tui/view/log_details.hpp, app/mon/mon_tui/src/tui/view/message_visualization/messaage_vizualization.hpp, app/mon/mon_tui/src/tui/view/message_visualization/proto.hpp, app/mon/mon_tui/src/tui/view/process_details.hpp, app/mon/mon_tui/src/tui/view/service_details.hpp, app/mon/mon_tui/src/tui/view/shell.hpp, app/mon/mon_tui/src/tui/view/system_information.hpp, app/mon/mon_tui/src/tui/view/table.hpp, app/mon/mon_tui/src/tui/view/topic_details.hpp
ftxui has released a new major version.
This branch tries to ensure compatibility with the new release and all older releases.
Todo: It seems that 6.0.0 breaks the ability to select an item from the list of topics. This needs to be investigated.
(background ftxui 6.0.0, foreground ftxui 5.0.0 - the elements are no longer selectable).
(This PR does *not* update the submodule, so the current build is still using 5.0.0)
@brakmic-aleksandar There is no chance that you might quickly look into this? I am not quite sure where to start.
=> [dependencies] Add support for ftxui 6.0.0.

doc/extensions/generate_release_documentation.py, doc/extensions/resource/release_page.rst.jinja
- The Installers now properly state the CPU architecture (everything was flagged x64 before)
- PyPy bindings are now displayed, if they are available.
=> [Doc] Fixed release page (cpu arch and pypy bindings)

app/mon/mon_plugins/monitor_tree_view/CMakeLists.txt, app/play/play_core/CMakeLists.txt, app/rec/rec_client_core/CMakeLists.txt, app/rec/rec_server_core/CMakeLists.txt, app/sys/sys_client_core/CMakeLists.txt, app/sys/sys_core/CMakeLists.txt
Made these changes a while ago but forgot to get them upstreamed :grimacing: 
The apps have some common functionality libraries that are not installed and only used to support the apps.
As such, if CMake `BUILD_SHARED_LIBS` is on (as is typical of Linux packaging builds) these common/helper libraries are built as shared libraries but don't get installed and the apps can't run (as the libraries are missing).
To fix, I simply made them all static so they don't need to be installed, as they don't appear to be meant for external use.
-
=> [build] Static app helper libraries

ecal/samples/cpp/services/mirror_client/CMakeLists.txt, ecal/samples/cpp/services/mirror_server/CMakeLists.txt
HDF5 may provide a CMake target with the name `mirror_server` as they have an executable of the same name.
If you try to configure eCAL with such an HDF5 package, HDF5 support enabled, and the `mirror_server` sample enabled it will fail as the target will already exist.
To get around this I simply appended `_cpp` to the problematic samples (as there is also `mirror_server_c`)
Eg: The Arch Linux HDF5 package has `mirror_server` included: https://archlinux.org/packages/extra/x86_64/hdf5/
-
=> [build] Avoid mirror_server name clash with HDF5

.github/workflows/test-suite-trigger.yml
This PR introduces a new GitHub Actions workflow (`.github/workflows/trigger-tests.yml`) that automatically triggers the `ecal-test-suite` whenever a pull request or push is made to the `master` branch of this repository.
The workflow uses a `repository_dispatch` event to trigger a remote test run and links the corresponding test results back to the related commit or pull request.
- Trigger on:
- Push to `master`
- Pull request to `master`
- Manual `workflow_dispatch`
- Sends a `repository_dispatch` with:
- Commit SHA
- Originating repository
- Link to the current workflow run
- Points to the official test suite repository:
https://github.com/eclipse-ecal/ecal-test-suite
- Outputs links to:
- Test reports: https://eclipse-ecal.github.io/ecal-test-suite/
This enables automated integration …
=> Add GitHub Action to Trigger Test Suite (ecal-test-suite)

app/mon/mon_gui/CMakeLists.txt, app/play/play_gui/CMakeLists.txt, app/rec/rec_gui/CMakeLists.txt, app/sys/sys_gui/CMakeLists.txt, app/util/launcher/CMakeLists.txt, samples/cpp/services/ecalplayer_gui_client/CMakeLists.txt, samples/cpp/services/rec_client_service_gui/CMakeLists.txt, samples/cpp/services/rec_server_service_gui/CMakeLists.txt, thirdparty/cmakefunctions/cmake_functions/cmake_functions.cmake, thirdparty/cmakefunctions/cmake_functions/qt/exclusive_command.cmake, thirdparty/cmakefunctions/cmake_functions/qt/exclusive_command.ps1, thirdparty/qwt/CMakeLists.txt
This prevents the build to fail by multiple windeployqt instances trying to write the same dlls at the same time.
=> [CMake / Qt] Windeployqt calls are now waiting for each other

app/mon/mon_tui/src/model/data/topic.hpp, app/mon/mon_tui/src/model/monitor.hpp, app/mon/mon_tui/src/tui/viewmodel/topics.hpp
- Change frequency calcualation to Hz (before mHz)
- Rename member variable accordingly to mHz
- Added "(Hz)" to header information
- Fixes #2259
=> [ecal_mon_tui] Set frequency calculation to Hz

ecal/core/include/ecal/v5/ecal_publisher.h, ecal/core/include/ecal/v5/ecal_subscriber.h, ecal/core/src/pubsub/ecal_publisher_impl.cpp, ecal/core/src/pubsub/ecal_publisher_impl.h, ecal/core/src/pubsub/ecal_subscriber.cpp, ecal/core/src/pubsub/ecal_subscriber_impl.cpp, ecal/core/src/pubsub/ecal_subscriber_impl.h, ecal/core/src/v5/pubsub/ecal_publisher.cpp, ecal/core/src/v5/pubsub/ecal_subscriber.cpp
The Publisher Implementation and Subscriber Implementation contained callback maps for both v6 and v5 style callbacks.
This PR removes the v5 style callback maps and moves them into the actual v5 implementations, thus cleaning up the core.
This implementation is used ONLY for the legacy Python bindings, so we should think about when we can remove those safely.
=> Move v5 callback maps to v5 implementation
