- README.md
> readme: correct minor typo.

- .github/workflows/build-ubuntu-iceoryx.yml
- ecal/core/src/readwrite/ecal_reader_iceoryx.cpp
- ecal/core/src/readwrite/ecal_writer_iceoryx.cpp
build against the new iceoryx 0.17.0 version
> update iceoryx build to 0.17.0

- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu-iceoryx.yml
- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows.yml
Ini files for ecal and iceoryx needed to run tests and RouDi copied to default target folders
> Copy ini files

- ecal/core/src/readwrite/ecal_reader.cpp
- ecal/core/src/readwrite/ecal_reader_iceoryx.cpp
- ecal/core/src/readwrite/ecal_reader_iceoryx.h
- ecal/core/src/readwrite/ecal_reader_inproc.cpp
- ecal/core/src/readwrite/ecal_reader_inproc.h
- ecal/core/src/readwrite/ecal_reader_layer.h
- ecal/core/src/readwrite/ecal_reader_shm.cpp
- ecal/core/src/readwrite/ecal_reader_shm.h
- ecal/core/src/readwrite/ecal_reader_udp_mc.h
that will fix the issue with two susbscriptions with the same topic name for iceoryx layer (additional fix for #92)
> iceoryx datareader map now based on topic id

- .gitmodules
Removed official hdf5 git repo, as they decided to password-protect it
> Hdf5 mirror

- app/play/play_cli/src/ecal_play_cli.cpp
- app/play/play_core/src/ecal_play.cpp
- app/play/play_core/src/play_thread.cpp
- app/play/play_gui/src/q_ecal_play.cpp
- app/rec/rec_client_cli/src/ecal_rec_cli.cpp
- app/rec/rec_client_core/src/addons/addon_manager.cpp
- app/rec/rec_gui/src/qecalrec.cpp
- app/rec/rec_gui/src/widgets/recordermanager_widget/recorder_model.cpp
- app/rec/rec_server_core/src/rec_server_impl.cpp
- app/rec/rec_server_core/src/recorder/remote_recorder.cpp
- ecal/core/src/ecal_globals.cpp
- ecal/core/src/ecal_servgate.cpp
- ecal/core/src/ecal_util.cpp
- ecal/core/src/pubsub/ecal_pubgate.cpp
- ecal/core/src/pubsub/ecal_subgate.cpp
- ecal/core/src/readwrite/ecal_reader.cpp
- ecal/core/src/readwrite/ecal_writer.cpp
- ecal/core/src/readwrite/ecal_writer_shm.cpp
- lib/Udpcap/src/udpcap_socket_private.cpp
* std::list -> std::vector (if possible)
* new -> std::make_shared / std::make_unique
> different static code analysis fixes

- cpack/innosetup/ecal_setup.iss.in
- ecal/core/cfg/CMakeLists.txt
- ecal/core/src/ecal_config.cpp
Accidentally fixed on the ecalsys_cli branch ;)
> Improved ecal.ini path on Windows

- .gitignore
- CMakeLists.txt
set CMake default options for windows and linux platform (curl, hdf5, protobuf)
> add Clion artefacts to .gitignore

- lib/Udpcap/include/udpcap/npcap_helpers.h
- lib/Udpcap/src/npcap_helpers.cpp
Added support for modern NPCAP that has been installed without the legacy loopback Adapter.
> Loopback-less NPCAP

- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu-18.yml
- .github/workflows/build-ubuntu-20.yml
- .github/workflows/build-ubuntu-iceoryx.yml
- .github/workflows/build-windows.yml
- lang/python/CMakeLists.txt
- lang/python/setup.py.in
Python binding is now packed as .whl
On Windows the python binding is compiled for multiple python Versions
> Python binding as whl

- ecal/core/src/readwrite/ecal_reader.cpp
- ecal/core/src/readwrite/ecal_writer.cpp
crash appears for time deltas < 1 ms
> possible division by zero fixed

- app/sys/sys_core/src/config/esys_cfg_parser.cpp
Removed that horrible legacy code that tried to read the Window layout from the ecalsys file. It is not used any more, but caused issues.
> Removed legacy code

- doc/rst/advanced/transport_layers.rst
> Fixed typo

- app/rec/rec_server_core/src/rec_server_impl.cpp
> eCAl Rec now recursively creates upload paths

- app/rec/rec_gui/src/widgets/recording_history_widget/job_history_jobitem.cpp
- app/rec/rec_gui/src/widgets/recording_history_widget/job_history_jobitem.h
- app/rec/rec_gui/src/widgets/recording_history_widget/recording_history_widget.cpp
> Added "Explore to..." context menu in Rec GUI History

- app/play/play_core/src/ecal_play.cpp
> eCAL Play now supports channel mappings with spaces

- app/sys/sys_client_core/src/task.cpp
Sys now properly handles relative paths as relative to the working directory
> Sys relative paths

- CMakeLists.txt
- ecal/core/CMakeLists.txt
- ecal/core/include/ecal/msg/publisher.h
- ecal/core/src/ecal_descgate.cpp
- ecal/core/src/ecal_expmap.h
- ecal/core/src/ecal_servgate.cpp
- ecal/core/src/pubsub/ecal_subgate.cpp
- ecal/core/src/readwrite/ecal_reader_iceoryx.cpp
- ecal/core/src/readwrite/ecal_reader_iceoryx.h
- ecal/core/src/readwrite/ecal_reader_layer.h
- ecal/core/src/readwrite/ecal_reader_udp_mc.h
- ecal/core/src/readwrite/ecal_writer_iceoryx.cpp
* iceoryx layer (current master) working on windows platform now (needs latest VS2019 16.10.x version to build iceoryx itself !)
* minor PVS static analysis fixes on ecal core
> iceoryx support for windows platform

- ecal/core/src/readwrite/ecal_reader_iceoryx.cpp
- ecal/core/src/readwrite/ecal_writer_iceoryx.cpp
release iceoryx payload
detach listener
> iceoryx-layer-leaks

- .github/workflows/ecal-fat-source.yml
Fixes #335 for future releases
> GH Actions: Action that creates fat source packages

- cmake/eCALConfig.cmake.in
Removed fine_package hdf5 in the main eCAlConfig.cmake
> Fixed compile-against-ecal issue

- cmake/Modules/Findasio.cmake
Fixed warning in custom Findasio.cmake
> Fixed warning in custom Findasio.cmake

- app/rec/rec_client_core/src/job/ftp_upload_thread.cpp
- app/rec/rec_server_core/src/config/config_v2to3.cpp
Bugfix for Build with VS2019
-
-
-
> Add missing std includes for VS2019

- ecal/core/src/service/ecal_service_client_impl.cpp
- ecal/core/src/service/ecal_service_client_impl.h
When client calls service which doesn't exist/isn't initiated yet it fails silently.
Issue Number: #371
Client will let user know that it couldn't connect to service through callback.
> Added callback calls on CallAsync service errors

- doc/rst/advanced/threading_model.rst
- doc/rst/index.rst
> threading model roughly described (issue #370)

- ecal/core/src/ecal_thread.cpp
Ressource leak in eCAL thread handling.
Issue Number: PR #340
Leak fixed.
> fix leak (PR #340)

- app/mon/mon_gui/src/plugin/plugin_manager.cpp
- ecal/core/src/ecal_timegate.cpp
- ecal/core/src/getenvvar.h
fixed time plugin and monitor plugin search path priority. introduced ECAL_TIME_PLUGIN_PATH environment variable.
-
-
-
> fixed time plugin and monitor plugin search path priority

- app/mon/mon_gui/src/widgets/ecalmon_tree_widget/topic_widget.cpp
- app/sys/sys_gui/src/widgets/import_from_cloud_widget/import_from_cloud_widget.cpp
- ecal/core/include/ecal/ecal_util.h
Issue Number: Additional cleanup for #362
> deprecated use of GeteCALDefaultIniFile removed

- app/play/play_gui/src/q_ecal_play.cpp
> Player: Fixed bug when loading deleted measurement

- ecal/core/include/ecal/msg/protobuf/dynamic_subscriber.h
> Dynamic Subscriber - check for default (empty) proto

- .github/workflows/build-windows.yml
> Uninstall chocolatey

- ecal/core/include/ecal/ecal_publisher.h
- ecal/core/include/ecal/ecal_subscriber.h
- ecal/core/src/pubsub/ecal_publisher.cpp
- ecal/core/src/pubsub/ecal_subscriber.cpp
- ecal/core/src/readwrite/ecal_reader.h
- ecal/core/src/readwrite/ecal_writer.h
There aren't api functions that provide number of subscribers for given publisher and number of publishers for given subscriber.
Two new API functions were added CSubscriber::GetPublisherCount and CPublisher::GetSubscriberCount which add aforementioned functionality.
> Added subscriber count and publisher count to Subscriber and Publisher

- doc/rst/advanced/measurement_format.rst
- doc/rst/index.rst
> Add first draft of measurement format documentation.

- doc/rst/configuration/options.rst
> [doc] Fixed path to ecal.ini

- lib/Udpcap/src/npcap_helpers.cpp
> Fixed crash when NPCAP is not installed

- ecal/core/src/ecal_config.cpp
> [Bugfix] Fallback for ecal config path on linux

- app/rec/rec_server_cli/src/ecal_rec_server_cli.cpp
"ecal_rec -r" will properly block now, until the recording finishes
Blocking can be stopped by sending a signal (SIGINT / SIGTERM / CTRL+C / etc.) or by stopping the recording from an external application via the eCAL Service.
Fixes #410
> "ecal_rec -r" will properly block now, until the recording finishes

- thirdparty/cmake_functions/cmake_functions.cmake
> Removed windeployqt from cmakefunctions for non-windows installs

- ecal/core/src/service/ecal_tcpclient.cpp
- ecal/core/src/service/ecal_tcpclient.h
Async write sometimes fails because request data provided to it can get deleted during write operation.
Make writes synchronous (reading/waiting for response is still async) to make sure request data stays intact, this way we won't have to break API.
> Server requests for async requests will be synchronous

- README.md
> Agtonomy Trellis project added to Readme.md

- lang/python/ecalhdf5/ecal/measurement/measurement.py
Channel class throws a non meaningful error message when trying to construct instance if channel name does not exist.
**Thanks Jan Kissner for the hint.**
- Channel class will raise a sensible error message if channel name does not exist in the measurement
> Fixed channel class in measurement.py to raise a sensible error

- cpack/innosetup/ecal_setup.iss.in
> [Setup]: Associate .ecalmeas files with eCAL Player on Windows

- app/rec/rec_client_core/CMakeLists.txt
- app/rec/rec_client_core/src/ecal_rec_impl.cpp
- app/rec/rec_client_core/src/ecal_rec_impl.h
- app/rec/rec_client_core/src/frame_buffer.cpp
- app/rec/rec_client_core/src/frame_buffer.h
- app/rec/rec_client_core/src/job/hdf5_writer_thread.cpp
- app/rec/rec_client_core/src/job/hdf5_writer_thread.h
- app/rec/rec_client_core/src/job/record_job.cpp
- app/rec/rec_client_core/src/job/record_job.h
Fixed the framedrop issue that occured on file closing and opening when the maximum file size has been reached.
Fixes #453
> eCAL Rec: Fixed framedropping when the HDF5 filesize has been reached

- ecal/pb/CMakeLists.txt
- thirdparty/cmake_functions/protoc_functions/protoc_generate_files.cmake
- thirdparty/cmake_functions/protoc_functions/protoc_generate_python.cmake
Issue Number: #438 
This PR adds pre-compiled protobuf files to python wheel.
> Added pre-compiled protobuf files to python wheel

- samples/cpp/services/ecalplayer_client/src/ecalplayer_client.cpp
> Play Service Sample: Fixed step channel command

- app/mon/mon_gui/src/plugin/plugin_wrapper.cpp
> Added missing curly braces

- thirdparty/cmake_functions/cmake_functions.cmake
> missing python cmake file added

- ecal/core/src/service/ecal_clientgate.cpp
- ecal/core/src/service/ecal_clientgate.h
- ecal/core/src/service/ecal_servicegate.cpp
- ecal/core/src/service/ecal_servicegate.h
> shared mutexes used in service gates instead exclusive ones (#496)

- ecal/core/src/ecal_register.cpp
- ecal/core/src/readwrite/ecal_reader.cpp
- ecal/core/src/readwrite/ecal_writer.cpp
> Fix: Bad pub/sub create performance

- lang/python/core/ecal/core/core.py
- lang/python/core/ecal/core/publisher.py
- lang/python/core/src/ecal_wrap.cxx
> Fix: wrong python types for python message publisher create

- doc/rst/development/build_ecal.rst
- doc/rst/development/building_ecal_with_conan_dependencies.rst
- doc/rst/development/ecal_cmake_options.rst
@FlorianReimold, @hannemn please review content (and style ;) )
> Update documentation of eCAL build.

- doc/rst/advanced/ros_comparison.rst
- doc/rst/index.rst
A comparison between eCAL / ROS. Please review for correctness!
> Add comparison ROS vs eCAL.

- ecal/pb/CMakeLists.txt
> don't force ecal::pb as static lib

- doc/rst/development/building_ecal_from_source.rst
Fix some minor documentation issues for Ubuntu build
Some minor fixes - ubuntu only. Moved installing python dependencies in Ubuntu16/18/20 section. Add some comments regarding python CMake options.
> minor doc fixes for building from sources (ubuntu)

- ecal/core/src/readwrite/ecal_reader_tcp.cpp
> should fix #551 (tcp layer starts default thread per subscriber)

- ecal/core/include/ecal/ecal_qos.h
- ecal/core/include/ecal/ecal_tlayer.h
- ecal/core/src/service/ecal_service_server_impl.cpp
Some minor clang findings fixed.
> clang tidy findings

- app/rec/rec_gui/src/qecalrec.cpp
- app/rec/rec_server_cli/src/ecal_rec_server_cli.cpp
> Rec: Default splitsize increased to 1000MiB

- doc/rst/advanced/compatibility.rst
- doc/rst/applications/rec/recorder_architecture.rst
- doc/rst/faq.rst
- doc/rst/getting_started/hello_world.rst
> Doc: Fixed typos

- app/mon/mon_gui/appmenu/app.desktop.in
- app/play/play_gui/appmenu/app.desktop.in
- app/rec/rec_gui/appmenu/app.desktop.in
- app/sys/sys_gui/appmenu/app.desktop.in
- app/util/launcher/appmenu/app.desktop.in
> Added Category (and .desktop version) to .desktop files

- lang/python/core/src/ecal_wrap.cxx
> should fix (Traceback Handling in Python Subscriber)

- contrib/ecalhdf5/CMakeLists.txt
> activate C language explicitly.

- ecal/core/src/ecal_config.cpp
> Refactor code for config path.

- lang/python/core/src/ecal_wrap.cxx
The function is deprecated and basically not needed since 3.7 any more. It was deprecated in 3.9 and will be removed in 3.11.
> Py: Not calling PyEval_InitThreads() for 3.9 and up any more

- lang/python/core/ecal/proto/helper.py
...when building the filedescriptorset for descriptors.
Currently, when a sending a submessage which contain common subtypes, which are defined in different proto files
```
A
├ B
| └ X
└ C
└ X
```
In the displayed case, filedescriptor for `X` would be contained twice in the filedescriptorset, which can lead to problems.
```
X
B
X
C
A
```
The new set contains X only once.
```
X
B
C
A
```
This change is to be cherry-picked to the support branches.
> Py/proto: Make sure that files not added multiple times when building the filedescriptorset for descriptors

- app/mon/mon_plugins/plugin_template/CMakeLists.txt
> Suppressed warnings in mon plugin template

- doc/rst/development/building_ecal_from_source.rst
> Doc: Update documentation for building ecal from source

- ecal/core/src/ecal_config_reader.cpp
> Replaced assert that was causing segfault when ecal.ini was not present

- samples/python/minimal_service/minimal_service.pyproj
- samples/python/minimal_service/minimal_service_client.py
- samples/python/minimal_service/minimal_service_server.py
Python demo service sample is not working because of blocking Python GIL.
Issue Number: #244 and #626
Demo split into separate units and working well.
> python demo service split in separate server and client implementation

- doc/rst/advanced/tutorials.rst
- doc/rst/development/build_ecal.rst
- doc/rst/development/building_ecal_from_source.rst
- tabified dependency install instructions for different Ubuntu versions
- moved Conan Build instructions to Tutorial section
> Doc Improvements: Build instructions

- ecal/core/src/io/udp_sender.cpp
<functional> header is only visibile in the scope of udp_sender.cpp because asio.hpp brings it. In certain cases this can lead to compiler errors. 
Fixes compiles error because of missing header <functional> in certain cases.
> Added missing <functional> header

- doc/extensions/generate_download_tables.py
- doc/extensions/resource/download_table.html.em
The download tables now show which python version is the default for the selected Ubuntu version.
> Doc: Improved download tables for python bindings

- doc/conf_py_buildvars.py.in
- doc/rst/advanced/transport_layers.rst
> Update generic transport layer info

- contrib/ecalhdf5/include/ecalhdf5/eh5_meas.h
- contrib/ecalhdf5/src/eh5_meas.cpp
Issue Number: https://github.com/continental/ecal/issues/692
-
-
-
> HDF5Meas cannot be copied #692

- ecal/core/src/readwrite/ecal_writer_base.h
- ecal/core/src/readwrite/ecal_writer_iceoryx.cpp
- ecal/core/src/readwrite/ecal_writer_iceoryx.h
- ecal/core/src/readwrite/ecal_writer_inproc.cpp
- ecal/core/src/readwrite/ecal_writer_inproc.h
- ecal/core/src/readwrite/ecal_writer_shm.cpp
- ecal/core/src/readwrite/ecal_writer_shm.h
- ecal/core/src/readwrite/ecal_writer_tcp.cpp
- ecal/core/src/readwrite/ecal_writer_tcp.h
- ecal/core/src/readwrite/ecal_writer_udp_mc.cpp
- ecal/core/src/readwrite/ecal_writer_udp_mc.h
atm, the `Getinfo` method does not return anything nor changes a value
Issue Number: #708
Function now returns a struct
> Fixes #708

- ecal/core/src/io/ecal_memfile_pool.cpp
> Restart observer if observing was interrupted.

- ecal/core/src/pubsub/ecal_subgate.cpp
- ecal/core/src/pubsub/ecal_subscriber.cpp
> CSubGate::Unregister return state corrected (fixing #712)

- samples/cpp/misc/proto_dyn/src/proto_dyn.cpp
- testing/contrib/ecalproto/dynproto_test/src/dynproto_test.cpp
> Replace google::protobuf::string with std::string.

- README.md
updated links to renamed repositories
fixed typo for gpsd2ecal
> updated repository links

- ecal/core/CMakeLists.txt
- ecal/core/src/ecal_util.cpp
core logic not depending on eCAL::apps
> eCAL::apps dependency removed

- README.md
> project list updated

- ecal/core/CMakeLists.txt
- ecal/core/src/custom_tclap/advanced_tclap_output.cpp
- ecal/core/src/custom_tclap/advanced_tclap_output.h
Core depends on CustomTclap.
Issue Number: #611
CustomTclap dependency removed by duplicates.
> core dependency CustomTclap removed (#611)

- .gitmodules
> Replaced Submodule reference with new eclipse-ecal repos

- .clang-tidy
The new checks include:
- bugprone
- cppcoreguidelines
- misc
- performance
> Created a more sophisticated .clang-tidy file with more checks

- app/mon/mon_plugins/monitor_tree_view/src/monitor_tree_item.cpp
Issue Number: [731](https://github.com/eclipse-ecal/ecal/issues/731)
-
-
-
> added the size to a filed of byte type

- app/play/play_gui/src/q_ecal_play.cpp
This error dialog is able e.g. to show the "too many open files" error on Linux.
> Play: Added dialog in error-case when connecting to eCAL

- ecal/core/src/io/ecal_memfile.cpp
- ecal/core/src/io/ecal_memfile.h
> Fixed internal CMemoryFile structure compatibility

- doc/doc.hpp
Fix doc type.
- [ x] Documentation content changes
> doc(api): Fix type

- .github/workflows/build-windows.yml
- app/mon/mon_plugin_lib/CMakeLists.txt
This fixes the mon_plugin_lib target, which was not built before.
Fixes #789
> Windows GH Action: Added HAS_QT5=ON for SDK / Debug build

- app/meas_cutter/src/ecal_meas_cutter.cpp
- app/meas_cutter/src/measurement_exporter.cpp
- app/meas_cutter/src/measurement_importer.cpp
- app/meas_cutter/src/utils.h
- doc/rst/applications/meas_cutter/meas_cutter.rst
- doc/rst/applications/meas_cutter/meas_cutter_usage.txt
No functionality to have each topic in a separate file.
Added a flag to enable one file per topic.
> eCAL Meas Cutter : Added flag for one file per channel

- app/iconset/darkmode/console.svg
- app/iconset/ecalicons.qrc
- app/iconset/lightmode/console.svg
- app/mon/mon_gui/src/ecalmon.cpp
- app/play/play_gui/src/ecal_play_gui.cpp
- app/rec/rec_gui/src/ecalrec_gui.cpp
- app/sys/sys_gui/src/ecalsys_gui.cpp
- lib/QEcalParser/include/QEcalParser/ecal_parser_lineedit/ecal_parser_lineedit.h
- lib/QEcalParser/include/QEcalParser/ecal_parser_textedit/ecal_parser_textedit.h
- lib/QEcalParser/resources/qecalparser.qrc
- lib/QEcalParser/resources/show_dialog_darkmode.svg
- lib/QEcalParser/resources/show_dialog_darkmode_src.svg
- lib/QEcalParser/src/ecal_parser_lineedit/ecal_parser_lineedit.cpp
- lib/QEcalParser/src/ecal_parser_textedit/ecal_parser_textedit.cpp
> GUI Apps: Made dark-mode default

- .github/workflows/build-ubuntu-18.yml
- .github/workflows/build-ubuntu-20.yml
- .github/workflows/build-ubuntu-22.yml
This should solve the Ubuntu 18.04 compile issue from  #843
> GH Action / Python: Upgrading pip to solve setuptools dependency issue

- lib/ecal_utils/include/ecal_utils/portable_endian.h
> Restore QNX support.

- README.md
This PR updates a link in the README to the new location of eCal rmw repository.
> Update link to eCal rmw repository in README

- ecal/core/include/ecal/ecal_clang.h
- ecal/core/include/ecal/ecal_process.h
- ecal/core/include/ecal/ecal_publisher.h
- ecal/core/src/ecal_clang.cpp
- ecal/core/src/io/ecal_memfile_header.h
- ecal/core/src/io/ecal_memfile_pool.cpp
- ecal/core/src/io/ecal_memfile_pool.h
- ecal/core/src/io/ecal_memfile_sync.cpp
- ecal/core/src/io/ecal_memfile_sync.h
- ecal/core/src/pubsub/ecal_publisher.cpp
- ecal/core/src/readwrite/ecal_reader_shm.cpp
- ecal/core/src/readwrite/ecal_writer.cpp
- ecal/core/src/readwrite/ecal_writer.h
- ecal/core/src/readwrite/ecal_writer_data.h
- ecal/core/src/readwrite/ecal_writer_shm.cpp
- ecal/core/src/readwrite/ecal_writer_shm.h
- lang/python/core/ecal/core/core.py
- lang/python/core/ecal/core/publisher.py
- lang/python/core/src/ecal_wrap.cxx
- samples/cpp/performance/performance_rec/src/performance_rec.cpp
- samples/cpp/performance/performance_rec_cb/src/performance_rec_cb.cpp
- samples/cpp/performance/performance_snd/src/performance_snd.cpp
Provide new shm handshake timeout API for the `CPublisher`.
Fixes #875
> shm handshake timeout CPublisher API (fixing issue #875)

- app/sys/sys_gui/src/widgets/taskwidget/task_widget.cpp
- app/sys/sys_gui/src/widgets/taskwidget/task_widget.h
- [x ] Feature
Issue Number: 573
Add functionality to a task's right-click context menu for moving the window of a task to the front
-
-
-
> Add bring window to front functionality

- app/rec/rec_addon_dummy/CMakeLists.txt
> Fix: `rec_addon_dummy` finds and links threads. (#938)

- .github/workflows/build-ubuntu-22.yml
> GH Actions: Added Pyhton 3.11 Wheel for Jammy

- .github/workflows/build-windows.yml
- app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.cpp
Unfortunately I have no idea why the commits fixed the issue, but just in case it ever happens again we may now get a hint why it failed.
> Added errror printing to eCAL Rec Tests

- app/mon/mon_gui/src/widgets/visualisation_widget/visualisation_widget.cpp
> Mon: Don't warn for 2 or more publishers on a topic

- .github/workflows/build-macos.yml
> Install pkg-config in MacOS github workflow

- app/mon/mon_cli/CMakeLists.txt
See commit message.
See commit message.
> Mon: Replaced deprecated cmake pb target in mon cli

- build_win/win_make_cmake.bat
win_make_cmake.bat file fixed for new folder of requirements.txt
> Minimal fix for python requirements

- README.md
ecal-foxglove-bridge and ecal-mcap-tools add to Readme
> Adding the new Foxglove repositories to Readme

- lang/csharp/Continental/eCAL/Core/ecal_clr.cpp
- lang/csharp/Continental/eCAL/Core/ecal_clr.h
- samples/csharp/CMakeLists.txt
- samples/csharp/minimal/minimal_client/CMakeLists.txt
- samples/csharp/minimal/minimal_client/minimal_client.cs
- samples/csharp/minimal/minimal_server/CMakeLists.txt
- samples/csharp/minimal/minimal_server/minimal_server.cs
This is the last C# PR, now adding services.
Please review regarding String / Byte[] usage in the API.
> Add Service / Client interface to C# and add samples

- ecal/core/include/ecal/ecal_callback.h
- ecal/core/src/readwrite/ecal_reader.cpp
- ecal/core/src/readwrite/ecal_reader.h
- ecal/core/src/readwrite/ecal_writer.cpp
- ecal/core/src/readwrite/ecal_writer.h
- ecal/core/src/service/ecal_clientgate.cpp
- ecal/core/src/service/ecal_service_client_impl.cpp
- ecal/core/src/service/ecal_service_client_impl.h
- ecal/core/src/service/ecal_service_server_impl.cpp
- ecal/core/src/service/ecal_service_server_impl.h
- ecal/core/src/service/ecal_servicegate.cpp
- ecal/core_pb/src/ecal/core/pb/service.proto
- ecal/core_pb/src/ecal/core/pb/topic.proto
ecal/ecal_callback.h reverted completely to previous version to keep ABI compatibility
> hotfix/public-api-reverted and versions for pub/sub removed again

- .github/workflows/build-windows.yml
- app/mon/mon_tui/CMakeLists.txt
- thirdparty/build-ftxui.cmake
eCAL installer will be build with v142 toolset.
> Upgrade github actions ecal build to v142, and remove C++17 hack.

- colcon.pkg
- package.xml
> feat: add package.xml

- ecal/core/include/ecal/msg/publisher.h
> Core: Added missing overload of CMsgPublisher::Create() for STopicInformation

- ecal/core/src/ecal_process.cpp
> Core: Dump experimental settings in Process::DumpConfig()

- testing/ecal/clientserver_test/src/clientserver_getservices.cpp
Fixes #1162 
Must be cherry-picked to:
- 5.12
> Adapted clientserver test to the changed API

- ecal/core/CMakeLists.txt
- ecal/core/include/ecal/ecal_payload_writer.h
- ecal/core/src/ecal_buffer_payload_writer.h
- ecal/core/src/pubsub/ecal_publisher.cpp
- ecal/core/src/readwrite/ecal_writer.cpp
Unintended public API `CBufferPayloadWriter`
Fixes #1173
`CBufferPayloadWriter` removed from public API.
**Cherry-pick to:**
- 5.12
> CBufferPayloadWriter moved to internal API

- .github/workflows/build-windows.yml
Before: windows-setup-eclipse.zip
Now: windows-setup-signed.zip
- _none_
> GH Actions: Renamed signed Windows artifact

- samples/cpp/benchmarks/perftool/CMakeLists.txt
- samples/cpp/benchmarks/perftool/Readme.md
- samples/cpp/benchmarks/perftool/src/main.cpp
- samples/cpp/benchmarks/perftool/src/publisher.cpp
- samples/cpp/benchmarks/perftool/src/publisher.h
- samples/cpp/benchmarks/perftool/src/publisher_statistics.h
- samples/cpp/benchmarks/perftool/src/subscriber.cpp
- samples/cpp/benchmarks/perftool/src/subscriber.h
- samples/cpp/benchmarks/perftool/src/subscriber_statistics.h
Added the eCAL Perftool as  Sample.
The original development repository can be found here: https://github.com/FlorianReimold/ecal-perftool
The following files are missing here, as adding them makes no sense:
- LICENSE
- GH Action files
- .clang-tidy file
- .gitignore file
- _none_
> Samples: Added perftool

- .github/workflows/build-windows.yml
Have github actions build eCAL whls for new Python version 3.12
- 5.11
-  5.12
> GH-Actions: Add Python 3.12 wheels.

- ecal/core/cfg/ecal.ini
THE GLOBAL CONFIGURATION IS NICELY FORMATTED AGAIN.
* none
> ecal ini file formatting

- .github/workflows/clang-tidy-review-post-comments.yml
- .github/workflows/clang-tidy-review.yml
clang tidy review gh action update
> clang-tidy review gh action updated 0.12.2 -> 0.14.0

- doc/extensions/generate_download_tables.py
Added Ubuntu Noble (24.04) to the codename dictionary
- _none_
> Doc: Added Ubuntu Noble (24.04) to the codename dictionary

- thirdparty/qwt/Modules/Findqwt.cmake
> Fixed Findqwt.cmake

- ecal/core/src/util/ecal_expmap.h
- testing/ecal/expmap_test/src/expmap_test.cpp
Provide a const_iterator for CExpMap.
> Provide a const iterator to iterate through a const ExpMap.

- doc/rst/advanced/layers/tcp.rst
> Doc: Improved TCP Layer documentation

- ecal/core/src/ecal_registration_receiver.h
> Added missing include

- .github/pull_request_template.md
> [GH PR Template] Added new template options for eCAL 5 / eCAL 5.13

- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu-20.yml
- .github/workflows/build-ubuntu-22.yml
- .github/workflows/build-windows.yml
- .github/workflows/documentation.yml
- .github/workflows/ecal-fat-source.yml
- .github/workflows/pr-auto-approve.yml
- build_win/download_npcap.ps1
- build_win/win_make_cmake.bat
* windows build batch files HAS_QT5 renamed to HAS_QT
* github actions checkout updated from v3 to v4
* unnecessary npcap download powershell script removed
- _none_
> [cmake, gh actions, batch] build cmake options and gh actions updated 

- package.xml
package.xml: Bumped version number to 6.0.0
- _none_
> package.xml: Bumped version number to 6.0.0

- .github/pull_request_template.md
We will backport later when we actually know what we want to have for 5.14
> [GH PR Template] Removed master-v5

- .github/workflows/clang-tidy-review.yml
> [GH Actions] Changed HAS_QT5 to HAS_QT in clang-tidy-review action

- ecal/service/ecal_service/src/client_session_impl_v1.cpp
Silences an unreferenced parameter warning in release mode (in Debug mode this variable is referenced).
- master
> [warnings] silence unused parameter warning.

- lib/ecal_utils/include/ecal_utils/filesystem.h
Extra semicolon removed.
- _none_
> [warnings] extra semicolon removed

- lang/python/core/CMakeLists.txt
- lang/python/core/src/ecal_wrap.cxx
* python binding core_pb dependency removed (by using logging and monitoring struct API)
* added python monitoring for client entities
- _none_
> [core] python binding uses logging and monitoring struct API

- samples/CMakeLists.txt
- samples/cpp/services/ecalplayer_gui_client/CMakeLists.txt
- samples/cpp/services/rec_client_service_gui/CMakeLists.txt
- samples/cpp/services/rec_server_service_gui/CMakeLists.txt
Added Qt6 support to samples again
The Qt6 support was removed by accident by #1370
- Fixes #1441
> Added Qt6 support to samples, again

- .github/workflows/cherry-pick-to.yml
Fixed typo in cherry-pick action
> [GH Actions] Fixed typo in cherry-pick action

- .github/workflows/cherry-pick-label-check.yml
- Run cherry-pick-label-check when a PR is opened
- Run the action when the PR branch changes (synchronize event)
- Fixed detection of required label
> [GH Actions] Fixed cherry-pick-label-check action

- doc/requirements.txt
Downgraded empy due to incompatiblity with empy 4.0
> [Doc] Downgraded empy due to incompatiblity with empy 4.0

- doc/rst/_templates/footer.html
Fixed malformed HTML code of page footer
> [Doc] Fixed malformed HTML code of page footer

- .github/workflows/documentation.yml
Documentation is now built from support/v5.13 branch
> [Doc] Documentation is now built from support/v5.13 branch

- .github/workflows/cherry-pick-to.yml
This allows the action to trigger workflows and to cherry-pick workflow changes as well.
> [GH Actions] Added CHERRY_PICK_GITHUB_TOKEN to cherry-pick action

- .github/workflows/cherry-pick-to.yml
Fixed typos in cherry-pick-to workflow.
> [GH Actions] Fixed typos in cherry-pick-to workflow.

- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu-20.yml
- .github/workflows/build-ubuntu-22.yml
- .github/workflows/documentation.yml
- build_win/win_make_cmake.bat
> [cmake] quotation marks removed from submodule_dependencies.cmake

- ecal/tests/CMakeLists.txt
Sync PR with ecal-core, 2024-04-17.
> [core] sync with ecal core 2024 04 17

- ecal/core/src/io/udp/ecal_udp_sample_receiver.cpp
In case of a corrupt UDP receive buffer, the parsing of sample name and payload can lead to memory access violations. This should be fixed by checking sample and payload sizes.
> check sample name / payload size before processing receive udp samples

- app/mon/mon_gui/src/widgets/models/service_tree_item.h
Related to #1550
5.13 and 5.12 are handled by different PRs.
> [Mon] Fix service collisions on ecal_mon_gui (master)

- app/mon/mon_gui/src/widgets/models/service_tree_item.cpp
Related to https://github.com/eclipse-ecal/ecal/pull/1550
> [Mon] Fix service collisions on ecal_mon_gui (5.12)

- ecal/core/src/io/udp/ecal_udp_sample_receiver.cpp
Build fails otherwise on ubuntu 18.
> Added iostream to ecal_udp_sample_receiver.cpp source.

- ecal/core/src/service/ecal_service_singleton_manager.cpp
> [core, service] service log level changed from info to debug1

- ecal/core/src/readwrite/ecal_writer.cpp
> [core] send frequency calculation fixed in case of unconnected publisher

- .github/workflows/build-macos.yml
> [gh actions] update setup-python action for macos

- ecal/core/src/registration/ecal_registration_receiver.cpp
- ecal/core/src/registration/ecal_registration_receiver.h
- ecal/tests/cpp/clientserver_proto_test/src/clientserver_test_proto.cpp
- ecal/tests/cpp/clientserver_test/src/clientserver_test.cpp
* loopback logic (EnabledLoopback) was ignored for service registration
* some refactoring of the logic whether to process a sample registration or not
* user registration callback performance fix
* samples will be reserialized only if the corresponding callback is set
> [core] registration-loopback-logic-fixed-for-service-registrations

- ecal/core/src/pubsub/ecal_pubgate.cpp
- ecal/core/src/pubsub/ecal_pubgate.h
- ecal/core/src/pubsub/ecal_subgate.cpp
- ecal/core/src/pubsub/ecal_subgate.h
- ecal/core/src/readwrite/ecal_reader.cpp
- ecal/core/src/readwrite/ecal_reader.h
- ecal/core/src/readwrite/ecal_writer.cpp
- ecal/core/src/readwrite/ecal_writer.h
- ecal/core/src/registration/ecal_registration_provider.cpp
- ecal/core/src/registration/ecal_registration_provider.h
- ecal/core/src/service/ecal_clientgate.cpp
- ecal/core/src/service/ecal_clientgate.h
- ecal/core/src/service/ecal_service_client_impl.cpp
- ecal/core/src/service/ecal_service_client_impl.h
- ecal/core/src/service/ecal_service_server_impl.cpp
- ecal/core/src/service/ecal_service_server_impl.h
- ecal/core/src/service/ecal_servicegate.cpp
- ecal/core/src/service/ecal_servicegate.h
- ecal/tests/cpp/util_test/src/util_gettopics.cpp
Registration logic from RefreshRegistration -> ApplySample to GetRegistration changed.
> [core] active-registration-logic-getter

- ecal/core/src/serialization/ecal_serialize_logging.cpp
- ecal/core/src/serialization/ecal_serialize_monitoring.cpp
- ecal/core/src/serialization/ecal_serialize_sample_payload.cpp
- ecal/core/src/serialization/ecal_serialize_sample_registration.cpp
- ecal/core/src/serialization/ecal_serialize_service.cpp
> [core] serialization-decode-error-handling

- ecal/core/src/io/ecal_memfile_pool.cpp
- testing/ecal/pubsub_test/src/pubsub_test.cpp
zero length payload was not transferred over shm in zero copy mode
> [core] zero-copy-zero-payload-shm-transfer-5-12

- ecal/core/src/io/shm/ecal_memfile_pool.cpp
- testing/ecal/pubsub_test/src/pubsub_test.cpp
zero length payload was not transferred over shm in zero copy mode
> [core] zero-copy-zero-payload-shm-transfer-5-13

- ecal/core/src/service/ecal_service_server_impl.cpp
> [core] remove-callbacks-before-stopping-tcp-protocol-layer

- ecal/core/src/pubsub/ecal_pubgate.cpp
- ecal/core/src/pubsub/ecal_subgate.cpp
- ecal/core/src/readwrite/ecal_reader.cpp
- ecal/core/src/readwrite/ecal_reader.h
- ecal/core/src/readwrite/ecal_writer.cpp
- ecal/core/src/readwrite/ecal_writer.h
- ecal/core/src/serialization/ecal_struct_sample_registration.h
Use the new Registration::SampleIdentifier in datawriter / datareader.
> [core] Remove SPublicationInfo / SSubscriptionInfo type.

- ecal/core/src/service/ecal_service_server_impl.cpp
remove callbacks before stopping tcp protocol layer
> [core] remove-callbacks-before-stopping-tcp-protocol-layer-5-13

- ecal/core/src/monitoring/ecal_monitoring_impl.cpp
enable loopback for monitoring functionality
> [core] enable-loopback-for-monitoring-functionality

- ecal/core/src/config/configuration_reader.cpp
- ecal/core/src/config/configuration_to_yaml.cpp
- ecal/core/src/config/ecal_cmd_parser.cpp
- ecal/core/src/config/ecal_config.cpp
- ecal/core/src/ecal_global_accessors.cpp
- ecal/core/src/registration/ecal_registration_provider.h
- ecal/core/src/serialization/ecal_struct_sample_registration.h
- ecal/core/src/types/ecal_custom_data_types.cpp
Fix some warnings and VS2017 build errors.
> [core] warnings and build issue fixes

- ecal/core/CMakeLists.txt
- ecal/core/src/builder/monitoring_attribute_builder.cpp
- ecal/core/src/builder/monitoring_attribute_builder.h
- ecal/core/src/ecal_globals.cpp
- ecal/core/src/monitoring/attributes/monitoring_attributes.h
- ecal/core/src/monitoring/ecal_monitoring_def.cpp
- ecal/core/src/monitoring/ecal_monitoring_def.h
- ecal/core/src/monitoring/ecal_monitoring_impl.cpp
- ecal/core/src/monitoring/ecal_monitoring_impl.h
> [config] Monitoring uses SAttributes instead of config object

- ecal/core/src/config/default_configuration.cpp
- ecal/tests/cpp/config_test/src/config_test.cpp
Removed quoteStrings and unused variable in config test
> [config] Removed some warnings

- ecal/core/src/config/ecal_config_initializer.cpp
- ecal/core/src/ecal.cpp
> [config] Removed InitGlobals from config to eCAL::Initialize

- ecal/core/CMakeLists.txt
> [core] ecal_config.h added to visual studio project

- cpack/innosetup/ecal_setup.iss.in
- samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
* sample logic aligned for massive_pub_sub
* InnoSetup script fixed for strange CMake configuration path behavior (needs to be fixed in a better way)
> [core] ecal sample logic massive_pub_sub aligned with master

- .github/workflows/build_wheels.yml
> [build] Enable wheel build on branch master

- .github/workflows/build_wheels.yml
- pyproject.toml
Updated cibuildwheel usage to use v2.21
Using hatchling as build tool
> [python] Updated wheel build

- app/mon/mon_gui/src/widgets/ecalmon_tree_widget/ecalmon_tree_widget.cpp
- app/mon/mon_gui/src/widgets/models/host_tree_item.cpp
- app/mon/mon_gui/src/widgets/models/topic_tree_item.cpp
- app/mon/mon_gui/src/widgets/visualisation_widget/visualisation_widget.cpp
- Do not get a topic type / encoding from utils if this topic has not set them.
- Avoid copies
> [MonGUI] minor performance improvements. 

- .github/workflows/build-ubuntu-24.yml
added gh workflow for ubuntu24
> Enable Ubuntu 24 gh action

- ecal/core/src/pubsub/config/builder/reader_attribute_builder.cpp
- ecal/core/src/pubsub/config/builder/writer_attribute_builder.cpp
- ecal/core/src/readwrite/config/builder/shm_attribute_builder.cpp
- ecal/core/src/readwrite/config/builder/tcp_attribute_builder.cpp
- ecal/core/src/readwrite/config/builder/udp_attribute_builder.cpp
- ecal/core/src/readwrite/tcp/config/builder/data_reader_tcp_attribute_builder.cpp
- ecal/core/src/readwrite/udp/config/builder/udp_attribute_builder.cpp
Removed unintentially "#pragma once" from source files.
> [config] Hotfix: pragma once removal in source files

- samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
See title.
Problem occured for vs2017 build.
> [Samples] Added algorithm header for massive pubsub

- doc/extensions/generate_download_tables.py
Added default python version for Ubuntu 24.04
> [Doc] Added default python version for Ubuntu 24.04

- README.md
Updated supported operating systems
> [Readme.md] Updated supported operating systems

- .gitignore
- scan-dependencies-with-dash.py
Added script for creating License reviews with the eclipse-dash-licensing-tool
> Added script for creating License reviews with the eclipse-dash-licensing-tool

- .github/workflows/build-ubuntu.yml
- .gitmodules
- thirdparty/zlib/build-zlib.cmake
> Removed zlib

- app/meas_cutter/src/config_file_parser.h
- app/meas_cutter/src/utils.h
- contrib/measurement/hdf5/include/ecal/measurement/hdf5/writer.h
- ecal/core/CMakeLists.txt
- ecal/core/include/ecal/msg/protobuf/dynamic_json_subscriber.h
- ecal/samples/c/pubsub/string/minimal_rec/src/minimal_rec.c
- ecal/samples/c/pubsub/string/minimal_rec_cb/src/minimal_rec_cb.c
- ecal/samples/c/pubsub/string/minimal_snd/src/minimal_snd.c
- ecal/samples/c/services/minimal_client_c/src/minimal_client_c.c
- ecal/samples/c/services/minimal_server_c/src/minimal_server_c.c
- ecal/samples/cpp/benchmarks/massive_pub_sub/src/massive_pub_sub.cpp
- ecal/samples/cpp/benchmarks/pubsub_throughput/src/pubsub_throughput.cpp
- ecal/samples/cpp/pubsub/protobuf/person_loopback/src/person_loopback.cpp
- ecal/tests/cpp/pubsub_test/src/pubsub_connection_test.cpp
- ecal/tests/cpp/pubsub_test/src/pubsub_test.cpp
> common warning fixes

- doc/rst/configuration/runtime_configuration.rst
- ecal/core/include/ecal/config/publisher.h
- ecal/core/include/ecal/config/transport_layer.h
- ecal/core/include/ecal/config/user_arguments.h
- ecal/core/include/ecal/types/ecal_custom_data_types.h
- ecal/core/src/config/configuration_to_yaml.cpp
- ecal/tests/cpp/config_test/src/config_test.cpp
Removed ConstrainedInteger and replaced it by unsigned int.
> [config] Removed ConstrainedInteger

- thirdparty/curl/build-curl.cmake
> [submodules] Updated curl to 8.11.0

- .github/workflows/build-ubuntu.yml
- .gitmodules
- thirdparty/libssh2/build-libssh2.cmake
> [submodules] Removed libssh submodule

- contrib/ecalhdf5/src/eh5_meas_api_v2.cpp
Added missing algorithm header to eh_meas_api_v2.cpp
> Hotfix: missing header

- ecal/core/src/ecal.cpp
> [config] Call InitFromConfig() when initialize is not called with config parameter

- app/mon/mon_cli/src/ecal_mon_cli.cpp
- app/mon/mon_gui/src/ecalmon.cpp
- app/mon/mon_tui/src/main.cpp
Also read the config yaml before initialization for all monitor apps.
> [config] Hotfix/mon apps initialization

- .github/workflows/build-ubuntu.yml
> [gh actions] Correct naming for Ubuntu versions

- contrib/mma/include/windows/mma_windows.h
- contrib/mma/src/windows/mma_windows.cpp
MMA network resource handled wrong (needs to be a class member to keep states).
> [app] mma-network-send-receive-fix

- pyproject.toml
- thirdparty/hdf5/build-hdf5.cmake
> Fix broken wheel build.

- ecal/core/src/config/configuration_to_yaml.cpp
- ecal/core/src/config/configuration_to_yaml.h
> [config] Removed template definition from src file to inline 

- serialization/flatbuffers/samples/pubsub/monster_rec/monster_rec.cpp
Build was broken by porting subscribers from v5 to v6.
> [flatbuffers] fix monster_rec sample.

- .github/workflows/build_wheels.yml
> [GH Action] Updated CI buildwheel step

- doc/rst/getting_started/src/hello_world/hello_world_rec/main.cpp
- doc/rst/getting_started/src/hello_world_protobuf/protobuf_rec/main.cpp
> [doc] Hello world src adaption to new API

- contrib/mma/src/mma_application.cpp
> [mma] MMA init condition change.

- app/mon/mon_gui/src/widgets/system_information_widget/system_information_widget.cpp
> [Mon] eCAL Mon can now open the yaml as root on Ubuntu

- app/rec/rec_tests/rec_rpc_tests/src/external_ecal_rec.cpp
This hopefully fixes the CI test issues
> [Tests] Increased timeouts of rec rpc test

- serialization/common/common/include/ecal/msg/subscriber.h
Previously, the deserializer was stored in a lambda function. This caused an issue with protobuf that lead to an segmentation fault on destroying the object. With this fix, the deserializer becomes a member variable of the subscriber, so that it will live until the subscriber is destroyed, preventing faulty access.
> [core] Make deserializer member of subscriber

- doc/rst/ecal_6_migration.rst
Publisher, subscriber, server, client description
Small configuration description and link to related page
> [docu] Migration guide updates

- doc/rst/ecal_6_migration.rst
- doc/rst/index.rst
This added guide tackles many of the the major changes from eCAL 5 to eCAL 6.
> [docu] eCAL 6 migration guide

- lang/c/samples/CMakeLists.txt
- lang/c/samples/pubsub/string/hello_receive/CMakeLists.txt
- lang/c/samples/pubsub/string/hello_receive/src/hello_receive.c
- lang/c/samples/pubsub/string/hello_send/CMakeLists.txt
- lang/c/samples/pubsub/string/hello_send/src/hello_send.c
- serialization/string/samples/pubsub/hello_send/src/hello_send.cpp
- Renamed the hello samples for c
- Set frequency to 500ms in c and cpp hello_send samples
- Added a counter to hello_send.c
> renamed send/receiver for c samples

- serialization/string/string/include/ecal/msg/string/publisher.h
Updated description of string publisher class
> Fixing description of string publisher class

- .github/actions/ccache-prepare/action.yml
- .github/actions/ccache-save/action.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-ubuntu.yml
- doc/CMakeLists.txt
> [CI] Use ccache on MacOS (#2134) - cherry-pick

- lang/csharp/CMakeLists.txt
> [csharp] Make CMAKE_DOTNET_TARGE_FRAMEWORK_VERSION a cached variable.

- ecal/core/src/readwrite/tcp/ecal_reader_tcp.cpp
The code stays compatible to tcp_pubsub 1.x as well.
> [Core / Submodule] Updated tcp_pubsub to 2.0.1

- scan-dependencies-with-dash.py
- This also updates npcap SDK and Pcap++ through udpcap
- Updated the dash scan script
- This is important for Asio >= 1.33 compatibility
> [Submodules] Updated ecaludp to 0.1.2 and udpcap to 2.0.3 submodules

- serialization/string/string/include/ecal/msg/string/serializer.h
> [msg] Correct warning.

- ecal/samples/cpp/pubsub/binary/blob_send/src/blob_send.cpp
- ecal/service/test/src/ecal_tcp_service_test.cpp
- lang/c/samples/services/mirror_server_c/src/mirror_server_c.c
- serialization/capnproto/samples/measurement/addressbook_write.cpp
- serialization/capnproto/samples/pubsub/addressbook_send/src/addressbook_send.cpp
> [samples] Fix several build warnings in eCAL samples.

- lang/csharp/Eclipse.eCAL.Core.Samples/pubsub/blob_receive_csharp.cs
- lang/csharp/Eclipse.eCAL.Core.Samples/pubsub/blob_send_csharp.cs
- lang/csharp/Eclipse.eCAL.Core/CMakeLists.txt
- lang/csharp/Eclipse.eCAL.Core/include/clr_process.h
- lang/csharp/Eclipse.eCAL.Core/include/clr_process_severity.h
- lang/csharp/Eclipse.eCAL.Core/src/clr_process.cpp
- lang/csharp/Eclipse.eCAL.Protobuf.Samples/pubsub/person_receive_csharp.cs
- lang/csharp/Eclipse.eCAL.Protobuf.Samples/pubsub/person_send_csharp.cs
- lang/csharp/Eclipse.eCAL.String.Samples/pubsub/hello_receive_csharp.cs
- lang/csharp/Eclipse.eCAL.String.Samples/pubsub/hello_send_csharp.cs
Now you can utilize the process functions in C#. Docu samples are updated to set their state.
> [lang] C#: Wrapped process.h

- app/rec/rec_client_core/src/addons/pipe_handler.cpp
removed atlconv.h
modified pipe_handler.cpp
> modified pipe_handler

- ecal/core/src/ecal_event.cpp
> Fixed a critical race condition in eCAL's posix event implementation

- .github/workflows/build-macos.yml
> Downgrade protobuf on macos.

- doc/rst/advanced/message_drops.rst
- doc/rst/versions/6.0/compatibility_table.txt
> [docu] Added compatibility information and small change in msg drops info.

- ecal/core/include/ecal/types/process.h
- ecal/core/src/ecal_global_accessors.cpp
- ecal/core/src/ecal_global_accessors.h
- ecal/core/src/ecal_process.cpp
- ecal/core/src/registration/ecal_process_registration.cpp
- adding process state structure as types
- handling global process state with mutexes
- fixes #2262
> [core] Process state structure

- contrib/ecalhdf5/include/ecalhdf5/eh5_meas_api_v2.h
- contrib/ecalhdf5/include/ecalhdf5/eh5_meas_api_v3.h
- contrib/ecalhdf5/src/eh5_meas_api_v2.cpp
- contrib/ecalhdf5/src/eh5_meas_api_v3.cpp
- contrib/ecalhdf5/src/eh5_meas_dir.cpp
- contrib/ecalhdf5/src/eh5_meas_dir.h
- contrib/ecalhdf5/src/eh5_meas_file_v1.cpp
- contrib/ecalhdf5/src/eh5_meas_file_v1.h
- contrib/ecalhdf5/src/eh5_meas_file_v2.cpp
- contrib/ecalhdf5/src/eh5_meas_file_v2.h
- contrib/ecalhdf5/src/eh5_meas_file_writer_v5.cpp
- contrib/ecalhdf5/src/eh5_meas_file_writer_v5.h
- contrib/ecalhdf5/src/eh5_meas_file_writer_v6.cpp
- contrib/ecalhdf5/src/eh5_meas_file_writer_v6.h
- contrib/ecalhdf5/src/eh5_meas_impl.h
- tests/contrib/ecalhdf5/hdf5_test/src/hdf5_test.cpp
Allow to retrieve data from hdf5 in one go, instead of calling serparately do get size and data.
> [hdf5] Add function to retrieve data from measurement into a std::string

- ecal/core/src/ecal_globals.cpp
- ecal/core/src/ecal_globals.h
- ecal/core/src/pubsub/ecal_publisher_impl.cpp
- ecal/core/src/pubsub/ecal_publisher_impl.h
- ecal/core/src/pubsub/ecal_subscriber_impl.cpp
- ecal/core/src/pubsub/ecal_subscriber_impl.h
- ecal/core/src/registration/ecal_registration_provider.cpp
- ecal/core/src/util/ecal_thread.h
This reverts commit 786b76041f6329702e4188fec805c207bc20ac30.
Performance issues occured.
> [core] Revert previous changes based on sanitizer findings
